---
settings:
  name: ONTAP tools for VMware vSphere 10.3
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP Tools für VMware vSphere 10.3
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: migrate
  - section: automation
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
