---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade, ONTAP tools, VMware vSphere, HA, non-HA, low RPO backup, SRA adapter, vCenter Server 
summary: ONTAP tools for VMware vSphere können von Version 10.4 oder 10.5 auf 10.6 für HA und Nicht-HA-Bereitstellungen unter Verwendung der erforderlichen Vorabprüfungen und Sicherungsschritte aktualisiert werden. 
---
= Upgrade von ONTAP tools für VMware vSphere 10.x auf 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein direktes Upgrade von ONTAP tools for VMware vSphere 10.4 oder 10.5 auf 10.6 ist möglich. Für ein Upgrade von ONTAP tools 10.0, 10.1, 10.2 oder 10.3 auf 10.6 ist zunächst ein Upgrade auf 10.4 oder 10.5 erforderlich.

[NOTE]
====
* Für ASA r2-Systeme sollte vor der Einrichtung weiterer Storage Availability Zones (SAZs) ein Upgrade auf ONTAP tools for VMware vSphere auf Version 10.6 und ONTAP auf Version 9.16.1 durchgeführt werden.
* Wenn das Upgrade von ONTAP tools for VMware vSphere 10.4 oder 10.5 auf 10.6 fehlschlägt, ist ein Rollback nicht möglich. Zur Wiederherstellung der Konfiguration kann eine Wiederherstellung mit niedrigem RPO oder per Snapshot erfolgen. Für ONTAP tools for VMware vSphere 10.3 und frühere Versionen kann eine Wiederherstellung mit Zero-RPO erfolgen. Nach der Wiederherstellung in geschützten Umgebungen sollte der Datenspeicherschutz erneut validiert und der Status sowie die Beziehungen der Schutzgruppen überprüft werden.


====
.Bevor Sie beginnen
* Alle Knoten müssen aktiv sein, bevor das Upgrade gestartet wird.
* Stellen Sie sicher, dass das ONTAP -Systemzertifikat und die integrierten vCenter-Zertifikate mindestens 5 Tage gültig sind. Wenn die Zertifikate früher ablaufen, schlägt das Upgrade fehl.
* Stellen Sie sicher, dass Sie auf allen Knoten über eine fünfte Festplatte mit einer Kapazität von 100 GB verfügen.
* Überprüfen Sie, ob die Knotenkonfiguration den Spezifikationen in der folgenden Tabelle entspricht.


|===
| Bereitstellungstyp | CPU-Kerne pro Node | Speicher (GB) pro Knoten | Speicherplatz (GB) pro Knoten | Gesamtzahl der CPU-Kerne | Gesamtspeicher (GB) | Gesamtspeicherplatz (GB) 


| Nicht-HA klein | 9 | 18 | 350 | 9 | 18 | 350 


| Non-HA Medium | 13 | 26 | 350 | 13 | 26 | 350 


| HA klein | 9 | 18 | 350 | 27 | 54 | 1050 


| HA Mittel | 13 | 26 | 350 | 39 | 78 | 1050 


| HA groß | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Eine Sicherung mit niedrigem RPO aktivieren und sicherstellen, dass eine Sicherung in der vSphere Client-Oberfläche sichtbar ist. Der Sicherungsordner sollte vor dem Upgrade heruntergeladen werden.
* Es wird eine Datensicherung mit niedrigem RPO empfohlen.  Bei einer Bereitstellung ohne Hochverfügbarkeit können Sie jedoch vor dem Upgrade einen statischen Snapshot der virtuellen Maschine der ONTAP -Tools erstellen.
+
Siehe link:../manage/backup-settings.html["Backup-Einstellungen bearbeiten"] Und link:../manage/recover-backup.html["Wiederherstellen des ONTAP Tools-Setups"] Weitere Informationen zu Datensicherung und -wiederherstellung finden Sie hier.



.Schritte
. Laden Sie ONTAP-Tools für VMware vSphere hoch, aktualisieren Sie ISO in die Content Library.
. Wählen Sie auf der primären VM-Seite *Aktionen* > *Einstellungen bearbeiten*. Um den primären VM-Namen zu ermitteln:
+
.. Aktivieren Sie die Diagnose-Shell auf einem beliebigen Knoten.
.. Führen Sie folgenden Befehl aus:
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. Wählen Sie im Fenster „Einstellungen bearbeiten“ unter dem Feld „CD/DVD-Laufwerk“ die *ISO-Datei der Inhaltsbibliothek* aus.
. Wählen Sie die ISO-Datei aus, aktivieren Sie das Kontrollkästchen *Verbunden* für das Feld *CD/DVD-Laufwerk* und klicken Sie auf *OK*.
. Melden Sie sich beim vCenter Server an.
. Die primäre ONTAP tools VM suchen und die Webkonsole öffnen.
. Melden Sie sich mit den  `maint` Zugangsdaten an.
. Geben Sie *2* ein, um das Menü *Systemkonfiguration* auszuwählen.
. *6* eingeben, um die Option *Upgrade* auszuwählen.
. Geben Sie die vCenter-Anmeldeinformationen ein, wenn Sie dazu aufgefordert werden. Dies ist die vCenter-Instanz, auf der die ONTAP tools gehostet werden.
+
Wenn Sie ONTAP tools in einer Zwei-vCenter-Server-Topologie verwenden – wobei die Appliance auf einer vCenter-Instanz gehostet wird und eine andere verwaltet –, können Sie der vCenter-Instanz, die die ONTAP tools hostet, eine eingeschränkte Rolle zuweisen. Sie können einen dedizierten vCenter-Benutzer und eine Rolle erstellen, die nur die für die OVF-Vorlagenbereitstellung erforderlichen Berechtigungen besitzt. Weitere Informationen finden Sie in der Liste der Rollen link:../concepts/rbac-vcenter-use.html#vsphere-object-hierarchy["In ONTAP Tools für VMware vSphere 10 enthaltene Rollen"].

+
Stellen Sie für die vCenter-Instanz, die von ONTAP -Tools verwaltet wird, sicher, dass das vCenter-Benutzerkonto über Administratorrechte verfügt.

+
Wenn während des Upgrades in integrierten Speicher-Backend-Zertifikaten SAN-Einträge (Subject Alternative Name) fehlen, erhalten Sie eine Meldung mit dem Hinweis auf den fehlenden SAN.  Wenn Sie ohne Validierung des SAN fortfahren, wird das Upgrade fortgesetzt. Dies wird jedoch aufgrund potenzieller Sicherheitsrisiken nicht empfohlen.

. Wenn Sie ein Upgrade durchführen, werden die folgenden Aktionen automatisch ausgeführt:
+
.. Das Gateway-Zertifikat wird mit einer Gültigkeitsdauer von einem Jahr erneuert. Beim Entfernen des vorherigen SRA-Adapters und Hochladen des neuen 10.6-Adapters ändert sich die Gültigkeitsdauer des SRA-Zertifikats von 10 Jahren auf 1 Jahr.
.. Remote-Plug-In wird aktualisiert
.. ONTAP und vCenter Server-Zertifikate werden validiert und zu ONTAP -Tools hinzugefügt
.. Sicherung ist aktiviert
.. Falls Hostcluster-Schutzeinstellungen aus ONTAP tools for VMware vSphere 10.5 oder früher vorhanden sind, konvertiert ONTAP tools diese in einen granularen Datenspeicherschutz und erstellt einen separaten Navigationspunkt *Cluster protection configuration*.




.Wie es weiter geht
Nach dem Upgrade auf ONTAP tools für VMware vSphere 10.6:

* Überwachen Sie Systemwarnungen und planen Sie die Erneuerung des Gateway-Zertifikats, bevor es in einem Jahr abläuft.
* Den ONTAP tools 10.4 oder 10.5 SRA Adapter entfernen und die 10.6 SRA Adapter tar-Datei hochladen.
* Führen Sie den Installationsbefehl nach dem Hochladen des SRA-Adapter-Tar-Archivs aus. Scannen Sie anschließend die SRA-Adapter erneut, um die Seite „VMware Site Recovery Storage Replication Adapters“ zu aktualisieren.
* *Cluster-Schutzkonfiguration* öffnen und prüfen, ob die vorhandenen Host-Cluster-Schutzeinstellungen vorhanden und korrekt zugeordnet sind.
* Weitere Informationen zu den Funktionen des granularen Datenspeicherschutzes und zur Eignung sind unter link:../protect/granular-datastore-protection-concept.html["Granulare Kriterien für den Schutz von Datenspeichern in ONTAP Tools"] zu finden.


Nach dem Upgrade können Sie:

* Dienste im ONTAP tools Manager deaktivieren
* Wechseln Sie von einer Einrichtung ohne HA-Konfiguration zu einer HA-Einrichtung
* Skalieren Sie eine kleine Konfiguration ohne HA auf eine mittlere Konfiguration ohne HA oder auf eine mittlere oder große HA-Konfiguration.


.Verwandte Informationen
link:../migrate/migrate-to-latest-ontaptools.html["Migration von ONTAP tools für VMware vSphere 9.x auf 10.6"]
