---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: Upgrade wird sowohl für HA-Implementierungen als auch für Implementierungen ohne HA unterstützt. 
---
= Upgrade von ONTAP tools for VMware vSphere 10.x auf 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können von ONTAP tools for VMware vSphere 10.3 oder 10.4 auf 10.5 aktualisieren.  Um jedoch von ONTAP Tools 10.0, 10.1 oder 10.2 auf 10.5 zu aktualisieren, müssen Sie zuerst auf 10.3 oder 10.4 aktualisieren, bevor Sie mit 10.5 fortfahren.

[NOTE]
====
* Stellen Sie bei ASA R2-Systemen sicher, dass Sie ein Upgrade auf ONTAP tools for VMware vSphere auf 10.5 und ONTAP auf 9.16.1 durchführen, bevor Sie weitere Storage Availability Zones (SAZs) einrichten.
* Wenn das Upgrade von ONTAP tools for VMware vSphere 10.3 oder 10.4 auf 10.5 fehlschlägt, ist ein Rollback nicht möglich. Verwenden Sie ein niedriges RPO oder eine Snapshot-Wiederherstellung, um das Setup wiederherzustellen. Verwenden Sie für ONTAP tools for VMware vSphere 10.2 und früher Zero-RPO, um das Setup wiederherzustellen.


====
.Bevor Sie beginnen
* Stellen Sie sicher, dass das ONTAP -Systemzertifikat und die integrierten vCenter-Zertifikate mindestens 5 Tage gültig sind. Wenn die Zertifikate früher ablaufen, schlägt das Upgrade fehl.
* Um ein sicheres Upgrade zu gewährleisten, überprüfen Sie, ob Ihre Zertifikate Einträge für den Subject Alternative Name (SAN) enthalten. Wenn Zertifikate keine SAN-Einträge enthalten, setzen Sie das Zertifikatvalidierungsflag auf „false“, um SAN-Prüfungen während des Upgrades zu umgehen.
* Stellen Sie sicher, dass Sie auf allen Knoten über eine fünfte Festplatte mit einer Kapazität von 100 GB verfügen.
* Überprüfen Sie, ob die Knotenkonfiguration den Spezifikationen in der folgenden Tabelle entspricht.


|===
| Bereitstellungstyp | CPU (Core) pro Node | Arbeitsspeicher (GB) pro Node | Festplattenspeicher (GB) pro Node | CPU gesamt (Core) | Arbeitsspeicher (GB) | Gesamter Festplattenspeicher (GB) 


| Nicht-HA klein | 9 | 18 | 350 | 9 | 18 | 350 


| Non-HA Medium | 13 | 26 | 350 | 13 | 26 | 350 


| HA klein | 9 | 18 | 350 | 27 | 54 | 1050 


| HA Mittel | 13 | 26 | 350 | 39 | 78 | 1050 


| HA groß | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Stellen Sie sicher, dass das Hot-Plug-in für CPU und RAM aktiviert ist.
* Erstellen Sie für ONTAP tools for VMware vSphere 10.3 oder 10.4 vor dem Upgrade einen stillgelegten Snapshot auf der virtuellen Maschine der ONTAP Tools.
* Aktivieren Sie die Sicherung mit niedrigem RPO und stellen Sie sicher, dass eine Sicherung in der vCenter-Client-Schnittstelle sichtbar ist.


.Schritte
. Laden Sie ONTAP-Tools für VMware vSphere hoch, aktualisieren Sie ISO in die Content Library.
. Wählen Sie auf der primären VM-Seite *actions* > *Edit Settings* aus
. Wählen Sie im Fenster „Einstellungen bearbeiten“ unter dem Feld „CD/DVD-Laufwerk“ die *ISO-Datei der Inhaltsbibliothek* aus.
. Wählen Sie die ISO-Datei aus, aktivieren Sie das Kontrollkästchen *Verbunden* für das Feld *CD/DVD-Laufwerk* und klicken Sie auf *OK*.
. Öffnen Sie im vCenter Server eine Konsole für ONTAP Tools.
. Melden Sie sich als Wartungbenutzer an.
. Geben Sie *2* ein, um das Menü *Systemkonfiguration* auszuwählen.
. Geben Sie *7* ein, um die Option *Upgrade* auszuwählen.
+
Wenn während des Upgrades in integrierten Speicher-Backend-Zertifikaten SAN-Einträge (Subject Alternative Name) fehlen, erhalten Sie eine Meldung mit dem Hinweis auf den fehlenden SAN.  Wenn Sie ohne Validierung des SAN fortfahren, wird das Upgrade fortgesetzt. Dies wird jedoch aufgrund potenzieller Sicherheitsrisiken nicht empfohlen.

. Wenn Sie ein Upgrade durchführen, werden die folgenden Aktionen automatisch ausgeführt:
+
.. Das Gateway-Zertifikat wird mit einer Gültigkeitsdauer von 1 Jahr erneuert.  Wenn Sie den vorherigen SRA-Adapter entfernen und den neuen 10.5-Adapter hochladen, ändert sich die Gültigkeit des SRA-Zertifikats von 10 Jahren auf 1 Jahr.
.. Remote-Plug-In wird aktualisiert
.. ONTAP und vCenter Server-Zertifikate werden validiert und zu ONTAP -Tools hinzugefügt
.. Sicherung ist aktiviert




.Wie es weiter geht
Nach dem Upgrade auf ONTAP tools for VMware vSphere 10.5:

* Überwachen Sie Systemwarnungen und planen Sie die Erneuerung des Gateway-Zertifikats, bevor es in einem Jahr abläuft.
* Entfernen Sie den SRA-Adapter der ONTAP Tools 10.4 oder 10.3 und laden Sie die TAR-Datei des SRA-Adapters 10.5 hoch.  Scannen Sie dann die SRA-Adapter erneut, um die Seite „VMware Site Recovery Storage Replication Adapters“ zu aktualisieren.


Nach dem Upgrade können Sie:

* Deaktivieren Sie die Dienste über die Benutzeroberfläche des Managers
* Wechseln Sie von einer Einrichtung ohne HA-Konfiguration zu einer HA-Einrichtung
* Skalieren Sie eine kleine Konfiguration ohne HA auf eine mittlere Konfiguration ohne HA oder auf eine mittlere oder große HA-Konfiguration.


.Verwandte Informationen
link:../migrate/migrate-to-latest-ontaptools.html["Migrieren Sie von ONTAP tools for VMware vSphere 9.xx auf 10.5"]
