---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: VASA Provider migration, SRA update, VMware Live Site Recovery, ONTAP tools migration, vVols migration, migration jobs, Swagger, REST API 
summary: VASA Provider migrieren und SRA von ONTAP tools 9.x auf 10.6 für VMware Live Site Recovery aktualisieren. 
---
= Migrieren Sie den VASA Provider und aktualisieren Sie die SRA in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dieser Aufgabe wird der VASA Provider von ONTAP tools for VMware vSphere 9.xx auf 10.6 migriert und der Storage Replication Adapter (SRA) auf der VMware Live Site Recovery Appliance aktualisiert.



[[migrate-the-vasa-provider]]
== Migrieren des VASA-Anbieters

.Bevor Sie beginnen
Es muss sichergestellt sein, dass ONTAP tools for VMware vSphere 10.6 bereitgestellt ist und dass der Ziel-vCenter Server sowie die Storage-Backends für die Migration bereit sind.

. Um den Derby-Port 1527 auf der vorhandenen ONTAP tools for VMware vSphere Appliance zu aktivieren, den Root-Benutzer aktivieren, sich über SSH an der CLI anmelden und den folgenden Befehl ausführen:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Die OVA für ONTAP tools for VMware vSphere 10.6 bereitstellen.
. Die vCenter Server-Instanz, die zu ONTAP tools for VMware vSphere 10.6 migriert werden soll, hinzufügen. Weitere Informationen sind unter link:../configure/add-vcenter.html["Fügen Sie eine vCenter Server-Instanz hinzu"] zu finden.
. Das Speicher-Backend kann lokal über die vCenter Server-APIs für das ONTAP tools Plug-in eingebunden werden. Weitere Informationen sind unter link:../configure/add-storage-backend.html["Ein Storage-Backend über die vSphere Client-Schnittstelle hinzufügen"] verfügbar.
. Sie benötigen ein Zugriffstoken, um REST-API-Anfragen zu authentifizieren.  Verwenden Sie das folgende Beispiel und ersetzen Sie die Variablen durch Werte, die für Ihre Umgebung spezifisch sind.
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD", "vcenter hostname": "$MYVCENTER"}'
----
+
Kopieren und speichern Sie das in der Antwort zurückgegebene Zugriffstoken.

. Den folgenden Migrations-API-Aufruf in Swagger oder Postman ausführen.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Sie können über diese URL auf Swagger zugreifen: `\https://$FQDN_IP_PORT/` , Zum Beispiel: `\https://10.67.25.33:8443/` .

+
[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Pfad* 


| POST | /API/v1 
|===
*Verarbeitungsart*

Asynchron

*Beispiel für Curl*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
Request Body für andere Release-Migration:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*JSON-Ausgabebeispiel*

Das System gibt ein Jobobjekt zurück.  Speichern Sie die Auftragskennung, um sie im nächsten Schritt zu verwenden.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====




[[check-migration-status]]
=== Migrationsstatus prüfen

. Verwenden Sie den folgenden URI in Swagger, um den Status zu überprüfen:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
Verwenden Sie den im vorherigen Schritt vom Migrationsauftrag zurückgegebenen Wert 'id'. Überprüfen Sie nach Abschluss des Auftrags den Migrationsbericht in der Auftragsantwort.





[[register-and-verify-the-migrated-vasa-provider]]
=== Den migrierten VASA Provider registrieren und verifizieren

. Registrieren Sie den VASA-Provider mit ONTAP tools for VMware vSphere. Anweisungen finden Sie unterlink:../configure/registration-process.html["Registrieren Sie den VASA Provider"] .
. Überprüfen Sie die VASA Provider-Registrierung:
+
.. Im vSphere Client navigieren Sie zum vCenter Server.
.. Wählen Sie *Configure* > *Storage Providers*.
.. Bestätigen Sie, dass der im vorherigen Schritt registrierte VASA Provider online erscheint.


. Beenden Sie die ONTAP tools for VMware vSphere Storage Provider 9.10/9.11/9.12/9.13 VASA Provider-Dienst mit den folgenden Schritten:
+
.. Öffnen Sie in ONTAP tools 9.x die Webkonsole.
.. Melden Sie sich mit den  `maint` Zugangsdaten an.
.. Eingeben `1` um das Menü *Anwendungskonfiguration* auszuwählen.
.. Eingeben `5` um die VASA Provider- und SRA-Dienste zu stoppen.
.. Im vSphere Client navigieren Sie zum vCenter Server und wählen Sie *Konfigurieren* > *Speicheranbieter*.
.. Wählen Sie den Offline VASA Provider für ONTAP tools 9.x aus und wählen Sie *Entfernen*.
+
Nachdem der alte VASA Provider gestoppt wurde, erfolgt ein Failover des vCenter Servers auf ONTAP tools for VMware vSphere. Alle Datastores und VMs sind zugänglich und werden von ONTAP tools for VMware vSphere bereitgestellt.



. Migrierte NFS und VMFS Datenspeicher erscheinen in ONTAP tools for VMware vSphere 10.6 nach dem Datenspeicher-Erkennungsauftrag, was bis zu 30 Minuten dauern kann. Die Sichtbarkeit dieser Datenspeicher ist auf der Übersichtsseite ersichtlich.




[[run-the-patch-migration]]
=== Die Patch-Migration ausführen

. Den Patch-Migration-API-Aufruf mit Swagger oder Postman ausführen:
+
[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Pfad* 


| PATCH | /API/v1 
|===
*Verarbeitungsart*

Asynchron

Verwenden Sie die folgende URI in Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Pfad* 


| PATCH | /API/v1 
|===
*Verarbeitungsart*

Asynchron

Verwenden Sie die folgende URI in Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Beispiel für Curl*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*JSON-Ausgabebeispiel*

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: Verwenden Sie den in Schritt 7 zurückgegebenen Wert 'migration_id' als <migration_id> im PATCH-API-Aufruf. Der Anfragetext ist für die Patch-Operation leer.

+

NOTE: UUID ist die Migrations-UUID, die als Antwort auf die API nach der Migration zurückgegeben wird.



Nach Ausführung der Patch-Migrations-API halten alle VMs die Storage-Richtlinie ein.



[[after-migration]]
== Nach der Migration

Nach Abschluss der Migration und Registrierung von ONTAP tools 10.6 beim vCenter Server sind die folgenden Schritte zu beachten:

* Warten Sie, bis die *Erkennung* abgeschlossen ist. Das System aktualisiert die Zertifikate auf allen Hosts automatisch.
* Warten Sie, bevor Sie mit dem Starten von Datenspeicher- und virtuellen Maschinenvorgängen beginnen.  Die Wartezeit hängt von der Anzahl der Hosts, Datenspeicher und virtuellen Maschinen ab.  Wenn Sie nicht warten, kann es gelegentlich zu Fehlern kommen.


Wenn der Compliance-Zustand der virtuellen Maschine nach dem Upgrade veraltet ist, wenden Sie die Speicherrichtlinie erneut an, indem Sie die folgenden Schritte ausführen:

. Gehen Sie zum Datenspeicher und wählen Sie *Zusammenfassung* > *VM-Speicherrichtlinien*.
. Das System zeigt den Compliance-Status unter *VM-Speicherrichtlinien-Compliance* als *Veraltet* an.
. Wählen Sie die Storage-VM-Richtlinie und die entsprechende VM aus.
. Wählen Sie *Übernehmen*.
. Der Konformitätsstatus unter *VM-Speicherrichtlinienkonformität* wird als konform angezeigt.


.Verwandte Informationen
* link:../concepts/rbac-learn-about.html["Erfahren Sie mehr über ONTAP Tools für die rollenbasierte Zugriffssteuerung von VMware vSphere 10"]
* link:../upgrade/upgrade-ontap-tools.html["Upgrade von ONTAP tools für VMware vSphere 10.x auf 10.6"]




[[update-the-storage-replication-adapter-sra]]
== Den Speicherreplikationsadapter (SRA) aktualisieren

.Bevor Sie beginnen
Vor der Migration der SRA ist Folgendes zu überprüfen:

* Im Wiederherstellungsplan ist der geschützte Standort der Ort, an dem die VMs aktuell ausgeführt werden, und der Wiederherstellungsstandort ist der Ort, an dem die VMs wiederhergestellt werden.
* In der Benutzeroberfläche der VMware Live Site Recovery Appliance erscheint ein Standort im geschützten Zustand und der andere Standort im Wiederherstellungszustand.
* Im Wiederherstellungsplan sind die Schaltflächen *BEREINIGEN* und *RÜCKSCHUTZ* deaktiviert, und die Schaltflächen *TESTEN* und *AUSFÜHREN* bleiben aktiviert.



NOTE: Beginnen Sie die Migration nicht, wenn das Failover abgeschlossen ist, die Re-Protect-Funktion aber noch aussteht. Stellen Sie sicher, dass der Re-Protect-Vorgang abgeschlossen ist, bevor Sie mit der Migration fortfahren. Wenn ein Test-Failover läuft, bereinigen Sie das Test-Failover und starten Sie die Migration.

. Führen Sie diese Schritte aus, um den SRA-Adapter für ONTAP-Tools für VMware vSphere 9.xx in der VMware-Standortwiederherstellung zu löschen:
. Wechseln Sie zur Konfigurationsverwaltungsseite von VMware Live Site Recovery.
+
.. Gehen Sie zum Abschnitt *Storage Replication Adapter*.
.. Wählen Sie im Auslassungsmenü *Konfiguration zurücksetzen*.
.. Wählen Sie im Auslassungsmenü *Löschen*.


. Führen Sie diese Schritte sowohl an Sicherungs- als auch an Recovery-Standorten aus.
+
.. link:../manage/enable-services.html["Aktivieren Sie ONTAP-Tools für VMware vSphere-Services"]
.. ONTAP tools für VMware vSphere 10.6 SRA Adapter werden mithilfe der Schritte in link:../protect/configure-on-srm-appliance.html["Konfigurieren Sie SRA auf der VMware Live Site Recovery-Appliance"] konfiguriert.
.. Führen Sie auf der VMware Live Site Recovery-Schnittstelle *Discover Arrays* und *Discover Devices* aus.  Bestätigen Sie, dass die Geräte wie vor der Migration angezeigt werden.



