---
permalink: deploy/deployment-error-codes.html 
sidebar: sidebar 
keywords: troubleshooting deployment errors, log bundles, error codes, ONTAP tools 
summary: ONTAP tools Bereitstellungsfehlercodes dienen zur Diagnose und Behebung von Fehlern bei Bereitstellung, Neustart und Wiederherstellung. 
---
= Fehlercodes bei der Bereitstellung von ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Bereitstellungsprobleme auftreten, werden die Protokolle und Fehlercodes zur Diagnose und Behebung der Probleme überprüft. Ab ONTAP tools for VMware vSphere 10.6 enthalten die von den Pods gesammelten Protokollpakete Protokolle von MongoDB, RabbitMQ und Vault sowie den Status und die Beschreibungen aller Pods. ONTAP tools 10.6 bietet außerdem eine Audit-Protokollierung zur Verbesserung der Nachverfolgbarkeit bei der Fehlerbehebung. Diese werden zusätzlich zu den bestehenden ONTAP tools Serviceprotokollen bereitgestellt und verbessern die Supportfähigkeit und Fehlerbehebung.



[[collect-the-log-files]]
== Sammeln Sie die Protokolldateien

Sie können Protokolldateien für ONTAP tools for VMware vSphere über die Optionen in der ONTAP tools Manager-Benutzeroberfläche erfassen. Der technische Support kann Sie bitten, die Protokolldateien zur Fehlerbehebung zu sammeln.


NOTE: Die Protokollgenerierung über den ONTAP tools Manager umfasst alle Protokolle aller vCenter Serverinstanzen. Die Protokollgenerierung über die vCenter Client-Benutzeroberfläche ist auf den ausgewählten vCenter Server beschränkt.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Log Bundles* aus.
+
Dieser Vorgang kann mehrere Minuten dauern.

. Wählen Sie *Generate*, um die Protokolldateien zu generieren.
. Geben Sie die Bezeichnung für das Log Bundle ein und wählen Sie *Generate*.
+
Laden Sie die Datei tar.gz herunter, und senden Sie sie an den technischen Support.



Führen Sie die folgenden Schritte aus, um Protokollbündel über die vCenter Client-Benutzeroberfläche zu generieren:

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Gehen Sie auf der vSphere Client-Homepage zu *Support* > *Log Bundle* > *Generate*.
. Geben Sie die Bezeichnung des Protokollpakets an und generieren Sie das Protokollpaket. Die Download-Option wird angezeigt, wenn die Dateien generiert werden. Der Download kann einige Zeit dauern.



NOTE: Das erzeugte Log-Bundle ersetzt das Log-Bundle, das innerhalb der letzten 3 Tage oder 72 Stunden erzeugt wurde.



[[deployment-error-codes]]
== Fehlercodes für die Bereitstellung

Während der Bereitstellung, des Neustarts und der Wiederherstellungsvorgänge von ONTAP-Tools für VMware vSphere können Fehlercodes auftreten.
Die Fehlercodes sind fünf Ziffern lang, wobei die ersten beiden Ziffern das Skript darstellen, das auf das Problem gestoßen ist, und die letzten drei Ziffern den spezifischen Workflow innerhalb dieses Skripts darstellen.

Alle Fehlerprotokolle werden in der Datei ansible-perl-errors.log im Verzeichnis /var/log/otvng gespeichert, um die Nachverfolgung und Behebung von Problemen zu erleichtern. Diese Protokolldatei enthält den Fehlercode und die fehlgeschlagene Ansible Aufgabe.


NOTE: Die auf dieser Seite angegebenen Fehlercodes dienen nur als Referenz. Wenden Sie sich an das Support-Team, falls der Fehler weiterhin besteht oder keine Lösung genannt wird.

In der folgenden Tabelle sind die Fehlercodes und die entsprechenden Dateinamen aufgeführt.

|===


| *Fehlercode* | *Skriptname* 


| 00 | firstboot-network-config.pl, Mode Deployment 


| 01 | firstboot-network-config.pl, Modusaktualisierung 


| 02 | firstboot-inputs-validation.pl 


| 03 | firstboot-deploy-otv-ng.pl, Deploy, HA 


| 04 | firstboot-deploy-otv-ng.pl, Deploy, non-HA 


| 05 | firstboot-deploy-otv-ng.pl, Neustart 


| 06 | firstboot-deploy-otv-ng.pl, Upgrade, HA 


| 07 | firstboot-deploy-otv-ng.pl, Upgrade, nicht HA 


| 08 | firstboot-otv-recovery.pl 


| 09 | post-deploy-upgrade.pl 
|===
Die letzten drei Ziffern des Fehlercodes zeigen den spezifischen Workflow-Fehler im Skript an:

|===


| *Deployment-Fehlercode* | *Arbeitsablauf* | * Auflösung* 


| 049 | Für Netzwerk und Validierung wird Perl Skript sie auch in Kürze zuweisen | - 


| 050 | SSH-Schlüsselgenerierung fehlgeschlagen | Starten Sie die primäre virtuelle Maschine (VM) neu. 


| 053 | Fehler bei der Installation von RKE2 | Führen Sie entweder Folgendes aus und starten Sie die primäre VM neu, oder starten Sie Neuimplementierung:
Sudo rke2-killall.sh (alle VMs)
Sudo rke2-uninstall.sh (alle VMs). 


| 054 | Einstellung von kubeconfig fehlgeschlagen | Neuimplementierung 


| 055 | Fehler beim Bereitstellen der Registrierung | Wenn der Registry-Pod vorhanden ist, warten Sie, bis der Pod bereit ist, und starten Sie dann die primäre VM neu oder stellen Sie sie erneut bereit. 


| 059 | Die KubeVip-Bereitstellung ist fehlgeschlagen | Stellen Sie sicher, dass die virtuelle IP-Adresse für die Kubernetes-Steuerungsebene und die während der Bereitstellung angegebene ONTAP tools IP-Adresse zum selben VLAN gehören und freie IP-Adressen sind. Starten Sie neu, wenn alle vorherigen Punkte korrekt sind. Andernfalls führen Sie eine erneute Bereitstellung durch. 


| 060 | Die Benutzerbereitstellung ist fehlgeschlagen | Neu Starten 


| 061 | Die Bereitstellung der Dienste ist fehlgeschlagen | Grundlegendes Kubernetes-Debugging wie get pods, get rs, get svc usw. im ntv-system Namespace liefert weitere Details und Fehlerprotokolle unter /var/log/otvng/ansible-perl-errors.log und /var/log/otvng/ansible-run.log; anschließend kann eine erneute Bereitstellung erfolgen. 


| 062 | Die Bereitstellung der ONTAP Tools Services ist fehlgeschlagen | Weitere Details stehen in den Fehlerprotokollen unter /var/log/otvng/ansible-perl-errors.log und eine erneute Bereitstellung ist erforderlich. 


| 065 | Die URL der Swagger-Seite ist nicht erreichbar | Neuimplementierung 


| 066 | Fehler bei den Schritten nach der Bereitstellung für das Gateway-Zertifikat  a| 
Führen Sie folgende Schritte aus, um das Upgrade wiederherzustellen/abzuschließen:

* Diagnose-Shell aktivieren.
* Führen Sie den Befehl 'sudo perl /home/maint/scripts/post-deploy-upgrade.pl --postDeploy' aus.
* Die Protokolle unter /var/log/otvng/post-deploy-upgrade.log prüfen.




| 088 | Die Konfiguration der Protokollrotation für journald ist fehlgeschlagen | Überprüfen Sie die VM-Netzwerkeinstellungen, die mit dem Host kompatibel sind, auf dem die VM gehostet wird. Sie können versuchen, auf einen anderen Host zu migrieren und die VM neu zu starten. 


| 089 | Ändern der Eigentumsrechte für die Konfigurationsdatei „Zusammenfassung Protokoll drehen“ ist fehlgeschlagen | Starten Sie die primäre VM neu. 


| 096 | Installieren Sie die dynamische Storage-provisionierung | - 


| 108 | Das Seeding des Skripts ist fehlgeschlagen | - 
|===
|===


| *Fehlercode für Neustart* | *Arbeitsablauf* | * Auflösung* 


| 067 | Zeitüberschreitung beim Warten auf Rke2-Server. | - 


| 101 | Fehler beim Zurücksetzen des Benutzerpassworts für Wartung/Konsole. | - 


| 102 | Fehler beim Löschen der Kennwortdatei beim Zurücksetzen des Benutzerpassworts für Wartung/Konsole. | - 


| 103 | Fehler beim Aktualisieren des neuen Benutzerpassworts für Wartung/Konsole im Tresor. | - 


| 088 | Die Konfiguration der Protokollrotation für journald ist fehlgeschlagen. | Überprüfen Sie die VM-Netzwerkeinstellungen, die mit dem Host kompatibel sind, auf dem die VM gehostet wird. Sie können versuchen, auf einen anderen Host zu migrieren und die VM neu zu starten. 


| 089 | Ändern der Eigentumsrechte für die Konfigurationsdatei „Zusammenfassung Protokoll drehen“ ist fehlgeschlagen. | Starten Sie den VM neu. 
|===