---
permalink: deploy/deployment-error-codes.html 
sidebar: sidebar 
keywords: upgrade 
summary: Auf dieser Seite werden die Fehlercodes für die Bereitstellung, den Neustart und die Wiederherstellungsvorgänge von ONTAP-Tools für das VMware vSphere-System erläutert. 
---
= Beheben von Bereitstellungsfehlern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn bei der Bereitstellung Probleme auftreten, überprüfen Sie die Protokolle und Fehlercodes, um die Probleme zu diagnostizieren und zu beheben.  Ab ONTAP tools for VMware vSphere 10.5 umfassen die von den Pods gesammelten Protokollpakete Protokolle von MongoDB, RabbitMQ und Vault sowie den Status und die Beschreibungen aller Pods.  Diese werden zusätzlich zu den vorhandenen Serviceprotokollen der ONTAP Tools bereitgestellt und verbessern die Supportfähigkeit und Fehlerbehebung.



== Sammeln Sie die Protokolldateien

Sie können Protokolldateien für ONTAP-Tools für VMware vSphere über die in der Benutzeroberfläche von ONTAP Tools Manager verfügbaren Optionen sammeln. Der technische Support fordert Sie möglicherweise auf, die Protokolldateien zu sammeln, damit Sie Probleme beheben können.


NOTE: Die Generierung von Protokollen über den ONTAP-Tools-Manager umfasst alle Protokolle für alle vCenter-Serverinstanzen. Die Generierung von Protokollen über die vCenter-Client-Benutzeroberfläche ist für den ausgewählten vCenter-Server vorgesehen.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Log Bundles* aus.
+
Dieser Vorgang kann mehrere Minuten dauern.

. Wählen Sie *Generate*, um die Protokolldateien zu generieren.
. Geben Sie die Bezeichnung für das Log Bundle ein und wählen Sie *Generate*.
+
Laden Sie die Datei tar.gz herunter, und senden Sie sie an den technischen Support.



Führen Sie die folgenden Schritte aus, um Protokollbündel über die vCenter Client-Benutzeroberfläche zu generieren:

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Gehen Sie auf der vSphere Client-Homepage zu *Support* > *Log Bundle* > *Generate*.
. Geben Sie die Bezeichnung des Protokollpakets an und generieren Sie das Protokollpaket. Die Download-Option wird angezeigt, wenn die Dateien generiert werden. Der Download kann einige Zeit dauern.



NOTE: Das erzeugte Log-Bundle ersetzt das Log-Bundle, das innerhalb der letzten 3 Tage oder 72 Stunden erzeugt wurde.



== Fehlercodes für die Bereitstellung

Während der Bereitstellung, des Neustarts und der Wiederherstellungsvorgänge von ONTAP-Tools für VMware vSphere können Fehlercodes auftreten.
Die Fehlercodes sind fünf Ziffern lang, wobei die ersten beiden Ziffern das Skript darstellen, das auf das Problem gestoßen ist, und die letzten drei Ziffern den spezifischen Workflow innerhalb dieses Skripts darstellen.

Alle Fehlerprotokolle werden in der Datei ansible-perl-errors.log im Verzeichnis /var/log aufgezeichnet, um die einfache Verfolgung und Lösung von Problemen zu ermöglichen.  Diese Protokolldatei enthält den Fehlercode und die fehlgeschlagene Ansible-Aufgabe.


NOTE: Die auf dieser Seite angegebenen Fehlercodes dienen nur als Referenz. Wenden Sie sich an das Support-Team, wenn der Fehler weiterhin besteht oder wenn keine Lösung erwähnt wird.

In der folgenden Tabelle sind die Fehlercodes und die entsprechenden Dateinamen aufgeführt.

|===


| *Fehlercode* | *Skriptname* 


| 00 | firstboot-network-config.pl, Mode Deployment 


| 01 | firstboot-network-config.pl, Modusaktualisierung 


| 02 | firstboot-inputs-validation.pl 


| 03 | firstboot-deploy-otv-ng.pl, Deploy, HA 


| 04 | firstboot-deploy-otv-ng.pl, Deploy, non-HA 


| 05 | firstboot-deploy-otv-ng.pl, Neustart 


| 06 | firstboot-deploy-otv-ng.pl, Upgrade, HA 


| 07 | firstboot-deploy-otv-ng.pl, Upgrade, nicht HA 


| 08 | firstboot-otv-recovery.pl 


| 09 | post-deploy-upgrade.pl 
|===
Die letzten drei Ziffern des Fehlercodes zeigen den spezifischen Workflow-Fehler im Skript an:

|===


| *Deployment-Fehlercode* | *Arbeitsablauf* | * Auflösung* 


| 049 | Für Netzwerk und Validierung wird Perl Skript sie auch in Kürze zuweisen | - 


| 050 | Generierung des SSH-Schlüssels fehlgeschlagen | Starten Sie die primäre virtuelle Maschine (VM) neu. 


| 053 | RKE2 konnte nicht installiert werden | Führen Sie entweder Folgendes aus und starten Sie die primäre VM neu, oder starten Sie Neuimplementierung:
Sudo rke2-killall.sh (alle VMs)
Sudo rke2-uninstall.sh (alle VMs). 


| 054 | Einstellung von kubeconfig fehlgeschlagen | Neuimplementierung 


| 055 | Fehler beim Bereitstellen der Registrierung | Wenn der Registrierungs-Pod vorhanden ist, warten Sie, bis der Pod bereit ist, starten Sie dann die primäre VM neu oder starten Sie es andernfalls neu. 


| 059 | Die KubeVip-Bereitstellung ist fehlgeschlagen | Vergewissern Sie sich, dass die während der Implementierung angegebene virtuelle IP-Adresse für die Kubernetes-Kontrollebene und die ONTAP-Tools die IP-Adresse im selben VLAN und freien IP-Adressen sind. Neu starten, wenn alle vorherigen Punkte korrekt sind. Ansonsten Neuimplementierung. 


| 060 | Die Benutzerbereitstellung ist fehlgeschlagen | Neu Starten 


| 061 | Die Bereitstellung der Dienste ist fehlgeschlagen | Führen Sie einfache Kubernetes-Fehlerbehebungen wie get Pods, get rs, get svc usw. im ntv-System-Namespace durch, um weitere Details und Fehlerprotokolle unter /var/log/ansible-perl-errors.log und /var/log/ansible-run.log zu erhalten und Neuimplementierungen durchzuführen. 


| 062 | Die Bereitstellung der ONTAP Tools Services ist fehlgeschlagen | Weitere Informationen und Neuimplementierungen finden Sie in den Fehlerprotokollen unter /var/log/ansible-perl-errors.log. 


| 065 | Die URL der Swagger-Seite ist nicht erreichbar | Neuimplementierung 


| 066 | Fehler bei den Schritten nach der Bereitstellung für das Gateway-Zertifikat | Gehen Sie wie folgt vor, um das Upgrade wiederherzustellen/abzuschließen: * Diagnostic Shell aktivieren. * Führen Sie den Befehl 'sudo perl /Home/maint/scripts/post-deploy-upgrade.pl --postDeploy' aus. * Überprüfen Sie die Protokolle unter /var/log/post-deploy-Upgrade.log. 


| 088 | Die Konfiguration der Protokollrotation für journald ist fehlgeschlagen | Überprüfen Sie die VM-Netzwerkeinstellungen, die mit dem Host kompatibel sind, auf dem die VM gehostet wird. Sie können versuchen, auf einen anderen Host zu migrieren und die VM neu zu starten. 


| 089 | Ändern der Eigentumsrechte für die Konfigurationsdatei „Zusammenfassung Protokoll drehen“ ist fehlgeschlagen | Starten Sie die primäre VM neu. 


| 096 | Installieren Sie die dynamische Storage-provisionierung | - 


| 108 | Das Seeding des Skripts ist fehlgeschlagen | - 
|===
|===


| *Fehlercode für Neustart* | *Arbeitsablauf* | * Auflösung* 


| 067 | Zeitüberschreitung beim Warten auf Rke2-Server. | - 


| 101 | Fehler beim Zurücksetzen des Benutzerpassworts für Wartung/Konsole. | - 


| 102 | Fehler beim Löschen der Kennwortdatei beim Zurücksetzen des Benutzerpassworts für Wartung/Konsole. | - 


| 103 | Fehler beim Aktualisieren des neuen Benutzerpassworts für Wartung/Konsole im Tresor. | - 


| 088 | Die Konfiguration der Protokollrotation für journald ist fehlgeschlagen. | Überprüfen Sie die VM-Netzwerkeinstellungen, die mit dem Host kompatibel sind, auf dem die VM gehostet wird. Sie können versuchen, auf einen anderen Host zu migrieren und die VM neu zu starten. 


| 089 | Ändern der Eigentumsrechte für die Konfigurationsdatei „Zusammenfassung Protokoll drehen“ ist fehlgeschlagen. | Starten Sie den VM neu. 
|===