---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: Sie können HA s in kleinen, mittleren oder großen Konfigurationen konfigurieren. 
---
= Implementierung der HA-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können HA für drei Nodes in kleinen, mittleren oder großen Konfigurationen konfigurieren. Für die HA-Implementierung werden die Servicedaten mithilfe von Trident gespeichert.

* Kleine HA, drei Nodes, enthalten 8 CPUs und 16 GB RAM pro Node.
* Mittlere HA, drei Nodes enthalten 12 CPUs und 24 GB RAM pro Node.
* Große HA, drei Nodes enthalten 16 CPUs und 32 GB RAM pro Node.


*Bevor Sie beginnen*

Diese Aufgabe enthält Anweisungen zum Installieren von HA Three Nodes in kleinen, mittleren oder hohen Konfigurationen.


NOTE: Das Erstellen der Content Library ist ein obligatorischer Schritt für die Bereitstellung der HA-Konfiguration mit drei Nodes. link:../deploy/download-ontap-tools.html["Erstellen Sie eine Inhaltsbibliothek"]Das Verfahren finden Sie im Abschnitt. Weitere Informationen finden Sie im https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Erstellen und Verwenden der Inhaltsbibliothek"] Blog.

Stellen Sie sicher, dass Sie Ihre OVA in Ihre Inhaltsbibliothek importiert haben. Halten Sie den Namen der Inhaltsbibliothek und den Namen des Bibliothekselements, den Sie für Ihr OVA-Element angegeben haben, griffbereit.


NOTE: Bevor Sie mit der Bereitstellung fortfahren, setzen Sie den Distributed Resource Scheduler (DRS) des Clusters im Inventar während der Installation von ONTAP-Tools auf „konservativ“. Dadurch wird sichergestellt, dass VMs während der Installation nicht migriert werden.

*Schritte*

. Melden Sie sich beim vSphere-Server an.
. Navigieren Sie zum Ressourcenpool, den Sie erstellt haben, oder zum Cluster oder zum Host, auf dem Sie die OVA bereitstellen möchten.
. Klicken Sie mit der rechten Maustaste auf den gewünschten Speicherort und wählen Sie *OVF-Vorlage bereitstellen...*.
+

NOTE: Implementieren Sie keine ONTAP-Tools für die virtuelle VMware vSphere-Maschine auf einem von ihr gemanagten VVols-Datastore.

. Wählen Sie die OVA-Datei entweder über die URL für die _.ova_-Datei aus, oder navigieren Sie zu dem Ordner, in dem die _.ova_-Datei gespeichert ist, und klicken Sie dann auf *Weiter*.
. So implementieren Sie ONTAP-Tools für VMware vSphere aus der Content Library:
+
.. Öffnen Sie Ihre Inhaltsbibliothek, und klicken Sie auf das Bibliothekselement, das Sie bereitstellen möchten.
.. Klicken Sie auf *actions* > *New VM aus dieser Vorlage*


. Wählen Sie eine Computerressource aus und klicken Sie auf *Weiter*.
. Überprüfen Sie die Details der Vorlage und klicken Sie auf *Weiter*.
. Lesen und akzeptieren Sie die Lizenzvereinbarung und klicken Sie auf *Weiter*.
. Wählen Sie die Bereitstellungskonfiguration aus und klicken Sie auf *Weiter*.
. Wählen Sie den Speicher für die Konfiguration und die Festplattendateien aus und klicken Sie auf *Weiter*.
. Wählen Sie das Zielnetzwerk für jedes Quellnetzwerk aus und klicken Sie auf *Weiter*.
. Füllen Sie im Fenster *Vorlage anpassen* die erforderlichen Felder aus und klicken Sie auf *Weiter*.
+
** Wenn der SVM-Bereich aktiviert ist, sollte die SVM-Unterstützung mit der Management-IP-Adresse bereits aktiviert sein.
** Die hier bereitgestellten Informationen werden während des Installationsprozesses auf korrekte Muster überprüft. Im Falle einer Abweichung wird eine Fehlermeldung auf der Webkonsole angezeigt, und Sie werden aufgefordert, falsche Informationen zu korrigieren.
** Host-Namen müssen aus Groß-/Kleinbuchstaben (A–Z), Ziffern (0–9) oder dem Bindestrich (-) bestehen. Wenn Sie Dual-Stack konfigurieren möchten, geben Sie den Hostnamen an, der der IPv6-Adresse zugeordnet ist.


. Überprüfen Sie die Details im Fenster *Ready to Complete*, wählen Sie *Finish*.
+
Wenn die Bereitstellungsaufgabe erstellt wird, wird der Fortschritt in der vSphere-Taskleiste angezeigt.

. Schalten Sie die VM nach Abschluss der Aufgabe ein.
+
Die Installation beginnt. Sie können den Installationsfortschritt in der Web-Konsole der VM verfolgen. Im Rahmen der Installation werden Node-Konfigurationen validiert. Die Eingaben, die unter verschiedenen Abschnitten unter der Vorlage „Anpassen“ im OVF-Formular bereitgestellt werden, werden validiert. Bei Unstimmigkeiten werden Sie in einem Dialogfeld aufgefordert, Korrekturmaßnahmen zu ergreifen.

. Nehmen Sie die erforderlichen Änderungen in der Dialogaufforderung vor. Verwenden Sie die Tabulatortaste, um durch das Bedienfeld zu navigieren, und wählen Sie *OK*.
+
Die angegebenen Werte werden erneut validiert. Mit den ONTAP-Tools für VMware vSphere können Sie drei Versuche durchführen, ungültige Werte zu korrigieren. Wenn Sie Probleme nach drei Versuchen nicht beheben können, wird die Produktinstallation angehalten, und Sie werden aufgefordert, die Installation auf einer neuen VM zu versuchen.



Nach der erfolgreichen Installation zeigt die Webkonsole den Status der ONTAP Tools für VMware vSphere an.
