---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: Sie können in kleinen oder mittleren Konfigurationen einen Single Node ohne HA konfigurieren. 
---
= Implementierung einer Single Node-Konfiguration ohne Hochverfügbarkeit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Single Node-Konfiguration ohne HA in einer kleinen oder mittelgroßen Konfiguration implementieren.

* Die kleine Konfiguration ohne HA umfasst 8 CPUs und 16 GB RAM.
* Mittelgroße Konfiguration ohne HA enthält 12 CPUs und 24 GB RAM.


*Bevor Sie beginnen*

Stellen Sie sicher, dass die Netzwerkroute vorhanden ist. Auf das Storage-Datennetzwerk muss über das VM-Managementnetzwerk zugegriffen werden können. Melden Sie sich beispielsweise bei ONTAP an > führen Sie den Befehl _Network Route create -vserver <SVM> -Destination 0.0.0.0/0 -Gateway <gateway_ip>_ aus

*Schritte*

. Melden Sie sich beim vSphere-Server an.
. Navigieren Sie zum Ressourcenpool, den Sie erstellt haben, oder zum Cluster oder zum Host, auf dem Sie die OVA bereitstellen möchten.
. Klicken Sie mit der rechten Maustaste auf den gewünschten Speicherort und wählen Sie *OVF-Vorlage bereitstellen...*.
+

NOTE: Implementieren Sie keine ONTAP-Tools für die virtuelle VMware vSphere-Maschine auf einem von ihr gemanagten VVols-Datastore.

. Wählen Sie die OVA-Datei entweder über die URL für die _.ova_-Datei aus, oder navigieren Sie zu dem Ordner, in dem die _.ova_-Datei gespeichert ist, und klicken Sie dann auf *Weiter*.
. Wählen Sie eine Computerressource aus und klicken Sie auf *Weiter*.
. Überprüfen Sie die Details der Vorlage und klicken Sie auf *Weiter*.
. Lesen und akzeptieren Sie die Lizenzvereinbarung.
. Wählen Sie die Bereitstellungskonfiguration aus und klicken Sie auf *Weiter*.
+
Bei den erweiterten Implementierungsoptionen kommt Trident zur dynamischen Storage-bereitstellung für ONTAP zum Erstellen von Volumes zum Einsatz. Bei der einfachen Implementierung werden lokale Storage-Ressourcen zur Erstellung von Volumes verwendet.

. Wählen Sie den Speicher für die Konfiguration und die Festplattendateien aus und klicken Sie auf *Weiter*.
. Wählen Sie das Zielnetzwerk für jedes Quellnetzwerk aus und klicken Sie auf *Weiter*.
. Geben Sie in der *Customize Vorlage* die erforderlichen Details ein und klicken Sie auf *Weiter*
+
** Wenn der SVM-Bereich aktiviert ist, sollte die SVM-Unterstützung mit der Management-IP-Adresse bereits aktiviert sein.
** Die hier bereitgestellten Informationen werden während des Installationsprozesses auf korrekte Muster überprüft. Im Falle einer Abweichung wird eine Fehlermeldung auf der Webkonsole angezeigt, und Sie werden aufgefordert, falsche Informationen zu korrigieren.
** Host-Namen müssen aus Groß-/Kleinbuchstaben (A–Z), Ziffern (0–9) oder dem Bindestrich (-) bestehen. Wenn Sie Dual-Stack konfigurieren möchten, geben Sie den Hostnamen an, der der IPv6-Adresse zugeordnet ist.


. Überprüfen Sie die Details im Fenster *Ready to Complete*, wählen Sie *Finish*.
+
Wenn die Bereitstellungsaufgabe erstellt wird, wird der Fortschritt in der vSphere-Taskleiste angezeigt.

. Schalten Sie die VM nach Abschluss der Aufgabe ein.
+
Die Installation beginnt. Sie können den Installationsfortschritt in der Web-Konsole der VM verfolgen. Im Rahmen der Installation werden Node-Konfigurationen validiert. Die Eingaben, die unter verschiedenen Abschnitten unter der Vorlage „Anpassen“ im OVF-Formular bereitgestellt werden, werden validiert. Bei Unstimmigkeiten werden Sie in einem Dialogfeld aufgefordert, Korrekturmaßnahmen zu ergreifen.

. Nehmen Sie die erforderlichen Änderungen in der Dialogaufforderung vor. Verwenden Sie die Tabulatortaste, um durch das Bedienfeld zu navigieren, und wählen Sie *OK*.
+
Die angegebenen Werte werden erneut validiert. Mit den ONTAP-Tools für VMware vSphere können Sie drei Versuche durchführen, ungültige Werte zu korrigieren. Wenn Sie Probleme nach drei Versuchen nicht beheben können, wird die Produktinstallation angehalten, und Sie werden aufgefordert, die Installation auf einer neuen VM zu versuchen.



Nach der erfolgreichen Installation zeigt die Webkonsole den Status der ONTAP Tools für VMware vSphere an.
