---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools requirements, configuration limits, supported versions, sizing 
summary: Vor der Bereitstellung von ONTAP tools für VMware vSphere werden die unterstützten Versionen, die Dimensionierung, die Portanforderungen und die Konfigurationsgrenzen geprüft. 
---
= ONTAP-Tools für VMware vSphere – Anforderungen und Konfigurationsgrenzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Bereitstellung von ONTAP tools für VMware vSphere werden die unterstützten Versionen, die Dimensionierung, die Portanforderungen und die Konfigurationsgrenzen geprüft.

ONTAP tools für VMware vSphere in einer unterstützten vSphere Umgebung bereitstellen, die ESXi Hosts und VMware vCenter Server Virtual Appliance (vCSA) umfasst.



[[system-requirements]]
== Systemanforderungen

* *Platzanforderungen für Installationspaket pro Knoten*
+
** 15 GB bei Thin Provisioning-Installationen
** 348 GB für Thick Provisioning-Installationen


* *Anforderungen an die Dimensionierung des Hostsystems* Die folgende Tabelle zeigt die empfohlenen Werte für CPU, Arbeitsspeicher und Festplattenspeicher pro Knoten für jede Bereitstellungsgröße. Für Hochverfügbarkeit (HA) sollten drei Knoten bereitgestellt werden.


|===


| *Art der Bereitstellung* | *CPUs pro Knoten* | *Arbeitsspeicher (GB) pro Node* | *Speicherplatz (GB) Thick Provisioning pro Knoten* 


| Extra klein (XS) | 6 | 12 | 350 


| Klein | 9 | 18 | 350 


| Mittel | 13 | 26 | 350 


| Groß | 17 | 34 | 350 
|===

NOTE: Große Bereitstellungsgrößen werden nur für HA Konfigurationen unterstützt.


NOTE: Wenn die Datensicherung aktiviert ist, benötigt jeder ONTAP tools Cluster zusätzlich 50 GB Speicherplatz auf dem Datenspeicher, auf dem die VMs bereitgestellt sind. Daher sind für Non-HA insgesamt 400 GB und für HA insgesamt 1100 GB Speicherplatz erforderlich.



[[minimum-storage-and-application-requirements]]
== Mindestanforderungen hinsichtlich Storage und Applikationen

|===
| Storage, Host und Applikationen | Versionsanforderungen 


| ONTAP-Systeme | 9.16.1, 9.17.1, 9.18.1, 9.19.1 


| ESXi Hosts, die von ONTAP tools verwaltet werden | Ab 7.0.3 


| vCenter Server-Instanzen, die von ONTAP tools verwaltet werden | 8.0U3 und höher 


| VASA Provider | 3.0 


| OVA-Anwendung | 10,6 


| ESXi-Host, der zum Bereitstellen der ONTAP tools virtuellen Maschine verwendet wird | 7.0U3 und 8.0U3 


| vCenter Server, der zum Bereitstellen der ONTAP tools virtuellen Maschine verwendet wird | 7.0 und 8.0 
|===

NOTE: Ab ONTAP tools for VMware vSphere 10.4 ändert sich die Hardwareversion der virtuellen Maschine von 10 auf 17.

Das Interoperabilitäts-Matrix-Tool (IMT) enthält aktuelle Informationen zu den unterstützten Versionen von ONTAP, vCenter Server, ESXi-Hosts und Plug-in-Applikationen.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool"^]



[[port-requirements]]
== Port-Anforderungen

Die folgende Tabelle zeigt die von NetApp verwendeten Netzwerkports und deren Zweck. Es gibt drei verschiedene Arten von Anschlüssen:

* Externe Ports: Diese Ports sind von außerhalb des Kubernetes-Clusters oder -Knotens zugänglich. Sie ermöglichen es Diensten, mit externen Netzwerken oder Benutzern zu kommunizieren und so die Integration mit Systemen außerhalb der Clusterumgebung zu ermöglichen.
* Inter-node-Ports: Diese Ports ermöglichen die Kommunikation zwischen Knoten innerhalb des Kubernetes-Clusters. Sie sind für Cluster-Operationen wie Datenaustausch und Knotenkoordination erforderlich. Bei Einzelknoten-Bereitstellungen werden Inter-node-Ports nur innerhalb des Knotens verwendet und benötigen keinen externen Zugriff. Inter-node-Datenverkehr sollte nur aus vertrauenswürdigen Clusternetzwerken zugelassen und der Internetzugriff durch Firewall-Regeln blockiert werden.
* Interne Ports: Diese Ports kommunizieren innerhalb des Kubernetes-Clusters über ClusterIP-Adressen. Sie sind nicht extern zugänglich und müssen nicht zu Firewall-Regeln hinzugefügt werden.



NOTE: Stellen Sie sicher, dass sich alle ONTAP Tool-Knoten im selben Subnetz befinden, um eine unterbrechungsfreie Kommunikation untereinander aufrechtzuerhalten.

Klicken Sie, um die Tabelle mit den Portanforderungen ein- oder auszublenden.

[%collapsible]
====
|===
| *Dienst-/Komponentenname* | *Port* | *Protokoll* | *Anschlusstyp* | *Beschreibung* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Extern | Durchgangsport für eingehende Kommunikation für den VASA-Provider-Dienst. Auf diesem Port werden das selbstsignierte Zertifikat des VASA-Anbieters und das benutzerdefinierte CA-Zertifikat gehostet. 


| SSH | 22 | TCP | Extern | Secure Shell für die Anmeldung am Remote-Server und die Ausführung von Befehlen. 


| rke2-Server | 9345 | TCP | Zwischenknoten | RKE2 Supervisor API (Beschränkung auf vertrauenswürdige Netzwerke). 


| kube-apiserver | 6443 | TCP | Zwischenknoten | Kubernetes API-Server-Port (auf vertrauenswürdige Netzwerke beschränken). 


| rpcbind/portmapper | 111 | TCP/UDP | Zwischenknoten | Wird für die RPC-Kommunikation zwischen Diensten verwendet. 


| coredns (DNS) | 53 | TCP/UDP | Zwischenknoten | Domain Name System (DNS)-Dienst zur Namensauflösung innerhalb des Clusters. 


| NTP | 123 | UDP | Zwischenknoten | Netzwerkzeitprotokoll (NTP) zur Zeitsynchronisation. 


| etcd | 2379, 2380, 2381 | TCP | Zwischenknoten | Schlüsselwertspeicher für Clusterdaten. 


| kube-vip | 2112 | TCP | Zwischenknoten | Kubernetes API-Server-Port. 


| kubelet | 10248, 10250 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-controller | 10257 | TCP | Zwischenknoten | Kubernetes-Komponente 


| Cloud-Controller | 10258 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-scheduler | 10259 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-proxy | 10249, 10256 | TCP | Zwischenknoten | Kubernetes-Komponente 


| Kaliko-Knoten | 9091, 9099 | TCP | Zwischenknoten | Calico-Netzwerkkomponente. 


| containerd | 10010 | TCP | Zwischenknoten | Container-Daemon-Dienst. 


| VXLAN (Flannel) | 8472 | UDP | Zwischenknoten | Overlay-Netzwerk für die Pod-Kommunikation. 
|===

NOTE: Bei HA-Bereitstellungen muss sichergestellt werden, dass der UDP-Port 8472 zwischen allen Knoten geöffnet ist. Dieser Port ermöglicht die Kommunikation zwischen Pods über verschiedene Knoten hinweg; durch Blockierung wird die Netzwerkverbindung zwischen den Knoten unterbrochen.

====


[[configuration-limits-for-vvol-datastores]]
== Konfigurationsbeschränkungen für vVol Datenspeicher

Die folgende Tabelle dient als Leitfaden für die Konfiguration von ONTAP tools for VMware vSphere.

|===


| * Bereitstellung* | *Typ* | *Anzahl der VVols* | *Anzahl der Hosts* 


| Ohne HA | Klein (S) | bis zu 12K | 32 


| Ohne HA | Mittel (M) | bis zu 24K | 64 


| Hochverfügbarkeit | Klein (S) | bis zu 24K | 64 


| Hochverfügbarkeit | Mittel (M) | bis zu 50K | 128 


| Hochverfügbarkeit | Groß (L) | bis zu 100K | 256 
|===

NOTE: Die Host-Zahlen in der Tabelle stellen die kombinierte Gesamtzahl über alle verbundenen vCenters dar.



[[configuration-limits-for-vmfs-and-nfs-datastores]]
== Konfigurationsbeschränkungen für VMFS und NFS-Datenspeicher

Die in diesem Abschnitt aufgeführten Konfigurationsgrenzen sind von NetApp validiert und unterstützt. Die tatsächlichen Grenzen können je nach Umgebung und Arbeitslast variieren. Eine Überschreitung dieser Grenzen kann die Leistung oder die Supportfähigkeit beeinträchtigen und wird nicht empfohlen. Beachten Sie Folgendes bei der Durchsicht der Tabelle:

* Die Notfallwiederherstellung (Disaster Recovery, DR) virtueller Maschinen wird mithilfe von synchronen, asynchronen oder strikten Sync-Richtlinien konfiguriert. DR wird für das NVMe-Protokoll nicht unterstützt.
* Der ESXi-Hostclusterschutz verwendet SnapMirror Active Sync, welches keine Multi-vCenter-Bereitstellungen unterstützt.
* ONTAP tools beschränkt lediglich die Anzahl der ESXi-Hosts und Datenspeicher basierend auf der Bereitstellungsgröße. Es gibt keine Beschränkungen hinsichtlich der Anzahl der vCenter Server, die mit ONTAP tools verbunden werden können.
* ONTAP tools führt eine parallele Erkennung aller Speicherobjekte durch. Konfigurationsbeschränkungen für ONTAP-Speicherobjekte gelten unabhängig von der Anzahl der aktiv verwendeten Objekte.
* ONTAP tools legt keine Beschränkung hinsichtlich der Anzahl der vCenter Servers fest, die integriert werden können. Die Konfigurationsbeschränkungen werden durch die Anzahl der unterstützten Hosts und Datenspeicher bestimmt, wie in der folgenden Tabelle aufgeführt.


|===
| Bereitstellung | Anzahl der VMFS- und NFS-Datenspeicher | Anzahl der DR-fähigen VMFS-Datenspeicher | Anzahl der Hosts 


| Extra klein | 50 | 50 | 16 


| Nicht-HA klein | 200 | 80 | 32 


| Non-HA Medium | 250 | 100 | 32 


| HA Extra klein | 200 | 100 | 32 


| HA klein | 350 | 200 | 64 


| HA Mittel | 600 | 200 | 128 


| HA groß | 1024 | 250 | 256 
|===


[[ontap-tools-for-vmware-vsphere-storage-replication-adapter-sra]]
== ONTAP Tools für VMware vSphere – Storage Replication Adapter (SRA)

In der folgenden Tabelle sind die Zahlen aufgeführt, die pro VMware Live Site Recovery-Instanz mithilfe von ONTAP Tools für VMware vSphere unterstützt werden.

|===
| *vCenter Bereitstellungsgröße* | *Klein* | *Mittel* 


| Gesamtzahl der virtuellen Maschinen, die für den Schutz mithilfe einer Array-basierten Replikation konfiguriert wurden | 2000 | 5000 


| Gesamtzahl der Array-basierten Replikationsschutzgruppen | 250 | 250 


| Gesamtzahl der Schutzgruppen pro Wiederherstellungsplan | 50 | 50 


| Anzahl replizierter Datastores | 255 | 255 


| Anzahl der VMs | 4000 | 7000 
|===
Die folgende Tabelle zeigt die Anzahl der VMware Live Site Recovery-Instanzen und die entsprechenden ONTAP tools für VMware vSphere-Bereitstellungsgröße.

|===


| *Anzahl der VMware Live Site Recovery Instanzen* | *ONTAP tools Bereitstellungsgröße* 


| Bis zu 4 | Klein 


| 4 bis 8 | Mittel 


| Mehr als 8 | Groß 
|===
Weitere Informationen finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Betriebsgrenzen der VMware Live Site Recovery"].
