---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Sie sollten einen Platzhalter-Datenspeicher konfigurieren, um Platz im vCenter-Inventar am Wiederherstellungsstandort für die geschützte virtuelle Maschine (VM) zu reservieren. Der Platzhalter-Datenspeicher muss nicht groß sein, da die Platzhalter-VMs klein sind und nur wenige hundert Kilobyte oder weniger belegen.' 
---
= Platzhalter-Datastores konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten einen Platzhalterdatenspeicher konfigurieren, der im vCenter-Inventar am Wiederherstellungsstandort Platz für die geschützte virtuelle Maschine (VM) reserviert. Der Platzhalterdatenspeicher muss nicht groß sein, da die Platzhalter-VMs klein sind und nur wenige hundert Kilobyte oder weniger belegen.

.Bevor Sie beginnen
* Sie sollten die geschützten und Recovery-Standorte verbunden haben.
* Sie sollten Ihre Ressourcenzuordnungen konfiguriert haben.


.Schritte
. Melden Sie sich bei vCenter Server an und wählen Sie *Site Recovery* > *Sites*.
. Wählen Sie Ihre geschützte Site aus und wählen Sie *Verwalten*.
. Wählen Sie *Platzhalter-Datenspeicher* > *Neu* auf der Registerkarte Verwalten aus, um einen neuen Platzhalter-Datenspeicher zu erstellen.
. Wählen Sie den entsprechenden Datastore aus und wählen Sie *OK*.
+

NOTE: Als Platzhalter-Datenspeicher können lokale oder Remote-Standorte verwendet werden und sollten nicht repliziert werden.

. Wiederholen Sie die Schritte 3 bis 5, um einen Platzhalterdatenspeicher für den Recovery-Standort zu konfigurieren.

