---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter \(SRA\) für VMware Live Site Recovery ausführen.' 
---
= Konfigurieren Sie SRA in ONTAP tools for VMware vSphere für SAN- und NAS-Umgebungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter (SRA) für die VMware Live Site Recovery ausführen.



== Konfiguration von SRA für SAN-Umgebungen


NOTE: Konsistenzgruppen in SRA-Workflows werden nur mit SAN-Protokollen (iSCSI und Fibre Channel) auf Unified- und ASA r2 Storage-Systemen unterstützt.

.Bevor Sie beginnen
Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* VMware Live Site Recovery: Die VMware-Site bietet Installationsdokumentation für VMware Live Site Recovery.
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Über VMware Live Site Recovery"]

* SRA: Installieren Sie den Adapter auf VMware Live Site Recovery.


Beachten Sie bei der Konfiguration des iSCSI-Protokolls vor dem Ausführen von SRA-Workflows Folgendes:

* *Geschützter Bereich*: iSCSI-Speicheradapter und Daten-LIF-Details werden bei der Bereitstellung von Datenspeichern automatisch konfiguriert. Keine manuelle Konfiguration ist erforderlich.
* *Wiederherstellungsstandort*: iSCSI-Speicheradapter müssen auf jedem ESXi-Host, der in die Ressourcenzuordnung für die Notfallwiederherstellung einbezogen ist, manuell konfiguriert werden. Um die individuelle Konfiguration der Adapter auf jedem Host zu vermeiden, erstellen Sie auf dem Wiederherstellungsstandort mithilfe der SVM, auf der die SRA-Workflows konfiguriert sind, einen Platzhalter-Datenspeicher vom Typ iSCSI. Dadurch werden der iSCSI-Adapter und die erforderlichen Daten-LIF-IP-Adressen automatisch allen zugeordneten ESXi-Hosts hinzugefügt. Weitere Informationen finden Sie unter link:../protect/configure-placeholder-datastores.html["Platzhalterdatenspeicher in ONTAP tools konfigurieren"].


.Schritte
. Vergewissern Sie sich, dass die primären ESXi-Hosts mit den LUNs im primären Speichersystem am geschützten Standort verbunden sind.
. Überprüfen Sie, ob sich die LUNs in igroups befinden, bei denen die  `ostype` Option auf _VMware_ auf dem primären Storage-System gesetzt ist.
. Stellen Sie sicher, dass die ESXi-Hosts am Wiederherstellungsstandort über eine entsprechende iSCSI- und Fibre Channel-Konnektivität zur Storage Virtual Machine (SVM) verfügen.  Die ESXi-Hosts des sekundären Standorts sollten Zugriff auf den Speicher des sekundären Standorts haben und die ESXi-Hosts des primären Standorts sollten Zugriff auf den Speicher des primären Standorts haben.
+
Dazu können Sie entweder überprüfen, ob die ESXi-Hosts über lokale LUNs auf der SVM oder auf der verfügen `iscsi show initiators` Befehl auf den SVMs.
Überprüfen Sie den LUN-Zugriff auf die zugeordneten LUNs auf dem ESXi-Host, um die iSCSI-Konnektivität zu überprüfen.





== Konfiguration von SRA für NAS-Umgebungen


NOTE: Konsistenzgruppen werden für NFS in SRA-Workflows nicht unterstützt. Wenn NFS-Datenspeichervolumes einer Konsistenzgruppe zugeordnet und geschützt werden, schlägt der Vorgang „Geräte ermitteln“ fehl. Verwenden Sie keine Konsistenzgruppen, wenn Sie NFS-Datenspeicher mit SRA schützen.

.Bevor Sie beginnen
Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* VMware Live Site Recovery: Installationsdokumentation für VMware Live Site Recovery finden Sie auf der VMware-Site – https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Über VMware Live Site Recovery"]
* SRA: Installieren Sie den Adapter auf VMware Live Site Recovery und dem SRA-Server.


.Schritte
. Überprüfen Sie, ob die Datenspeicher am geschützten Standort virtuelle Maschinen enthalten, die bei vCenter Server registriert sind.
. Überprüfen Sie, ob die ESXi-Hosts am geschützten Standort die NFS-Exportvolumes der Storage Virtual Machine (SVM) eingebunden haben.
. Stellen Sie sicher, dass im Feld *NFS Addresses* gültige IP-Adressen angegeben sind, unter denen die NFS-Exporte vorhanden sind, wenn Sie den Array Manager-Assistenten zum Hinzufügen von Arrays zu VMware Live Site Recovery verwenden. Verwenden Sie im Feld *NFS Addresses* nicht den NFS-Hostnamen oder den FQDN.
. Verwenden Sie die `ping` Führen Sie einen Befehl auf jedem ESXi Host am Recovery-Standort aus, um zu überprüfen, ob der Host über einen VMkernel-Port verfügt, der auf die IP-Adressen zugreifen kann, die für NFS-Exporte von der SVM verwendet werden.

