---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter \(SRA\) für VMware Live Site Recovery ausführen.' 
---
= Konfigurieren Sie SRA in ONTAP tools for VMware vSphere für SAN- und NAS-Umgebungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter (SRA) für die VMware Live Site Recovery ausführen.



== Konfiguration von SRA für SAN-Umgebungen

.Bevor Sie beginnen
Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* VMware Live Site Recovery: Die VMware-Site bietet Installationsdokumentation für VMware Live Site Recovery.
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Über VMware Live Site Recovery"]

* SRA: Installieren Sie den Adapter auf VMware Live Site Recovery.


.Schritte
. Vergewissern Sie sich, dass die primären ESXi-Hosts mit den LUNs im primären Speichersystem am geschützten Standort verbunden sind.
. Vergewissern Sie sich, dass die LUNS in Initiatorgruppen vorhanden sind, die über die verfügen `ostype` Option auf dem primären Storage-System auf _VMware_ eingestellt.
. Stellen Sie sicher, dass die ESXi-Hosts am Wiederherstellungsstandort über eine entsprechende iSCSI- und Fibre Channel-Konnektivität zur Storage Virtual Machine (SVM) verfügen.  Die ESXi-Hosts des sekundären Standorts sollten Zugriff auf den Speicher des sekundären Standorts haben und die ESXi-Hosts des primären Standorts sollten Zugriff auf den Speicher des primären Standorts haben.
+
Dazu können Sie entweder überprüfen, ob die ESXi-Hosts über lokale LUNs auf der SVM oder auf der verfügen `iscsi show initiators` Befehl auf den SVMs.
Überprüfen Sie den LUN-Zugriff auf die zugeordneten LUNs auf dem ESXi-Host, um die iSCSI-Konnektivität zu überprüfen.





== Konfiguration von SRA für NAS-Umgebungen

.Bevor Sie beginnen
Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* VMware Live Site Recovery: Installationsdokumentation für VMware Live Site Recovery finden Sie auf der VMware-Site – https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Über VMware Live Site Recovery"]
* SRA: Installieren Sie den Adapter auf VMware Live Site Recovery und dem SRA-Server.


.Schritte
. Überprüfen Sie, ob die Datenspeicher am geschützten Standort virtuelle Maschinen enthalten, die bei vCenter Server registriert sind.
. Überprüfen Sie, ob die ESXi-Hosts am geschützten Standort die NFS-Exporte-Volumes von der Storage Virtual Machine (SVM) gemountet haben.
. Stellen Sie sicher, dass gültige Adressen wie die IP-Adresse oder der FQDN, unter dem die NFS-Exporte vorliegen, im Feld *NFS-Adressen* angegeben sind, wenn Sie den Array Manager-Assistenten zum Hinzufügen von Arrays zu VMware Live Site Recovery verwenden. Verwenden Sie im Feld *NFS-Adressen* nicht den NFS-Hostnamen.
. Verwenden Sie die `ping` Führen Sie einen Befehl auf jedem ESXi Host am Recovery-Standort aus, um zu überprüfen, ob der Host über einen VMkernel-Port verfügt, der auf die IP-Adressen zugreifen kann, die für NFS-Exporte von der SVM verwendet werden.

