---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Konfigurieren Sie einen Platzhalterdatenspeicher, um im vCenter-Inventar am Wiederherstellungsstandort Speicherplatz für geschützte virtuelle Maschinen (VMs) zu reservieren.  Platzhalter-Datenspeicher erfordern nur minimale Kapazität, da Platzhalter-VMs klein sind und normalerweise nur einige hundert Kilobyte verwenden.' 
---
= Platzhalterdatenspeicher in ONTAP tools konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Konfigurieren Sie einen Platzhalterdatenspeicher, um im vCenter-Inventar am Wiederherstellungsstandort Speicherplatz für geschützte virtuelle Maschinen (VMs) zu reservieren.  Platzhalter-Datenspeicher erfordern nur minimale Kapazität, da Platzhalter-VMs klein sind und normalerweise nur einige hundert Kilobyte verwenden.

.Bevor Sie beginnen
* Stellen Sie sicher, dass die geschützten Sites und die Wiederherstellungssites verbunden sind.
* Überprüfen Sie, ob die Ressourcenzuordnungen konfiguriert wurden.


.Schritte
. Melden Sie sich bei vCenter Server an und wählen Sie *Site Recovery* > *Sites*.
. Wählen Sie Ihre geschützte Site aus und wählen Sie *Verwalten*.
. Wählen Sie *Platzhalter-Datenspeicher* > *Neu* auf der Registerkarte Verwalten aus, um einen neuen Platzhalter-Datenspeicher zu erstellen.
. Wählen Sie den entsprechenden Datastore aus und wählen Sie *OK*.
+

NOTE: Platzhalter-Datenspeicher können sich auf einem lokalen oder Remote-Speicher befinden, erfordern jedoch keine Replikation.

. Wiederholen Sie die Schritte 3 bis 5, um einen Platzhalterdatenspeicher für den Recovery-Standort zu konfigurieren.

