---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten Schutzgruppen erstellen, um eine Gruppe virtueller Maschinen am geschützten Standort zu schützen. 
---
= Konfigurieren von geschützten und Wiederherstellungsstandorten in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten Schutzgruppen erstellen, um eine Gruppe virtueller Maschinen am geschützten Standort zu schützen.

Wenn Sie einen neuen Datenspeicher hinzufügen, können Sie ihn in die bestehende Datenspeichergruppe aufnehmen oder einen neuen Datenspeicher hinzufügen und ein neues Volume oder eine neue Konsistenzgruppe zum Schutz erstellen. Nachdem Sie einen neuen Datenspeicher zu einer geschützten Konsistenzgruppe oder einem geschützten Volume hinzugefügt haben, aktualisieren Sie SnapMirror und führen Sie die Speichererkennung sowohl auf dem geschützten als auch auf dem Wiederherstellungsstandort durch. Sie können die Erkennung manuell oder nach Zeitplan durchführen, um sicherzustellen, dass der neue Datenspeicher erkannt und geschützt wird.



== Kombinieren Sie geschützte Standorte und Recovery-Standorte

Sie sollten die geschützten und Recovery-Standorte, die mit Ihrem vSphere Client erstellt wurden, koppeln, um Storage Replication Adapter (SRA) zur Erkennung der Speichersysteme zu aktivieren.


NOTE: Der Storage Replication Adapter (SRA) unterstützt Fan-Out mit einer synchronen Beziehung vom Typ Automated Failover Duplex und einer asynchronen SnapMirror-Beziehung in einer Konsistenzgruppe. Fan-Out mit zwei asynchronen SnapMirror-Beziehungen in Konsistenzgruppen oder Fan-Out SnapMirror-Beziehungen auf Volumes wird jedoch nicht unterstützt. Vault-Typ SnapMirror-Beziehungen sind von diesen Fan-Out-Beschränkungen ausgenommen. Die Unterstützung von Konsistenzgruppen im SRA ist auf SAN-Protokolle (iSCSI und Fibre Channel) auf Unified- und ASA r2 Storage-Systemen beschränkt. Konsistenzgruppen werden für NFS nicht unterstützt; wenn NFS-Datenspeichervolumes einer Konsistenzgruppe zugeordnet werden, schlägt die Discover Devices-Operation fehl.

.Bevor Sie beginnen
* VMware Live Site Recovery sollte auf den geschützten und Recovery-Standorten installiert sein.
* SRA sollte auf den geschützten und den Recovery-Standorten installiert sein.


.Schritte
. Doppelklicken Sie auf der Startseite des vSphere-Clients auf das Symbol *Site Recovery* und wählen Sie dann *Sites* aus.
. Wählen Sie *Objects* > *Actions* > *Pair Sites*.
. Geben Sie im Dialogfeld *Pair Site Recovery Manager Servers* die Adresse des Platform Services Controllers des geschützten Standorts ein, und wählen Sie dann *Next*.
. Gehen Sie im Abschnitt vCenter Server auswählen folgendermaßen vor:
+
.. Stellen Sie sicher, dass der vCenter Server des geschützten Standorts als übereinstimmender Kandidat für das Pairing angezeigt wird.
.. Geben Sie die SSO-Administratoranmeldedaten ein, und wählen Sie dann *Finish*.


. Wenn Sie dazu aufgefordert werden, wählen Sie *Ja*, um die Sicherheitszertifikate zu akzeptieren.


.Ergebnis
Im Dialogfeld *Objekte* werden sowohl die geschützten als auch die Wiederherstellungssites angezeigt.



== Konfigurieren Sie Schutzgruppen

.Bevor Sie beginnen
Stellen Sie sicher, dass die Quell- und Zielstandorte für Folgendes konfiguriert sind:

* Dieselbe Version von VMware Live Site Recovery ist installiert
* Virtual Machines
* Gepaarte geschützte Standorte und Recovery-Standorte
* Quell- und Ziel-Datastores sollten auf den jeweiligen Sites gemountet werden


.Schritte
. Melden Sie sich bei vCenter Server an und wählen Sie *Site Recovery* > *Schutzgruppen*.
. Wählen Sie im Bereich *Schutzgruppen* *Neu* aus.
. Geben Sie einen Namen und eine Beschreibung für die Schutzgruppe, Richtung und wählen Sie *Weiter*.
. Wählen Sie im Feld *Typ* die Option *Typfeld...* als Datenspeichergruppen (Array-basierte Replikation) für NFS- und VMFS-Datenspeicher aus. Die Fehlerdomäne besteht aus SVMs mit aktivierter Replikation. Die SVMs, die ausschließlich Peering implementiert haben und keine Probleme aufweisen, werden angezeigt.
. Wählen Sie auf der Registerkarte Replikationsgruppen entweder das aktivierte Array-Paar oder die Replikationsgruppen aus, für die die virtuelle Maschine konfiguriert ist, und wählen Sie dann *Weiter* aus.
+
Alle virtuellen Maschinen auf der Replikationsgruppe werden der Schutzgruppe hinzugefügt.

. Sie können entweder den vorhandenen Wiederherstellungsplan auswählen oder einen neuen erstellen, indem Sie *Zum neuen Wiederherstellungsplan hinzufügen* auswählen.
. Überprüfen Sie auf der Registerkarte bereit zur Fertigstellung die Details der von Ihnen erstellten Schutzgruppe, und wählen Sie dann *Fertig stellen* aus.

