---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter \(SRA\) für Site Recovery Manager \(SRM\) ausführen.' 
---
= Konfiguration von SRA für SAN- und NAS-Umgebungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Speichersysteme einrichten, bevor Sie Storage Replication Adapter (SRA) für Site Recovery Manager (SRM) ausführen.



== Konfiguration von SRA für SAN-Umgebung

*Was Sie brauchen*

Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* SRM
+
Dokumentation zur Installation von SRM befindet sich auf der VMware Site.

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager - Dokumentation"]

* SRA
+
Der Adapter wird entweder auf SRM installiert.



*Schritte*

. Vergewissern Sie sich, dass die primären ESXi-Hosts mit den LUNs im primären Speichersystem am geschützten Standort verbunden sind.
. Vergewissern Sie sich, dass die LUNS in Initiatorgruppen vorhanden sind, die über die verfügen `ostype` Option auf dem primären Storage-System auf _VMware_ eingestellt.
. Überprüfen Sie, ob die ESXi-Hosts am Wiederherstellungsstandort über eine geeignete iSCSI-Verbindung zur Storage Virtual Machine (SVM) verfügen. Die ESXi-Hosts der sekundären Site sollten Zugriff auf den sekundären Standort-Storage haben, ebenso sollten die ESXi-Hosts des primären Standorts Zugriff auf den primären Standort-Storage haben.
+
Dazu können Sie entweder überprüfen, ob die ESXi-Hosts über lokale LUNs auf der SVM oder auf der verfügen `iscsi show initiators` Befehl auf den SVMs.
Überprüfen Sie den LUN-Zugriff auf die zugeordneten LUNs auf dem ESXi-Host, um die iSCSI-Konnektivität zu überprüfen.





== Konfiguration von SRA für NAS-Umgebung

*Was Sie brauchen*

Die folgenden Programme sollten auf dem geschützten Standort und dem Wiederherstellungsstandort installiert sein:

* SRM
+
Dokumentation zur Installation von SRM finden Sie auf der VMware-Website.

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager - Dokumentation"]

* SRA
+
Der Adapter wird auf SRM und dem SRA Server installiert.



*Schritte*

. Überprüfen Sie, ob die Datenspeicher am geschützten Standort virtuelle Maschinen enthalten, die bei vCenter Server registriert sind.
. Überprüfen Sie, ob die ESXi-Hosts am geschützten Standort die NFS-Exporte-Volumes von der Storage Virtual Machine (SVM) gemountet haben.
. Überprüfen Sie, ob gültige Adressen wie die IP-Adresse, der Hostname oder der FQDN, auf denen die NFS-Exporte vorhanden sind, im Feld *NFS-Adressen* angegeben sind, wenn Sie den Array Manager-Assistenten zum Hinzufügen von Arrays zu SRM verwenden.
. Verwenden Sie die `ping` Führen Sie einen Befehl auf jedem ESXi Host am Recovery-Standort aus, um zu überprüfen, ob der Host über einen VMkernel-Port verfügt, der auf die IP-Adressen zugreifen kann, die für NFS-Exporte von der SVM verwendet werden.

