---
permalink: protect/pair-protected-and-recovery-sites.html 
sidebar: sidebar 
keywords:  
summary: 'Sie sollten die mit Ihrem vSphere-Client erstellten geschützten und Recovery-Standorte koppeln, um Storage Replication Adapter \ (SRA\) zur Erkennung der Speichersysteme zu aktivieren.' 
---
= Kombinieren Sie geschützte Standorte und Recovery-Standorte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die geschützten und Recovery-Standorte, die mit Ihrem vSphere Client erstellt wurden, koppeln, um Storage Replication Adapter (SRA) zur Erkennung der Speichersysteme zu aktivieren.

.Bevor Sie beginnen
* VMware Live Site Recovery sollte auf den geschützten und Recovery-Standorten installiert sein.
* SRA sollte auf den geschützten und den Recovery-Standorten installiert sein.


.Schritte
. Doppelklicken Sie auf der vSphere Client-Startseite auf *Site Recovery* und wählen Sie *Sites* aus.
. Wählen Sie *Objects* > *Actions* > *Pair Sites*.
. Geben Sie im Dialogfeld *Pair Site Recovery Manager Servers* die Adresse des Platform Services Controllers des geschützten Standorts ein, und wählen Sie dann *Next*.
. Gehen Sie im Abschnitt vCenter Server auswählen folgendermaßen vor:
+
.. Stellen Sie sicher, dass der vCenter Server des geschützten Standorts als übereinstimmender Kandidat für das Pairing angezeigt wird.
.. Geben Sie die SSO-Administratoranmeldedaten ein, und wählen Sie dann *Finish*.


. Wenn Sie dazu aufgefordert werden, wählen Sie *Ja*, um die Sicherheitszertifikate zu akzeptieren.


.Ergebnis
Sowohl die geschützten als auch die Wiederherstellungsstandorte werden im Dialogfeld Objekte angezeigt.
