---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Damit VMware Live Site Recovery mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldeinformationen auf dem VMware Live Site Recovery-Server aktualisieren, wenn Sie die Anmeldeinformationen geändert haben. 
---
= Aktualisieren Sie die SRA-Anmeldeinformationen in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit VMware Live Site Recovery mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldeinformationen auf dem VMware Live Site Recovery-Server aktualisieren, wenn Sie die Anmeldeinformationen geändert haben.

.Bevor Sie beginnen
Sie sollten die im Thema genannten Schritte ausgeführt haben link:../protect/configure-on-srm-appliance.html["Konfigurieren von SRA auf einer VMware Live Site Recovery-Appliance"].

.Schritte
. Führen Sie die folgenden Befehle aus, um die zwischengespeicherten ONTAP tools-Anmeldeinformationen von der VMware Live Site Recovery-Maschine zu löschen:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Führen Sie den Perl-Befehl aus, um SRA mit den neuen Anmeldeinformationen zu konfigurieren:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Sie benötigen ein einziges Angebot um den Passwortwert herum.
+
Es wird eine Erfolgsmeldung angezeigt, die bestätigt, dass die Speicherzugangsdaten gespeichert wurden. SRA kann über die angegebene IP-Adresse, den Port und die Zugangsdaten mit dem SRA-Server kommunizieren.







== Konfigurieren Sie vCenter in der VMware Live Site Recovery Appliance nach einer Zertifikatsänderung neu

Wenn sich das vCenter-Zertifikat ändert, beispielsweise nach einem vCenter-Upgrade, kann bei der Site Recovery-Erweiterung ein Fehler aufgrund eines nicht übereinstimmenden Fingerabdrucks auftreten. Führen Sie die folgenden Schritte aus, um das Problem zu beheben.

.Schritte
. Neukonfiguration vCenter in der VMware Live Site Recovery Appliance
+
.. Öffnen Sie die VMware Live Site Recovery Appliance Managementoberfläche in einem Browser: `\https://<SRM_IP>:5480`
.. Wählen Sie die Registerkarte *Zusammenfassung*.
.. Wählen Sie *Neu konfigurieren* für die vCenter Serververbindung.
+
Dies ruft den neuesten Zertifikatfingerabdruck von vCenter ab und akzeptiert ihn.



. Stellen Sie die Standortkopplung erneut her (falls der Fehler weiterhin besteht)
+
Wenn der Fehler mit der Fingerabdruckabweichung auch nach der Neukonfiguration weiterhin besteht:

+
.. Melden Sie sich bei der vCenter Benutzeroberfläche an.
.. Navigieren Sie zur Erweiterung *Site Recovery*.
.. Suchen Sie den Abschnitt *Site Pairing*.
.. Wählen Sie *Neu verbinden*, um die Standortkopplung mit dem aktualisierten Zertifikat wiederherzustellen.



