---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für VMware vSphere ist eine Sammlung von Tools für das Lifecycle Management von Virtual Machines. Die Lösung lässt sich in das VMware Ecosystem integrieren und unterstützt bei der Bereitstellung, grundlegenden Sicherung und Disaster Recovery von Virtual Machines. 
---
= Erfahren Sie mehr über ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere sind ein Satz von Tools für das Lebenszyklusmanagement virtueller Maschinen.  Es lässt sich in das VMware-Ökosystem integrieren, um die Bereitstellung von Datenspeichern zu vereinfachen und einen grundlegenden Schutz für virtuelle Maschinen bereitzustellen.  Es handelt sich um eine Sammlung horizontal skalierbarer, ereignisgesteuerter Microservices, die als Open Virtual Appliance (OVA) bereitgestellt werden.

ONTAP tools for VMware vSphere unterstützen:

* Kernfunktionen virtueller Maschinen (VM) wie Schutz und Notfallwiederherstellung
* VASA-Anbieter für speicherrichtlinienbasiertes Management
* Richtlinienbasiertes Storage-Management
* Storage Replication Adapter (SRA)


.Hohe Verfügbarkeit für ONTAP -Tools für VMware
ONTAP tools for VMware vSphere bieten Hochverfügbarkeitsunterstützung (HA), um bei Ausfällen einen unterbrechungsfreien Betrieb aufrechtzuerhalten.

Die HA-Lösung unterstützt Sie bei der schnellen Wiederherstellung nach den folgenden Arten von Ausfällen:

* Hostausfall – Es wird nur der Ausfall eines einzelnen Knotens unterstützt.
* Netzwerkausfall
* Ausfall der virtuellen Maschine (Gastbetriebssystem)
* Anwendungsfehler (ONTAP -Tools)


Sie müssen keine zusätzliche Konfiguration durchführen, um HA für ONTAP tools for VMware vSphere zu aktivieren.

[NOTE]
====
ONTAP tools for VMware vSphere unterstützen vCenter HA nicht.

====
Um die HA-Funktion zu verwenden, stellen Sie sicher, dass CPU-Hot-Add und Memory-Hot-Plug während der Bereitstellung oder später in den VM-Einstellungen aktiviert sind.
