---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords: key concepts, ONTAP tools terms, consistency group, dual stack 
summary: Wichtige Konzepte und Begriffe, die in der ONTAP tools for VMware vSphere Dokumentation verwendet werden, im Überblick. 
---
= Wichtige Begriffe und Definitionen für ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den wichtigsten Konzepten und der Terminologie, die in ONTAP tools for VMware vSphere verwendet werden, vertraut machen. Die Definitionen umfassen Storage-Backends, virtuelle Volumes (vVols), SnapMirror active sync, VASA, SRA und andere Kernkomponenten.



[[certificate-authority-ca]]
=== Zertifizierungsstelle (CA)

Eine Zertifizierungsstelle (CA) ist eine vertrauenswürdige Instanz, die Secure Sockets Layer (SSL)-Zertifikate ausstellt.



[[consistency-group]]
=== Konsistenzgruppe

Eine Konsistenzgruppe ist eine Sammlung von Volumes, die als eine Einheit verwaltet werden. Konsistenzgruppen werden synchronisiert, um Datenkonsistenz über Speichereinheiten und Volumes hinweg zu gewährleisten. In ONTAP bieten sie einfache Verwaltung und Schutzgarantien für einen Anwendungsworkload, der sich über mehrere Volumes erstreckt. Erfahren Sie mehr über https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["Konsistenzgruppen"].



[[dual-stack]]
=== Dual-Stack

Ein Dual-Stack-Netzwerk ist eine Netzwerkumgebung, die die gleichzeitige Verwendung von IPv4- und IPv6-Adressen unterstützt.



[[high-availability-ha]]
=== Hochverfügbarkeit

Cluster Nodes werden für einen unterbrechungsfreien Betrieb in HA-Paaren konfiguriert.



[[logical-unit-number-lun]]
=== Logical Unit Number (LUN)

Eine LUN ist eine Zahl, mit der eine logische Einheit innerhalb eines Storage Area Network (SAN) identifiziert wird. Bei diesen adressierbaren Geräten handelt es sich in der Regel um logische Laufwerke, auf die über das SCSI-Protokoll (Small Computer System Interface) oder eines seiner gekapselten Derivate zugegriffen wird.



[[nvme-namespace-and-subsystem]]
=== NVMe-Namespace und -Subsystem

Ein NVMe-Namespace ist eine Menge nichtflüchtigen Speichers, die in logische Blöcke formatiert werden kann. Namespaces sind das Äquivalent von LUNs bei FC- und iSCSI-Protokollen, und ein NVMe-Subsystem ist analog zu einer Initiatorgruppe. Ein NVMe-Subsystem kann mit Initiatoren verknüpft werden, sodass diese auf Namespaces innerhalb des Subsystems zugreifen können.



[[ontap-tools-manager]]
=== ONTAP Tools Manager

ONTAP tools Manager bietet ONTAP tools for VMware vSphere-Administratoren mehr Kontrolle über die verwalteten vCenter Serverinstanzen und eingebundene Storage-Backends. Er hilft bei der Verwaltung von vCenter Serverinstanzen, Storage-Backends, Zertifikaten, Passwörtern und Log-Bundles.



[[open-virtual-appliance-ova]]
=== Offene virtuelle Appliance (OVA)

OVA ist ein offener Standard für die Paketierung und Verteilung virtueller Appliances oder Software, die auf virtuellen Maschinen ausgeführt werden müssen.



[[recovery-point-objective-rpo]]
=== Recovery-Zeitpunkt (RPO)

Der RPO-Wert (Recovery Point Objective) gibt an, wie häufig Daten gesichert oder repliziert werden. Er legt den genauen Zeitpunkt fest, zu dem Daten nach einem Ausfall wiederhergestellt sein müssen, um den Geschäftsbetrieb wiederaufzunehmen. Hat ein Unternehmen beispielsweise einen RPO-Wert von vier Stunden, kann es im Katastrophenfall einen Datenverlust von bis zu vier Stunden tolerieren.



[[snapmirror-active-sync]]
=== SnapMirror Active Sync

SnapMirror active sync ermöglicht, dass Unternehmensdienste auch bei einem vollständigen Standortausfall weiter betrieben werden können, wobei Anwendungen mithilfe einer sekundären Kopie transparent auf ein Failover umschalten. SnapMirror active sync erfordert weder manuelle Eingriffe noch benutzerdefinierte Skripte, um ein Failover auszulösen. Weitere Informationen zu https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["SnapMirror Active Sync"].



[[storage-backends]]
=== Storage-Back-Ends

Storage-Back-Ends sind die zugrunde liegende Storage-Infrastruktur, die der ESXi Host zum Speichern von Virtual Machine-Dateien, Daten und anderen Ressourcen verwendet. Sie ermöglichen es dem ESXi-Host, auf persistente Daten zuzugreifen und diese zu managen, und liefern die erforderliche Storage-Funktionalität und Performance für eine virtualisierte Umgebung.

.Globaler Cluster (Storage Back-End)
Globale Storage Back-Ends, die nur mit ONTAP Cluster-Anmeldeinformationen verfügbar sind, werden über die Benutzeroberfläche des ONTAP Tools Managers aufgenommen. Sie können mit minimalem Privileges hinzugefügt werden, um wichtige Cluster-Ressourcen für das Management von VVols aufzufinden. Globale Cluster eignen sich ideal für mandantenfähige Szenarien, in denen ein SVM-Benutzer zum VVols-Management lokal hinzugefügt wird.

.Lokales Storage-Back-End
Lokale Storage-Back-Ends mit Cluster- oder SVM-Zugangsdaten werden über die Benutzeroberfläche der ONTAP Tools hinzugefügt und sind auf vCenter beschränkt. Bei lokaler Verwendung der Cluster-Anmeldeinformationen ordnen die zugehörigen SVMs automatisch dem vCenter zu, um VVols oder VMFS zu managen. Für VMFS-Management, einschließlich SRA, unterstützen ONTAP-Tools SVM-Zugangsdaten, ohne dass ein globales Cluster erforderlich ist.



[[storage-replication-adapter-sra]]
=== Storage Replication Adapter (SRA)

SRA ist die spezifische Storage-Software, die in der VMware Live Site Recovery-Appliance installiert ist. Der Adapter ermöglicht die Kommunikation zwischen dem Site Recovery Manager und einem Storage Controller auf Storage Virtual Machine (SVM)-Ebene und der Konfiguration auf Cluster-Ebene.



[[storage-virtual-machine-svm]]
=== Storage Virtual Machine (SVM)

SVM ist die Mandantenfähigkeitseinheit in ONTAP. Ähnlich einer virtuellen Maschine auf einem Hypervisor ist SVM eine logische Einheit, die physische Ressourcen abstrahiert. SVM enthält Datenvolumes und eine oder mehrere LIFs, über die Daten an Clients bereitgestellt werden.



[[uniform-and-non-uniform-configuration]]
=== Einheitliche und uneinheitliche Konfiguration

* *Einheitlicher Hostzugriff* bedeutet, dass Hosts von zwei Standorten mit allen Pfaden zu Speicherclustern an beiden Standorten verbunden sind. Standortübergreifende Pfade sind über Entfernungen verteilt.
* *Uneinheitlicher Hostzugriff* bedeutet, dass Hosts an jedem Standort nur mit dem Cluster am selben Standort verbunden sind. Standortübergreifende Pfade und gestreckte Pfade sind nicht miteinander verbunden.
+

NOTE: SnapMirror active sync unterstützt einheitlichen Hostzugriff für jede Bereitstellung, nicht einheitlicher Hostzugriff wird nur bei symmetrischen Aktiv/Aktiv-Bereitstellungen unterstützt. Weitere Informationen zu  https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Übersicht über die aktive SnapMirror-Synchronisierung in ONTAP"].





[[virtual-machine-file-system-vmfs]]
=== Virtual Machine File System (VMFS)

VMFS ist ein geclustertes Dateisystem, das zum Speichern von Dateien von virtuellen Maschinen in VMware vSphere-Umgebungen entwickelt wurde.



[[virtual-volumes-vvols]]
=== Virtuelle Volumes (VVols)

vVols bieten eine Abstraktion auf Volumenebene für den von einer virtuellen Maschine genutzten Speicher. vVols umfassen mehrere Vorteile und bieten eine Alternative zur Verwendung einer herkömmlichen LUN. Ein vVol Datenspeicher ist typischerweise mit einer einzelnen LUN verknüpft, die als Container für vVols dient.



[[vm-storage-policy]]
=== VM-Storage-Richtlinie

VM Storage Policies werden im vCenter Server unter Policies and Profiles erstellt. Für VVols erstellen Sie mithilfe von Regeln des NetApp VVols Storage-Typ-Providers eine Regelsammlung.



[[vmware-live-site-recovery]]
=== VMware Live Site Recovery

VMware Live Site Recovery, ehemals bekannt als Site Recovery Manager (SRM), bietet Funktionen für Geschäftskontinuität, Notfallwiederherstellung, Standortmigration und unterbrechungsfreies Testen in virtuellen VMware-Umgebungen.



[[vmware-vsphere-apis-for-storage-awareness-vasa]]
=== VMware vSphere APIs für Storage Awareness (VASA)

VASA besteht aus APIs, die Storage-Arrays für Management und Administration mit vCenter Server integrieren. Die Architektur basiert auf mehreren Komponenten, einschließlich dem VASA Provider, der die Kommunikation zwischen VMware vSphere und den Storage-Systemen übernimmt.



[[vmware-vsphere-storage-apis-array-integration-vaai]]
=== VMware vSphere Storage-APIs – Array-Integration (VAAI)

VAAI ist ein Satz von APIs, der die Kommunikation zwischen VMware vSphere ESXi-Hosts und den Speichergeräten ermöglicht. Die APIs enthalten eine Reihe von primitiven Operationen, die von den Hosts zur Auslagerung von Speicheroperationen auf das Array verwendet werden. VAAI kann für Storage-intensive Aufgaben erhebliche Performance-Steigerungen bieten.



[[vsphere-metro-storage-cluster]]
=== VSphere Metro Storage-Cluster

vSphere Metro Storage Cluster (vMSC) ist eine Architektur, die vSphere in einer Stretch-Cluster-Bereitstellung ermöglicht und unterstützt. vMSC-Lösungen werden auf NetApp MetroCluster und SnapMirror active sync (ehemals SMBC) unterstützt. Diese Lösungen bieten verbesserte Geschäftskontinuität im Falle eines Domänenausfalls. Das Resilienzmodell basiert auf Ihren spezifischen Konfigurationsentscheidungen. Erfahren Sie mehr https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro Storage-Cluster"].



[[vvols-datastore]]
=== VVols Datastore

Der vVols Datenspeicher ist eine logische Repräsentation eines vVols Containers, der von einem VASA Provider erstellt und verwaltet wird.



[[zero-rpo]]
=== Kein RPO

RPO steht für den Recovery Point Objective, die Menge des Datenverlusts, der während eines bestimmten Zeitraums als akzeptabel erachtet wird. Ein RPO von null bedeutet, dass kein Datenverlust akzeptabel ist.
