---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords: ONTAP tools overview, virtual machine lifecycle, VASA Provider, disaster recovery 
summary: Es wird erläutert, wie ONTAP tools for VMware vSphere die Verwaltung des Speicherlebenszyklus virtueller Maschinen, die Bereitstellung von Datenspeichern und die Notfallwiederherstellung unterstützt. 
---
= Erfahren Sie mehr über ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools für VMware vSphere ist eine Sammlung von Werkzeugen für das Lebenszyklusmanagement von Speichersystemen virtueller Maschinen. Es integriert sich in das VMware-Ökosystem, um die Bereitstellung von Datenspeichern zu vereinfachen und grundlegenden Schutz für virtuelle Maschinen bereitzustellen. Es ist eine Sammlung horizontal skalierbarer, ereignisgesteuerter Microservices, die als Open Virtual Appliance (OVA) bereitgestellt werden.

ONTAP tools for VMware vSphere unterstützen:

* Kernfunktionen virtueller Maschinen (VM) wie Schutz und Notfallwiederherstellung
* VASA-Anbieter für speicherrichtlinienbasiertes Management
* Richtlinienbasiertes Storage-Management
* Storage Replication Adapter (SRA)


.Hohe Verfügbarkeit für ONTAP -Tools für VMware
ONTAP tools for VMware vSphere bieten Hochverfügbarkeitsunterstützung (HA), um bei Ausfällen einen unterbrechungsfreien Betrieb aufrechtzuerhalten.

Die HA-Lösung unterstützt Sie bei der schnellen Wiederherstellung nach den folgenden Arten von Ausfällen:

* Hostausfall – Es wird nur der Ausfall eines einzelnen Knotens unterstützt.
* Netzwerkausfall
* Ausfall der virtuellen Maschine (Gastbetriebssystem)
* Anwendungsfehler (ONTAP -Tools)


Sie müssen keine zusätzliche Konfiguration durchführen, um HA für ONTAP tools for VMware vSphere zu aktivieren.

[NOTE]
====
ONTAP tools for VMware vSphere unterstützen vCenter HA nicht.

====
Um die HA-Funktion nutzen zu können, stellen Sie sicher, dass CPU Hot-Add und Memory Hot-Plug während der Bereitstellung oder in den VM-Einstellungen aktiviert sind.
