---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ONTAP RBAC deployment, custom roles, user configuration, JSON role definition 
summary: Vor der Verwendung von ONTAP tools für VMware vSphere in einer Produktionsumgebung sind die ONTAP RBAC-Überlegungen für ONTAP tools zu berücksichtigen. 
---
= ONTAP RBAC in ONTAP tools für VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools für VMware vSphere unterstützt rollenbasierte Zugriffssteuerung (RBAC) durch ONTAP, wodurch benutzerdefinierte Benutzer und Rollen erstellt werden können, die den Zugriff auf Speicherressourcen einschränken. Das Verständnis des Konfigurationsprozesses und der Berechtigungsstufen erleichtert die Einrichtung geeigneter Zugriffskontrollen, bevor ONTAP tools in einer Produktionsumgebung eingesetzt werden.



[[overview-of-the-configuration-process]]
== Überblick über den Konfigurationsprozess

ONTAP tools for VMware vSphere umfassen Unterstützung für die Erstellung eines ONTAP Benutzers mit einer benutzerdefinierten Rolle.  Die Definitionen sind in einer JSON-Datei verpackt, die Sie in den ONTAP Cluster hochladen können.  Sie können den Benutzer erstellen und die Rolle an Ihre Umgebung und Sicherheitsanforderungen anpassen.

Im folgenden Abschnitt werden die wichtigsten Konfigurationsschritte im Überblick beschrieben. Weitere Details sind unter link:../configure/configure-user-role-and-privileges.html["Konfigurieren Sie ONTAP-Benutzerrollen und -Berechtigungen"] zu finden.

.1. Vorbereiten
Sie müssen über Administratoranmeldeinformationen sowohl für den ONTAP Tools Manager als auch für den ONTAP Cluster verfügen.

.2. Laden Sie die JSON-Definitionsdatei herunter
Nachdem Sie sich bei der Benutzeroberfläche von ONTAP Tools Manager angemeldet haben, können Sie die JSON-Datei mit den RBAC-Definitionen herunterladen.

.3. Erstellen Sie einen ONTAP-Benutzer mit einer Rolle
Nach der Anmeldung bei System Manager können Sie den Benutzer und die Rolle erstellen:

. Wählen Sie *Cluster* auf der linken Seite und dann *Einstellungen*.
. Scrollen Sie nach unten zu *Benutzer und Rollen* und wählen  `-->`.
. Wählen Sie *Add* unter *Users* und wählen Sie *Virtualization products* aus.
. Wählen Sie die JSON-Datei auf Ihrer lokalen Workstation aus, und laden Sie sie hoch.


.4. Konfigurieren Sie die Rolle
Im Rahmen der Definition der Rolle müssen Sie mehrere administrative Entscheidungen treffen. Weitere Informationen finden Sie unter<<Konfigurieren Sie die Rolle mit System Manager>>.



[[configure-the-role-using-system-manager]]
== Konfigurieren Sie die Rolle mit System Manager

Nachdem Sie mit dem Erstellen eines neuen Benutzers und einer neuen Rolle mit System Manager begonnen und die JSON-Datei hochgeladen haben, können Sie die Rolle auf Ihre Umgebung und Ihre Anforderungen abstimmen.



[[core-user-and-role-configuration]]
=== Konfiguration von Kernbenutzern und -Rollen

Die RBAC-Definitionen sind in Form von verschiedenen Produktfunktionen gebündelt, darunter Kombinationen von VSC, VASA Provider und SRA. Wählen Sie die Umgebung oder die Umgebungen aus, in denen die RBAC-Unterstützung benötigt wird. Wenn Rollen beispielsweise die Remote Plug-in-Funktion unterstützen sollen, wählen Sie VSC aus. Außerdem müssen Sie den Benutzernamen und das zugehörige Kennwort auswählen.



[[privileges]]
=== Berechtigungen

Die Rollenberechtigungen sind in vier Gruppen unterteilt, basierend auf dem für ONTAP Storage benötigten Zugriffsniveau. Die den Rollen zugrunde liegenden Berechtigungen umfassen:

* Ermitteln
+
Diese Rolle ermöglicht es Ihnen, Storage-Systeme hinzuzufügen.

* Storage erstellen
+
Mit dieser Rolle können Sie Speicher erstellen. Er umfasst außerdem alle Privileges, die der Erkennungsrolle zugeordnet sind.

* Speicher ändern
+
Mit dieser Rolle können Sie Speicher ändern. Er umfasst auch alle Privileges, die der Ermittlung zugeordnet sind und Storage-Rollen erstellen.

* Zerstören Sie den Speicher
+
Mit dieser Rolle können Sie Speicher zerstören. Sie umfasst auch alle Privileges, die der Ermittlung zugeordnet sind, Speicher erstellen und Speicherrollen ändern.





[[generate-the-user-with-a-role]]
=== Benutzer mit einer Rolle generieren

Nachdem Sie die Konfigurationsoptionen für Ihre Umgebung ausgewählt haben, wählen Sie *Hinzufügen* und ONTAP erstellt den Benutzer und die Rolle. Der Name der generierten Rolle ist eine Verkettung der folgenden Werte:

* In der JSON-Datei definierter konstanter Präfixwert (z.B. „OTV_10“)
* Ausgewählte Produktfunktion
* Liste der Berechtigungssätze.


.Beispiel
`OTV_10_VSC_Discovery_Create`

Der neue Benutzer erscheint in der Liste auf der Seite *Benutzer und Rollen*. Sowohl HTTP- als auch ONTAPI-Benutzeranmeldemethoden werden unterstützt.
