---
sidebar: sidebar 
permalink: automation/api-reference.html 
keywords: ontap tools vmware vsphere rest api reference, api reference 
summary: Die Referenz zu den ONTAP Tools für VMware vSphere 10 REST API enthält Details zu allen API-Aufrufen. Diese Referenz ist bei der Entwicklung von Automatisierungsapplikationen hilfreich. 
---
= API-Referenz für die ONTAP-Tools für VMware vSphere 10 REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Referenz zu den ONTAP Tools für VMware vSphere 10 REST API enthält Details zu allen API-Aufrufen. Diese Referenz ist bei der Entwicklung von Automatisierungsapplikationen hilfreich.

Die ONTAP-Tools für die REST-API-Dokumentation zu VMware vSphere 10 können online über die Swagger-Benutzeroberfläche abgerufen werden. Sie benötigen die IP-Adresse oder den FQDN der ONTAP-Tools für den VMware vSphere 10 Gateway-Dienst sowie den Port.

.Schritte
. Geben Sie die folgende URL in Ihren Browser ein, um die entsprechende IP-Adresse und Port-Kombination für die Variable zu ersetzen, und drücken Sie *Enter*.
+
`\https://$FQDN_IP_PORT/`

+
*Beispiel*

+
`\https://10.61.25.33:8443/`

. Scrollen Sie als Beispiel für einen einzelnen API-Aufruf nach unten in die Kategorie *vCenters* und wählen Sie neben dem Endpunkt *GET* `/virtualization/api/v1/vcenters`

