---
permalink: automation/create-vvol-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: Ein Workflow ist eine Sequenz aus einem oder mehreren Schritten, die zur Ausführung einer bestimmten administrativen Aufgabe oder eines bestimmten Ziels erforderlich sind. 
---
= Erstellung eines VVols Datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen VVols-Datastore mit neuen Volumes oder mit vorhandenen Volumes erstellen. Zudem ist es möglich, einen VVols-Datastore mit einer Kombination aus vorhandenen Volumes und neuen Volumes zu erstellen.


NOTE: Überprüfen Sie, ob die Root-Aggregate nicht der SVM zugeordnet sind.

Generieren Sie ein JWT-Token, bevor Sie Datastores erstellen, oder erhöhen Sie den Ablauf des SAML-Tokens, indem Sie „Maximum Bearer Token Lifetime“ auf 60 m in vCenter festlegen.

Sie müssen x-auth für die API übergeben. Sie können diese X-Auth aus der neuen API generieren, die unter Auth in Swagger hinzugefügt wurde.

/Virtualization/API/v1/auth/vcenter-Login

. Erstellung eines VVols-Datastore mit neuem Volume


Abrufen der Aggregat-id, Storage_id(SVM-UUID) mit der ONTAP REST-API
POST /Virtualization/API/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/Datastores

Verwenden Sie den folgenden URI, um den Status zu überprüfen:

+

[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Anforderungskörper für NFS-Datastore

{
   „Name“:„nfsds1“,
   „Protokoll“: „nfs“,
   „Platform_type“: „Aff“,
   „Moref“:„Domain-c8“,
   „Volumes“:[
      {
         „Is_existing“:false,
         „Name“:„vol_nfs_pvt“,
         „Size_in_mb“:2048000,
         „Space_Efficiency“: „Thin“,
         „Aggregate“:{
            „id“: „D7078b3c-3827-4ac9-9273-0a32909455c2“
         },
         „qos“:{
            „Min_iops“:200,
            „max_iops“:5000
         }
      }
   ],
   „Storage_Backend“:{
      „Storage_id“:„654c67bc-0f75-11ee-8a8c-00a09860a3ff“
   }
}

Anforderungskörper für iSCSI-Datastore:
{
   „Name“ : „iscsi_Custom“,
   „Protokoll“ : „iscsi“,
   „Platform_type“: „AFF“,
   "Moref" : "Domain-c8",
   "Bände" : [
       {
           „Is_existing“ : false,
           „Name“ : „iscsi_Custom“,
           „Size_in_mb“ : 8034,
           "Space_efficiency" : "Thin",
           "Aggregat" : {
               „id“: „54fe5dd4-e461-49c8-bb2d-6d62c5d75af2“
           }
       }
   ],
   „Custom_igroup_Name“: „Igroup1“,
   „Storage_Backend“: {
                       „Storage_id“: „Eb9d33ab-1960-11ee-9506-00a0985c6d9b“ }
}
. VVols-Datastore mit vorhandenen Volumes erstellen

Erhalten Sie „Aggregate_id“ und „Volume_id“ mit der ONTAP-REST-API.

 POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
Text Anfordern

....
 {
"name" : "nfsds2",
"protocol" : "nfs",
"platform_type": "aff",
"moref" : "domain-c8",
"volumes" : [
    {
          "is_existing": true,
          "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
        }
],
"storage_backend": {
                    "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
....
}
