---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Fügen Sie vCenter Server-Instanzen zu den ONTAP-Tools für VMware vSphere hinzu, um Ihre virtuellen Datastores in Ihrer vCenter Server-Umgebung zu konfigurieren, zu managen und zu sichern. 
---
= vCenter Server-Instanzen zu ONTAP -Tools hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fügen Sie vCenter Server-Instanzen zu den ONTAP-Tools für VMware vSphere hinzu, um Ihre virtuellen Datastores in Ihrer vCenter Server-Umgebung zu konfigurieren, zu managen und zu sichern. Wenn Sie mehrere vCenter Server-Instanzen hinzufügen, sind für die sichere Kommunikation zwischen ONTAP-Tools und jedem vCenter Server benutzerdefinierte CA-Zertifikate erforderlich.

.Über diese Aufgabe
ONTAP -Tools lassen sich in vCenter Server integrieren, um Speicheraufgaben wie Bereitstellung, Snapshots und Datenschutz direkt vom vSphere-Client aus durchzuführen.

.Bevor Sie beginnen
* Stellen Sie sicher, dass das vCenter Server-Zertifikat eine gültige Subject Alternative Name (SAN)-Erweiterung mit sowohl DNS- als auch IP-Adresseinträgen enthält. Zum Beispiel:
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
Wenn das Zertifikat keine SAN-Erweiterung enthält oder die SAN-Erweiterung nicht die korrekten DNS- oder IP-Adresswerte enthält, können ONTAP tools-Operationen aufgrund von Zertifikatvalidierungsfehlern fehlschlagen.

* Die primäre Netzwerkkennung (PNID) des vCenter Server muss in den SAN-Details enthalten sein. Die PNID und der DNS-Name müssen identisch und im DNS auflösbar sein.
* Es wird empfohlen, den vCenter Server unter Verwendung seines vollqualifizierten Domainnamens (FQDN) bereitzustellen und sicherzustellen, dass der SAN im Zertifikat DNS Name=machine_FQDN enthält, um optimale Kompatibilität und Unterstützung zu gewährleisten.
* Weitere Informationen finden Sie in der VMware-Dokumentation:
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html["vSphere Certificate Requirements für verschiedene Lösungswege"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["Ersetzen Sie das vCenter-Maschinen-SSL-Zertifikat durch ein benutzerdefiniertes, von einer Zertifizierungsstelle signiertes Zertifikat"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["Fehler: Das Feld „Subject Alternate Name (SAN)“ enthält keine PNID. Bitte geben Sie ein gültiges Zertifikat an."]




[NOTE]
====
Falls kein FQDN verfügbar ist, können Sie die PNID auf die IP-Adresse setzen und die IP-Adresse in das SAN einbinden. Dies wird jedoch von VMware nicht empfohlen.

====
.Schritte
. Öffnen Sie einen Webbrowser und rufen Sie die URL auf: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *vCenters* > *Add*, um die vCenter Server-Instanzen zu integrieren. Geben Sie die vCenter-IP-Adresse oder den Hostnamen, den Benutzernamen, das Kennwort und die Portdetails an.
. Rufen Sie in den erweiterten Optionen das vCenter Server-Zertifikat automatisch ab (autorisieren Sie es) oder laden Sie es manuell hoch.
+

NOTE: Sie benötigen kein Administratorkonto, um vCenter Instanzen zu ONTAP Tools hinzuzufügen. Sie können eine benutzerdefinierte Rolle ohne Administratorkonto mit eingeschränkten Berechtigungen erstellen. Weitere Informationen finden Sie unter link:../concepts/rbac-vcenter-use.html["Nutzen Sie die RBAC für vCenter Server mit ONTAP Tools für VMware vSphere 10"] .



Das Hinzufügen einer vCenter Server-Instanz zu ONTAP Tools löst automatisch die folgenden Aktionen aus:

* ONTAP -Tools registrieren das vCenter-Client-Plug-In als Remote-Plug-In.
* Benutzerdefinierte Privileges für die Plug-ins und APIs werden auf die vCenter Server Instanz angewendet.
* Zum Verwalten der Benutzer werden benutzerdefinierte Rollen erstellt.
* Das Plug-in wird als Verknüpfung auf der vSphere-Benutzeroberfläche angezeigt.

