---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords: add storage backend, ONTAP tools storage backend, local and global storage backend, MetroCluster storage backend 
summary: Speicher-Backends können lokal für eine vCenter-Instanz oder global für die clusterweite Erkennung in ONTAP tools hinzugefügt und verwaltet werden. 
---
= Fügen Sie ein Speicher-Backend zu ONTAP tools hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP tools für VMware vSphere lassen sich Storage-Backends für Ihre ESXi-Hosts hinzufügen und verwalten, einschließlich des Onboardings von Clustern oder SVMs, der Aktivierung von MetroCluster Unterstützung und der Validierung von Zertifikaten für eine sichere Konnektivität. Die Konfiguration von Storage-Backends ist mit ONTAP tools Manager oder dem vSphere Client möglich, der Zertifikatsstatus kann überwacht und Ressourcen nach Clusteränderungen manuell erneut erkannt werden.

Um ein lokales Speicher-Backend hinzuzufügen, verwenden Sie Cluster- oder SVM-Anmeldeinformationen in der ONTAP -Tools-Oberfläche.  Lokale Speicher-Backends stehen nur dem ausgewählten vCenter Server zur Verfügung. ONTAP -Tools ordnen SVMs dem vCenter Server für die Verwaltung von vVols oder VMFS-Datenspeichern zu.  Für VMFS-Datenspeicher und SRA-Workflows können Sie SVM-Anmeldeinformationen verwenden, ohne einen Cluster global zuzuordnen.

Zum Hinzufügen eines globalen Storage-Backends werden ONTAP Cluster-Anmeldeinformationen im ONTAP tools Manager verwendet. Globale Storage-Backends ermöglichen Erkennungs-Workflows zur Identifizierung der für die vVols Verwaltung erforderlichen Clusterressourcen. In mandantenfähigen Umgebungen kann ein SVM-Benutzer lokal hinzugefügt werden, um vVols Datenspeicher zu verwalten.

Weitere Informationen zu globalen und lokalen Speichersystemen finden Sie im KB-Artikel: https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_10_What_is_storage_backend_global_and_local_scope["OTV 10: Was ist der globale und lokale Gültigkeitsbereich des Storage-Backends"^].

Wenn die NetApp MetroCluster Unterstützung in ONTAP aktiviert ist, werden sowohl Quell- als auch Zielcluster als lokale oder globale Storage-Backends eingebunden.

.Bevor Sie beginnen
Überprüfen Sie, ob das Zertifikat ein gültiges Feld „Subject Alternative Name“ (SAN) enthält.  ONTAP -Systeme verwenden das SAN-Feld, um Cluster- und SVM-Management-LIFs zu identifizieren.

[role="tabbed-block"]
====
.Verwenden des ONTAP Tools Managers
--

NOTE: In einer mandantenfähigen Einrichtung können Sie ein Storage-Back-End-Cluster global und eine lokale SVM hinzufügen, um die SVM-Benutzeranmeldedaten zu verwenden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Fügen Sie das Speicher-Back-End hinzu und geben Sie die IP-Adresse oder den FQDN, den Benutzernamen und das Kennwort des Servers an.
+

NOTE: IPv4- und IPv6-Adressenmanagement-LIFs werden unterstützt.

. Rufen Sie die ONTAP Cluster-Zertifikate automatisch ab und autorisieren Sie das Zertifikat oder laden Sie es manuell hoch, indem Sie zu seinem Speicherort navigieren.
+

NOTE: Bei Bedarf können Sie die SAN-Validierung (Subject Alternative Name) über die Wartungskonsole deaktivieren. Anweisungen hierzu finden Sie unterlink:../manage/change-valid-flag.html["Zertifikatvalidierungsflag ändern"] .

. Wenn das von Ihnen hinzugefügte Speicher-Backend Teil einer MetroCluster -Konfiguration ist, zeigt der ONTAP Tools Manager eine Popup-Meldung zum Hinzufügen des Peered-Clusters an.  Wählen Sie *Hinzufügen* und geben Sie die Details für das MetroCluster Peer-Storage-Backend ein.
+

NOTE: Nachdem das ONTAP -System ein Switchover und Switchback durchgeführt hat, führen Sie die Erkennung der ONTAP Tools manuell aus.



--
.Die vSphere-Client-Benutzeroberfläche wird verwendet
--

NOTE: vVols -Datenspeicher unterstützen nicht das direkte Hinzufügen eines SVM-Benutzers über die Benutzeroberfläche des vSphere-Clients.

. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Fügen Sie das Speicher-Back-End hinzu, und geben Sie die IP-Adresse, den Benutzernamen, das Kennwort und die Portdetails des Servers an.
+

NOTE: Sie können ein Speicher-Backend mithilfe clusterbasierter Anmeldeinformationen mit IPv4- oder IPv6-Verwaltungs-LIFs hinzufügen.  Um einen SVM-Benutzer direkt hinzuzufügen, geben Sie SVM-basierte Anmeldeinformationen zusammen mit einem SVM-Verwaltungs-LIF an.  Wenn ein Cluster bereits integriert ist, können Sie keinen SVM-Benutzer aus diesem Cluster erneut integrieren.

. Rufen Sie die ONTAP Cluster-Zertifikate automatisch ab und autorisieren Sie das Zertifikat oder laden Sie es manuell hoch, indem Sie zu seinem Speicherort navigieren.
. Wenn das hinzugefügte Speicher-Backend Teil der MetroCluster -Konfiguration ist, zeigen die ONTAP Tools den Bildschirm * MetroCluster Peer hinzufügen* an.  Wählen Sie *Peer hinzufügen*, um das Peer-Speicher-Backend hinzuzufügen.
+

NOTE: Nachdem das ONTAP -System ein Switchover und Switchback durchgeführt hat, führen Sie die Erkennung der ONTAP Tools manuell aus.



--
====
ONTAP tools listet das neu hinzugefügte Storage Backend auf der Seite *Storage backends* auf. Läuft ein Zertifikat in 30 Tagen oder weniger ab, zeigt ONTAP tools eine Warnung in der Spalte für das Ablaufdatum des Zertifikats an. Nach Ablauf markiert ONTAP tools das Storage Backend als unbekannt, da keine Verbindung zum Storage System hergestellt werden kann.

.Verwandte Informationen
https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_10_What_is_storage_backend_global_and_local_scope["OTV 10: Was ist der globale und lokale Gültigkeitsbereich des Storage-Backends"^]

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["Konfigurieren der Cluster in einer MetroCluster -Konfiguration"]
