---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords: add vCenter Server, ONTAP tools vCenter registration, multiple vCenter support, vCenter CA certificate 
summary: Fügen Sie vCenter Server-Instanzen zu ONTAP tools hinzu, um Datenspeicher zu konfigurieren, zu verwalten und zu schützen. 
---
= vCenter Server-Instanzen zu ONTAP -Tools hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fügen Sie vCenter Server-Instanzen zu ONTAP tools for VMware vSphere hinzu, um Datenspeicher in Ihrer vCenter Server-Umgebung zu konfigurieren, zu verwalten und zu schützen. Beim Hinzufügen mehrerer vCenter Server-Instanzen werden benutzerdefinierte CA-Zertifikate für die sichere Kommunikation zwischen ONTAP tools for VMware vSphere und jeder vCenter Server-Instanz konfiguriert.

.Über diese Aufgabe
ONTAP -Tools lassen sich in vCenter Server integrieren, um Speicheraufgaben wie Bereitstellung, Snapshots und Datenschutz direkt vom vSphere-Client aus durchzuführen.

Das Hinzufügen einer vCenter Server-Instanz zu ONTAP Tools löst automatisch die folgenden Aktionen aus:

* ONTAP -Tools registrieren das vCenter-Client-Plug-In als Remote-Plug-In.
* ONTAP tools wendet benutzerdefinierte Privileges für die Plug-ins und APIs auf die vCenter Serverinstanz an.
* ONTAP tools erstellt benutzerdefinierte Rollen zur Verwaltung der Benutzer.
* Das Plug-in wird als Verknüpfung auf der vSphere-Benutzeroberfläche angezeigt.


.Bevor Sie beginnen
* Stellen Sie sicher, dass das vCenter Server-Zertifikat eine gültige Subject Alternative Name (SAN)-Erweiterung mit sowohl DNS- als auch IP-Adresseinträgen enthält. Zum Beispiel:
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
Wenn das Zertifikat keine SAN-Erweiterung enthält oder die SAN-Erweiterung nicht die korrekten DNS- oder IP-Adresswerte enthält, können ONTAP tools-Operationen aufgrund von Zertifikatvalidierungsfehlern fehlschlagen.

* Die primäre Netzwerkkennung (PNID) des vCenter Server muss in den SAN-Details enthalten sein. Die PNID und der DNS-Name müssen identisch und im DNS auflösbar sein.
* Die Bereitstellung des vCenter Servers sollte unter Verwendung seines vollqualifizierte Domain Namens (FQDN) erfolgen, wobei sichergestellt werden muss, dass der SAN im Zertifikat DNS Name=machine_FQDN enthält, um optimale Kompatibilität und Unterstützung zu gewährleisten.
* Weitere Informationen finden Sie in der VMware-Dokumentation:
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates/certificate-requirements-for-different-solution-paths.html["vSphere Certificate Requirements für verschiedene Lösungswege"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["Ersetzen Sie das vCenter-Maschinen-SSL-Zertifikat durch ein benutzerdefiniertes, von einer Zertifizierungsstelle signiertes Zertifikat"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["Fehler: Das Feld „Subject Alternate Name (SAN)“ enthält keine PNID. Bitte geben Sie ein gültiges Zertifikat an."]




[NOTE]
====
Falls kein FQDN verfügbar ist, kann die PNID auf die IP-Adresse gesetzt und diese IP-Adresse in das SAN eingebunden werden. VMware empfiehlt diese Konfiguration jedoch nicht.

====
.Schritte
. Öffnen Sie einen Webbrowser und rufen Sie die URL auf: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *vCenters* > *Add*, um die vCenter Server-Instanzen zu integrieren. Geben Sie die vCenter-IP-Adresse oder den Hostnamen, den Benutzernamen, das Kennwort und die Portdetails an.
. Rufen Sie in den erweiterten Optionen das vCenter Server-Zertifikat automatisch ab (autorisieren Sie es) oder laden Sie es manuell hoch.
+

NOTE: Sie benötigen kein Administratorkonto, um vCenter-Instanzen zu ONTAP tools hinzuzufügen. Eine benutzerdefinierte Rolle mit eingeschränkten Berechtigungen kann ohne Administratorkonto erstellt werden. Weitere Einzelheiten sind unter link:../concepts/rbac-vcenter-use.html["Nutzen Sie die RBAC für vCenter Server mit ONTAP Tools für VMware vSphere 10"] zu finden.


