---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Verknüpfen Sie ein Storage-Backend mit dem vCenter Server, um eine Zuordnung zwischen dem Storage-Backend und der eingeboard vCenter Server Instanz global zu erstellen. 
---
= Verknüpfen Sie ein Storage-Backend mit einer vCenter Server-Instanz in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ordnen Sie einer vCenter Server-Instanz ein Speicher-Backend zu, um den Zugriff für alle vCenter Server-Instanzen zu ermöglichen.  Stellen Sie bei der MetroCluster -Konfiguration sicher, dass Sie beim Zuordnen eines Storage-Backend-Clusters auch dessen Peer-Cluster mit dem vCenter Server zuordnen.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Randleiste vCenter aus.
. Wählen Sie die vertikalen Auslassungspunkte neben der vCenter Server-Instanz aus, die Sie mit den Speicher-Backends verbinden möchten.
. Wählen Sie aus dem Dropdown-Menü das Speicher-Backend aus, das Sie mit der ausgewählten vCenter Server-Instanz verknüpfen möchten.

