---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords: associate storage backend, ONTAP tools backend mapping, global storage backend association, vCenter storage backend 
summary: Ein globales Storage-Backend wird mit einer vCenter Server-Instanz in ONTAP tools verknüpft. 
---
= Verknüpfen Sie ein Storage-Backend mit einer vCenter Server-Instanz in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dieser Aufgabe kann ein globales Speicher-Backend mit einer vCenter Server-Instanz verknüpft werden. Ein globales Speicher-Backend ist ein Backend, das im ONTAP tools Manager hinzugefügt wurde und noch keiner bestimmten vCenter Server-Instanz zugeordnet ist. Für NetApp MetroCluster Konfigurationen sollte beim Verknüpfen eines Speicher-Backend-Clusters auch dessen Peer-Cluster mit dem vCenter Server verknüpft werden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Randleiste vCenter aus.
. Wählen Sie die vertikale Ellipse neben der vCenter Serverinstanz aus, die mit den Storage-Backends verbunden werden soll.
. Wählen Sie aus dem Dropdown-Menü das Speicher-Backend aus, das Sie mit der ausgewählten vCenter Server-Instanz verknüpfen möchten.

