---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für VMware vSphere überprüft und setzt die Multipathing-Einstellungen für den ESXi Host und die HBA-Zeitüberschreitungseinstellungen, die für NetApp Storage-Systeme am besten geeignet sind. 
---
= Konfigurieren Sie ESXi-Hosteinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Konfiguration der Multipath- und Timeout-Einstellungen des ESXi-Servers können Sie die Datenverfügbarkeit und -integrität aufrechterhalten.  Es ermöglicht ein automatisches Failover auf einen Backup-Speicherpfad, wenn der primäre Pfad nicht mehr verfügbar ist.



== Konfigurieren Sie die Multipath- und Timeout-Einstellungen des ESXi-Servers

Die ONTAP Tools für VMware vSphere prüfen und legen die Multipath-Einstellungen für ESXi Hosts und die HBA-Zeitüberschreitungseinstellungen fest, die für NetApp Storage-Systeme am besten geeignet sind.

.Über diese Aufgabe
Dieser Vorgang kann je nach Konfiguration und Systemauslastung einige Zeit in Anspruch nehmen.  Sie können den Fortschritt im Bereich „Letzte Aufgaben“ anzeigen.

.Schritte
. Wählen Sie auf der VMware vSphere Web Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie auf der Seite Verknüpfungen des VMware vSphere Web-Clients im Abschnitt Plug-ins *NetApp ONTAP-Tools* aus.
. Gehen Sie in der Übersicht (Dashboard) der ONTAP Tools für VMware vSphere Plug-in zur *ESXi Host Compliance* Karte.
. Wählen Sie den Link *Empfohlene Einstellungen anwenden*.
. Wählen Sie im Fenster *Empfohlene Hosteinstellungen anwenden* die Hosts aus, die Sie aktualisieren möchten, um die empfohlenen NetApp -Einstellungen zu verwenden, und wählen Sie *Weiter*.
+

NOTE: Sie können den ESXi-Host erweitern, um die aktuellen Werte anzuzeigen.

. Wählen Sie auf der Einstellungsseite die empfohlenen Werte nach Bedarf aus.
. Überprüfen Sie im Übersichtsfenster die Werte und wählen Sie *Fertig stellen*. Sie können den Fortschritt im Fenster „Letzte Aufgabe“ verfolgen.




== Legen Sie ESXi-Hostwerte fest

Verwenden Sie ONTAP tools for VMware vSphere, um Timeouts und andere Werte auf ESXi-Hosts für optimale Leistung und Failover festzulegen.  Diese Werte werden auf Grundlage von NetApp -Tests festgelegt.

Auf einem ESXi-Host können Sie die folgenden Werte festlegen:



=== HBA/CNA-Adaptereinstellungen

Setzt die folgenden Parameter auf Standardwerte:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Emulex FC-HBA-Zeitüberschreitungen
* QLogic FC-HBA-Zeitüberschreitungen




=== MPIO-Einstellungen

MPIO-Einstellungen wählen die besten Pfade für NetApp -Speichersysteme aus.  Wählen Sie in den MPIO-Einstellungen den besten Pfad aus und verwenden Sie ihn.

Passen Sie für Hochleistungsumgebungen oder beim Testen mit einem einzelnen LUN-Datenspeicher die Lastausgleichseinstellung der Round-Robin-Pfadauswahlrichtlinie (VMW_PSP_RR) an, um die Leistung zu verbessern.  Setzen Sie den Standard-IOPS-Wert von 1000 auf 1.


NOTE: Die MPIO-Einstellungen gelten nicht für die Protokolle NVMe, NVMe/FC und NVMe/TCP.



=== NFS-Einstellungen

|===


| Parameter | Wert festlegen auf... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024MB 


| MaxVolumes: NFS | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 oder höher 


| NFS.HeartbeatMaxFailures | 10 


| HeartbeatFrequency NFS.HeartbeatFrequency | 12 


| HeartbeatTimeout NFS.HeartbeatTimeout | 5 
|===