---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Wenn Sie den Netzwerkzugriff noch nicht konfiguriert haben, werden standardmäßig alle vom ESXi-Host ermittelten IP-Adressen zur Exportrichtlinie hinzugefügt. 
---
= Konfigurieren Sie den Netzwerkzugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sofern kein Netzwerkzugriff konfiguriert wurde, werden alle vom ESXi-Host ermittelten IP-Adressen automatisch in die Exportrichtlinie aufgenommen.  Sie können die Richtlinie so konfigurieren, dass nur bestimmte IP-Adressen zugelassen und andere ausgeschlossen werden. Wenn Sie jedoch versuchen, von einem ausgeschlossenen ESXi-Host aus zu mounten, schlägt der Vorgang fehl.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie *NetApp ONTAP Tools* auf der Shortcuts-Seite unter dem Plug-ins-Bereich.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Einstellungen* > *Netzwerkzugriff verwalten* > *Bearbeiten*.
+
Um mehrere IP-Adressen hinzuzufügen, trennen Sie die Liste durch Kommas, Bereich, klassenloses Inter-Domain Routing (CIDR) oder eine Kombination aller drei.

. Wählen Sie *Speichern*.

