---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Wenn Sie den Netzwerkzugriff noch nicht konfiguriert haben, werden standardmäßig alle vom ESXi-Host ermittelten IP-Adressen zur Exportrichtlinie hinzugefügt. 
---
= Konfigurieren Sie Netzwerkzugriff in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig werden alle vom ESXi-Host ermittelten IP-Adressen automatisch zur Exportrichtlinie hinzugefügt, es sei denn, Sie konfigurieren den Netzwerkzugriff.  Sie können die Exportrichtlinie so ändern, dass der Zugriff nur von bestimmten IP-Adressen aus erlaubt ist.  Wenn ein ausgeschlossener ESXi-Host versucht, einen Mount-Vorgang durchzuführen, schlägt der Vorgang fehl.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie *NetApp ONTAP Tools* auf der Shortcuts-Seite unter dem Plug-ins-Bereich.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Einstellungen* > *Netzwerkzugriff verwalten* > *Bearbeiten*.
+
Um mehrere IP-Adressen hinzuzufügen, trennen Sie die Liste durch Kommas, Bereich, klassenloses Inter-Domain Routing (CIDR) oder eine Kombination aller drei.

. Wählen Sie *Speichern*.

