---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: configure network access, ONTAP export policy, ESXi host IP allowlist, ONTAP tools mount access 
summary: Der Netzwerkzugriff wird so konfiguriert, dass gesteuert wird, welche ESXi-Host-IP-Adressen zu Exportrichtlinien in ONTAP tools hinzugefügt werden. 
---
= Konfigurieren Sie Netzwerkzugriff in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig fügt ONTAP tools automatisch alle vom ESXi-Host ermittelten IP-Adressen zur Exportrichtlinie hinzu, es sei denn, Sie konfigurieren Netzwerkzugriff. Die Exportrichtlinie kann so angepasst werden, dass der Zugriff nur von bestimmten IP-Adressen erlaubt ist; Mount-Vorgänge schlagen für ausgeschlossene ESXi-Hosts fehl.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie *NetApp ONTAP tools* auf der Seite mit den Verknüpfungen unter dem Abschnitt „Plug-ins“ aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Einstellungen* > *Netzwerkzugriff verwalten* > *Bearbeiten*.
+
Um mehrere IP-Adressen hinzuzufügen, die Liste mit Kommas, Bereichen, Classless Inter-Domain Routing (CIDR)-Notation oder einer Kombination aus allen drei trennen.

. Wählen Sie *Speichern*.

