---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords: create datastore, ONTAP tools NFS VMFS vVols, host cluster datastore provisioning, nconnect datastore settings 
summary: NFS-, VMFS- oder vVols Datenspeicher in ONTAP tools auf Host- oder Hostcluster-Ebene erstellen. 
---
= Erstellen Sie einen Datenspeicher in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einen NFS-, VMFS- oder vVols Datenspeicher auf Host- oder Hostclusterebene erstellen. Wird ein Datenspeicher auf Hostclusterebene erstellt, mounten die ONTAP tools diesen auf allen Zielhosts, sofern die erforderlichen Privileges vorhanden sind.



[[interoperability-between-native-datastores-and-ontap-tools-managed-datastores]]
== Interoperabilität zwischen nativen Datenspeichern und ONTAP tools verwalteten Datenspeichern

Ab ONTAP tools for VMware vSphere 10.4 erstellen ONTAP Tools verschachtelte igroups für Datenspeicher, wobei übergeordnete igroups spezifisch für Datenspeicher und untergeordnete igroups den Hosts zugeordnet sind.  Sie können flache igroups vom ONTAP System Manager aus erstellen und diese zum Erstellen von VMFS-Datenspeichern verwenden, ohne ONTAP Tools zu verwenden. Siehe https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Verwalten von SAN-Initiatoren und igroups"] für weitere Informationen.

Nachdem Sie den Speicher integriert und die Datenspeichererkennung ausgeführt haben, ändern ONTAP -Tools flache Igroups in VMFS-Datenspeichern in verschachtelte Igroups.  Sie können frühere flache igroups nicht zum Erstellen neuer Datenspeicher verwenden.  Verwenden Sie die ONTAP Tools-Schnittstelle oder die REST-API, um verschachtelte igroups wiederzuverwenden.

[role="tabbed-block"]
====
.Erstellen Sie einen VVols-Datastore
--
Ab ONTAP tools for VMware vSphere 10.3 ist es möglich, einen vVols Datenspeicher auf ASA r2 Systemen mit Thin-Space-Effizienz zu erstellen. Der VASA Provider erstellt beim Anlegen des vVol Datenspeichers einen Container und die gewünschten Protokollendpunkte. Der VASA Provider weist diesem Container keine unterstützenden Volumes zu.

.Bevor Sie beginnen
* Stellen Sie sicher, dass keine Root-Aggregate auf die SVM abgebildet werden.
* Stellen Sie sicher, dass der VASA Provider beim ausgewählten vCenter registriert ist.
* Für ASA r2 Speichersysteme ist keine SVM zu Aggregat Zuordnung erforderlich.


.Schritte
. Melden Sie sich beim vSphere Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datastore erstellen*.
. Wählen Sie vVols als *Datenspeichertyp* aus.
. Geben Sie die Informationen *Datastore Name* und *Protocol* ein.
+

NOTE: Das ASA r2 System unterstützt die iSCSI- und FC-Protokolle für VVols.

. Wählen Sie die Storage-VM aus, auf der der Datastore erstellt werden soll.
. Unter *Erweiterte Optionen*:
+
** Wenn Sie die *Benutzerdefinierte Exportrichtlinie* auswählen, führen Sie die Erkennung in vCenter für alle Objekte durch, bevor Sie fortfahren. NetApp empfiehlt, diese Option nicht zu verwenden.
** Sie können einen *benutzerdefinierten Initiatorgruppen*-Namen für die iSCSI- und FC-Protokolle auswählen.
+

NOTE: Bei einer ASA r2 SVM werden keine Speichereinheiten (LUNs/Namespaces) erstellt, da der Datenspeicher nur ein logischer Container ist.



. Im Bereich *Speicherattribute* können Sie neue Volumes erstellen oder die vorhandenen Volumes verwenden. Sie können diese beiden Volume-Typen jedoch nicht kombinieren, um einen VVols-Datastore zu erstellen.
+
Beim Erstellen eines neuen Volumes können Sie QoS für den Datenspeicher aktivieren. Standardmäßig wird für jede LUN-Erstellungsanforderung ein Volume erstellt. Überspringen Sie diesen Schritt für vVols Datenspeicher auf ASA r2-Speichersystemen.

. Überprüfen Sie Ihre Auswahl im Fenster *Zusammenfassung* und wählen Sie *Fertig stellen*.


--
.Erstellen Sie einen NFS-Datastore
--
Ein NFS-Datenspeicher verbindet ESXi Hosts über das NFS-Protokoll mit gemeinsam genutztem Speicher. Er ist einfach und flexibel, und VMware vSphere Umgebungen verwenden ihn häufig.

.Schritte
. Melden Sie sich beim vSphere Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datenspeicher erstellen*.
. Wählen Sie NFS im Feld *Datastore type* aus.
. Im Bereich *Name und Protokoll* werden der Name, die Größe und die Protokollinformationen des Datenspeichers eingegeben.
+
.. In den *Erweiterten Optionen* *Datenspeichercluster* und *Kerberos-Authentifizierung* auswählen.
+

NOTE: Kerberos-Authentifizierung ist nur verfügbar, wenn das NFS 4.1-Protokoll ausgewählt ist.

.. Geben Sie die *Anzahl der Verbindungen (nconnect)* für den Datenspeicher an. Der Standardwert ist 4, konfigurierbar von 1 bis 8. Wenn der von Ihnen gewählte Wert höher ist als die aktuelle nconnect-Einstellung auf Hostebene, passen die ONTAP tools die nconnect-Einstellung auf Hostebene entsprechend an.


. Im Bereich *Speicher* sind *Plattform* und *Storage-VM* auszuwählen.
. Wenn unter den *Erweiterten Optionen* die *Benutzerdefinierte Exportrichtlinie* ausgewählt wird, erfolgt eine Erkennung in vCenter für alle Objekte, bevor fortgefahren wird.
+

NOTE: Sie können keinen NFS-Datenspeicher mithilfe der Standard- oder Root-Volume-Richtlinie der SVM erstellen.

+
** In den *Erweiterten Optionen* ist die Schaltfläche *Asymmetrisch* nur sichtbar, wenn in der Dropdown-Liste „Plattform“ „Leistung“ oder „Kapazität“ ausgewählt wird. Die Option *Asymmetrisch* gilt jedoch nicht für die Erstellung von NFS-Datenspeichern.
** Wenn im Dropdown-Menü für die Plattform die Option *Beliebig* ausgewählt wird, sind alle SVMs im vCenter sichtbar. Plattform- und asymmetrische Einstellungen haben keinen Einfluss auf die Sichtbarkeit.


. Im Bereich *Speicherattribute* das Aggregat für die Volume-Erstellung auswählen. Unter *Erweiterte Optionen* *Speicherplatzreservierung* und *QoS aktivieren* nach Bedarf auswählen.
. Im Bereich *Zusammenfassung* werden die Auswahlen überprüft und *Fertigstellen* ausgewählt.


ONTAP -Tools erstellen den NFS-Datenspeicher und mounten ihn auf allen Hosts.

--
.Erstellen Sie einen VMFS-Datastore
--
VMFS ist ein Cluster-Dateisystem zum Speichern von Dateien virtueller Maschinen.  Mehrere ESXi-Hosts können für vMotion- und Hochverfügbarkeitsfunktionen gleichzeitig auf dieselben VM-Dateien zugreifen.

.Bevor Sie beginnen
* Aktivieren Sie Services und LIFs für jedes Protokoll auf der ONTAP Storage-Seite.
* Für ASA r2 Speichersysteme ist keine SVM zu Aggregat Zuordnung erforderlich.
* Konfigurieren Sie den ESXi-Host, wenn Sie das NVMe/TCP-Protokoll verwenden:
+
.. Überprüfen Sie die https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware Compatibility Guide"]
+

NOTE: VMware vSphere 7.0 U3 und neuere Versionen unterstützen das NVMe/TCP-Protokoll. VMware vSphere 8.0 und neuere Versionen werden jedoch empfohlen.

.. Es sollte geprüft werden, ob der Hersteller der Netzwerkkarte (NIC) ESXi NICs mit dem NVMe/TCP-Protokoll unterstützt.
.. Richten Sie die ESXi-NIC für NVMe/TCP gemäß den Spezifikationen des NIC-Anbieters ein.
.. Wenn Sie VMware vSphere 7-Version verwenden, befolgen Sie die Anweisungen auf der VMware-Site https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Konfigurieren Sie die VMkernel Bindung für den NVMe over TCP Adapter"], um die NVMe/TCP-Portbindung zu konfigurieren. Wenn Sie VMware vSphere 8 Version verwenden, folgen Sie https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Konfiguration von NVMe over TCP auf ESXi"], um die NVMe/TCP-Portbindung zu konfigurieren.
.. Folgen Sie für VMware vSphere 7 Release den Anweisungen auf Seite https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Aktivieren Sie NVMe over RDMA oder NVMe over TCP-Softwareadapter"], um NVMe/TCP-Softwareadapter zu konfigurieren. Folgen Sie für die Version VMware vSphere 8, https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Fügen Sie Software-NVMe-over-RDMA- oder NVMe-over-TCP-Adapter hinzu"] um die NVMe/TCP-Softwareadapter zu konfigurieren.
.. Führen Sie die link:../configure/discover-storage-systems-and-hosts.html["Erkennen von Storage-Systemen und Hosts"] Aktion auf dem ESXi Host aus. Weitere Informationen finden Sie unter  https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Konfigurieren von NVMe/TCP mit vSphere 8.0 Update 1 und ONTAP 9.13.1 für VMFS-Datenspeicher"].


* Wenn Sie das NVMe/FC-Protokoll verwenden, sind die folgenden Schritte zur Konfiguration des ESXi-Hosts erforderlich:
+
.. Falls NVMe over Fabrics (NVMe-oF) noch nicht aktiviert ist, sollte es auf Ihren ESXi Hosts aktiviert werden.
.. Vollständiges SCSI-Zoning
.. Stellen Sie sicher, dass ESXi-Hosts und das ONTAP-System auf einer physischen und logischen Ebene verbunden sind.




Informationen zum Konfigurieren einer ONTAP SVM für das FC-Protokoll finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Konfigurieren Sie eine SVM für FC"].

Weitere Informationen zur Nutzung des NVMe/FC-Protokolls mit VMware vSphere 8.0 finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["NVMe-of Host-Konfiguration für ESXi 8.x mit ONTAP"].

Weitere Informationen zur Verwendung von NVMe/FC mit VMware vSphere 7.0 sind unter  https://docs.netapp.com/us-en/ontap-sanhost/nvme-esxi-7.html["ONTAP NVMe/FC-Host-Konfigurationsleitfaden"] zu finden.

.Schritte
. Melden Sie sich beim vSphere Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datastore erstellen*.
. Wählen Sie den VMFS-Datenspeichertyp aus.
. Geben Sie im Bereich *Name und Protokoll* den Namen, die Größe und die Protokollinformationen des Datenspeichers ein. Zum Hinzufügen des neuen Datenspeichers zu einem bestehenden VMFS Cluster wird der Datenspeichercluster in den *Erweiterten Optionen* ausgewählt.
. Im Bereich *Speicher* die Storage-VM auswählen. Im Abschnitt *Erweiterte Optionen* bei Bedarf den *Namen der benutzerdefinierten Initiatorgruppe* angeben. Es besteht die Möglichkeit, eine vorhandene Initiatorgruppe für den Datenspeicher auszuwählen oder eine neue Initiatorgruppe mit einem benutzerdefinierten Namen zu erstellen.
+
Bei Auswahl des NVMe/FC- oder NVMe/TCP-Protokolls wird ein neues Namespace-Subsystem erstellt und für die Namespace-Zuordnung verwendet. ONTAP tools erstellt das Namespace-Subsystem mit dem automatisch generierten Namen, der den Datenspeichernamen enthält. Eine Umbenennung des Namespace-Subsystems ist im Feld *Benutzerdefinierter Namespace-Subsystemname* in den *Erweiterten Optionen* des Bereichs *Speicher* möglich.

. Im Bereich *Speicherattribute*:
+
.. Wählen Sie aus den Dropdown-Optionen *Aggregate* aus.
+

NOTE: Für ASA r2 Speichersysteme wird die Option *Aggregate* nicht angezeigt, da der Speicher disaggregiert ist. Bei Auswahl eines ASA r2 Speichersystems vom Typ SVM werden auf der Seite *Storage attributes* Optionen zur Aktivierung von QoS angezeigt.

.. ONTAP -Tools erstellen basierend auf dem ausgewählten Protokoll eine Speichereinheit (LUN/Namespace) mit einer Thin-Space-Reserve.
+

NOTE: Ab ONTAP 9.16.1 unterstützen ASA r2 Storage-Systeme bis zu 12 Nodes pro Cluster.

.. Die *Leistungsstufe* für ein ASA r2 Speichersystem mit einer 12-Knoten-SVM in einem heterogen Cluster auswählen. Diese Option ist nicht verfügbar, wenn die ausgewählte SVM ein homogen Cluster ist oder ein SVM-Benutzer verwendet wird.
+
„Beliebig“ ist der Standard-PSL-Wert (Performance Service Level). Diese Einstellung erstellt die Speichereinheit mithilfe des ONTAP-Algorithmus für die ausgewogene Platzierung. Sie können jedoch nach Bedarf die Option „Performance“ oder „Extreme“ auswählen.

.. Wählen Sie *vorhandenes Volume verwenden*, *QoS*-Optionen nach Bedarf aktivieren und geben Sie die Details an.
+

NOTE: Im ASA r2 Speichertyp gilt die Erstellung oder Auswahl von Volumes nicht für die Erstellung von Speichereinheiten (LUN/Namespace). Daher werden diese Optionen nicht angezeigt.

+

NOTE: Sie können das vorhandene Volume nicht zum Erstellen eines VMFS-Datenspeichers mit NVMe/FC- oder NVMe/TCP-Protokoll verwenden.  Erstellen Sie ein neues Volume für den VMFS-Datenspeicher.



. Im Fenster *Schutz* die Option *Diesen Datenspeicher mithilfe der SnapMirror Replikation schützen* auswählen, um den Schutz zu aktivieren. Der Datenspeicher kann einer bestehenden Schutzgruppe hinzugefügt oder eine neue Schutzgruppe erstellt werden. Eine neue Schutzgruppe kann wie folgt erstellt werden:
+
.. Einen *Schutzgruppennamen* eingeben.
.. Die SnapMirror Beziehung konfigurieren. Bei Auswahl der Automated Failover Duplex Policy (AFD) sind die Host-Cluster-Konfigurationseinstellungen vor dem Fortfahren einzurichten. Einzelheiten finden sich unter link:../protect/config-proximity.html["Cluster für den Datenspeicherschutz mit ONTAP tools konfigurieren"].
+

NOTE: Ist das ausgewählte Volume bereits Teil einer anderen Schutzeinstellung, wird die nächste Schutzseite deaktiviert und eine Informationsmeldung angezeigt. Ist der Datenspeicher nicht für den Schutz geeignet, wird die Schutzoption deaktiviert und der Grund für die Nichteignung angezeigt. Der Datenspeicher kann dennoch ohne Schutz erstellt werden.



. Überprüfen Sie die Datastore-Details im Bereich *Summary* und wählen Sie *Finish*.
+

NOTE: Wenn ein Datenspeicher geschützt ist, mounten die ONTAP tools ihn auf allen Hosts im Cluster.



.Ergebnis
ONTAP -Tools erstellen den VMFS-Datenspeicher und mounten ihn auf allen Hosts.

--
====