---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie einen Datenspeicher auf Hostclusterebene erstellen, mounten ONTAP Tools ihn auf allen Zielhosts und aktivieren die Aktion nur, wenn Sie über die erforderlichen Berechtigungen verfügen. 
---
= Erstellen eines Datenspeichers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Datenspeicher auf Hostclusterebene erstellen, mounten ONTAP Tools ihn auf allen Zielhosts und aktivieren die Aktion nur, wenn Sie über die erforderlichen Berechtigungen verfügen.

*Interoperabilität zwischen nativen Datenspeichern mit vCenter Server und von ONTAP-Tools verwalteten Datenspeichern*

Ab ONTAP tools for VMware vSphere 10.4 erstellen ONTAP Tools verschachtelte igroups für Datenspeicher, wobei übergeordnete igroups spezifisch für Datenspeicher und untergeordnete igroups den Hosts zugeordnet sind.  Sie können flache igroups vom ONTAP System Manager aus erstellen und diese zum Erstellen von VMFS-Datenspeichern verwenden, ohne ONTAP Tools zu verwenden. Siehe https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Verwalten von SAN-Initiatoren und igroups"] für weitere Informationen.

Nachdem Sie den Speicher integriert und die Datenspeichererkennung ausgeführt haben, ändern ONTAP -Tools flache Igroups in VMFS-Datenspeichern in verschachtelte Igroups.  Sie können frühere flache igroups nicht zum Erstellen neuer Datenspeicher verwenden.  Verwenden Sie die ONTAP Tools-Schnittstelle oder die REST-API, um verschachtelte igroups wiederzuverwenden.

[role="tabbed-block"]
====
.Erstellen Sie einen VVols-Datastore
--
Ab den ONTAP tools for VMware vSphere 10.3 können Sie einen vVols Datenspeicher auf ASA R2-Systemen mit platzsparender Speicherkapazität als thin.vVol erstellen.  Der VASA-Anbieter erstellt beim Erstellen des vVol-Datenspeichers einen Container und die gewünschten Protokollendpunkte.  Der VASA-Anbieter weist diesem Container keine Sicherungsvolumes zu.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Root-Aggregate nicht auf SVM abgebildet sind.
* Stellen Sie sicher, dass der VASA Provider beim ausgewählten vCenter registriert ist.
* Im ASA R2-Speichersystem sollte die SVM dem Aggregat für den SVM-Benutzer zugeordnet werden.


.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datastore erstellen*.
. Wählen Sie VVols *Datenspeichertyp* aus.
. Geben Sie die Informationen *Datastore Name* und *Protocol* ein.
+

NOTE: Das ASA r2 System unterstützt die iSCSI- und FC-Protokolle für VVols.

. Wählen Sie die Storage-VM aus, auf der der Datastore erstellt werden soll.
. Unter Erweiterte Optionen:
+
** Wenn Sie die *Benutzerdefinierte Exportrichtlinie* auswählen, stellen Sie sicher, dass Sie die Erkennung in vCenter für alle Objekte ausführen.  Es wird empfohlen, diese Option nicht zu verwenden.
** Sie können für die iSCSI- und FC-Protokolle *Custom Initiator Group*-Name auswählen.
+

NOTE: Im ASA R2-Speichersystemtyp SVM werden keine Speichereinheiten (LUN/Namespace) erstellt, da der Datenspeicher nur ein logischer Container ist.



. Im Bereich *Speicherattribute* können Sie neue Volumes erstellen oder die vorhandenen Volumes verwenden. Sie können diese beiden Volume-Typen jedoch nicht kombinieren, um einen VVols-Datastore zu erstellen.
+
Beim Erstellen eines neuen Volumes können Sie QoS im Datenspeicher aktivieren.  Standardmäßig wird für jede LUN-Erstellungsanforderung ein Volume erstellt.  Überspringen Sie diesen Schritt für vVols -Datenspeicher auf ASA R2-Speichersystemen.

. Überprüfen Sie Ihre Auswahl im Fenster *Zusammenfassung* und wählen Sie *Fertig stellen*.


--
.Erstellen Sie einen NFS-Datastore
--
Ein NFS-Datenspeicher verbindet ESXi-Hosts über das NFS-Protokoll mit gemeinsam genutztem Speicher.  Sie sind einfach und flexibel und werden in VMware vSphere-Umgebungen verwendet.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datenspeicher erstellen*.
. Wählen Sie NFS im Feld *Datastore type* aus.
. Geben Sie den Namen, die Größe und die Protokollinformationen des Datastore im Bereich *Name und Protokoll* ein. Wählen Sie in den erweiterten Optionen *Datastore Cluster* und *Kerberos-Authentifizierung* aus.
+

NOTE: Kerberos-Authentifizierung ist nur verfügbar, wenn das NFS 4.1-Protokoll ausgewählt ist.

. Wählen Sie *Plattform* und *Storage VM* im Bereich *Storage* aus.
. Wenn Sie unter den erweiterten Optionen *Benutzerdefinierte Exportrichtlinie* auswählen, führen Sie die Erkennung in vCenter für alle Objekte aus.  Es wird empfohlen, diese Option nicht zu verwenden.
+

NOTE: Sie können keinen NFS-Datenspeicher mithilfe der Standard- oder Root-Volume-Richtlinie der SVM erstellen.

+
** In den erweiterten Optionen ist die Umschalttaste *Asymmetric* nur sichtbar, wenn Leistung oder Kapazität in der Dropdown-Liste Plattform ausgewählt ist.
** Wenn Sie im Plattform-Dropdown-Menü die Option *Beliebig* auswählen, können Sie alle SVMs im vCenter sehen.  Plattform und asymmetrische Flagge beeinträchtigen die Sicht nicht.


. Wählen Sie im Bereich *Speicherattribute* das Aggregat für die Volume-Erstellung aus. Wählen Sie in den erweiterten Optionen je nach Bedarf *Space Reserve* und *Enable QoS* aus.
. Überprüfen Sie die Auswahl im Fenster *Zusammenfassung* und wählen Sie *Fertig stellen*.


ONTAP -Tools erstellen den NFS-Datenspeicher und mounten ihn auf allen Hosts.

--
.Erstellen Sie einen VMFS-Datastore
--
VMFS ist ein Cluster-Dateisystem zum Speichern von Dateien virtueller Maschinen.  Mehrere ESXi-Hosts können für vMotion- und Hochverfügbarkeitsfunktionen gleichzeitig auf dieselben VM-Dateien zugreifen.

In einem geschützten Cluster:

* Sie können nur VMFS-Datenspeicher erstellen.  Durch das Hinzufügen eines VMFS-Datenspeichers zu einem geschützten Cluster wird dieser automatisch geschützt.
* Sie können keinen Datastore in einem Rechenzentrum mit einem oder mehreren geschützten Host-Clustern erstellen.
* Sie können keinen Datenspeicher auf einem ESXi-Host erstellen, wenn der übergeordnete Hostcluster durch eine „Automated Failover Duplex Policy“ (einheitliche oder nicht einheitliche Konfiguration) geschützt ist.
* Sie können einen VMFS-Datastore nur auf einem ESXi-Host erstellen, der durch eine asynchrone Beziehung geschützt ist. Sie können keinen Datastore auf einem ESXi-Host erstellen und mounten, der Teil eines Host-Clusters ist, der durch die Richtlinie „Automatischer Failover-Duplex“ geschützt ist.


.Bevor Sie beginnen
* Aktivieren Sie Services und LIFs für jedes Protokoll auf der ONTAP Storage-Seite.
* SVM-Aggregat für SVM-Benutzer im ASA r2 Storage-System zuordnen
* Konfigurieren Sie den ESXi-Host, wenn Sie das NVMe/TCP-Protokoll verwenden:
+
.. Überprüfen Sie die https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware Compatibility Guide"]
+

NOTE: VMware vSphere 7.0 U3 und neuere Versionen unterstützen das NVMe/TCP-Protokoll. VMware vSphere 8.0 und neuere Versionen werden jedoch empfohlen.

.. Überprüfen Sie, ob der Anbieter der Netzwerkschnittstellenkarte (NIC) ESXi NIC mit dem NVMe/TCP-Protokoll unterstützt.
.. Richten Sie die ESXi-NIC für NVMe/TCP gemäß den Spezifikationen des NIC-Anbieters ein.
.. Wenn Sie VMware vSphere 7-Version verwenden, befolgen Sie die Anweisungen auf der VMware-Site https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Konfigurieren Sie die VMkernel Bindung für den NVMe over TCP Adapter"], um die NVMe/TCP-Portbindung zu konfigurieren. Wenn Sie VMware vSphere 8 Version verwenden, folgen Sie https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Konfiguration von NVMe over TCP auf ESXi"], um die NVMe/TCP-Portbindung zu konfigurieren.
.. Folgen Sie für VMware vSphere 7 Release den Anweisungen auf Seite https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Aktivieren Sie NVMe over RDMA oder NVMe over TCP-Softwareadapter"], um NVMe/TCP-Softwareadapter zu konfigurieren. Folgen Sie für die Version VMware vSphere 8, https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Fügen Sie Software-NVMe-over-RDMA- oder NVMe-over-TCP-Adapter hinzu"] um die NVMe/TCP-Softwareadapter zu konfigurieren.
.. Führen Sie link:../configure/discover-storage-systems-and-hosts.html["Erkennen von Storage-Systemen und Hosts"]eine Aktion auf dem ESXi-Host aus. Weitere Informationen finden Sie unter https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Konfigurieren von NVMe/TCP mit vSphere 8.0 Update 1 und ONTAP 9.13.1 für VMFS-Datenspeicher"].


* Wenn Sie das NVME/FC-Protokoll verwenden, führen Sie die folgenden Schritte aus, um den ESXi-Host zu konfigurieren:
+
.. Falls noch nicht aktiviert, aktivieren Sie NVMe over Fabrics (NVMe-of) auf Ihren ESXi Hosts.
.. Vollständiges SCSI-Zoning
.. Stellen Sie sicher, dass ESXi-Hosts und das ONTAP-System auf einer physischen und logischen Ebene verbunden sind.




Informationen zum Konfigurieren einer ONTAP SVM für das FC-Protokoll finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Konfigurieren Sie eine SVM für FC"].

Weitere Informationen zur Nutzung des NVMe/FC-Protokolls mit VMware vSphere 8.0 finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["NVMe-of Host-Konfiguration für ESXi 8.x mit ONTAP"].

Weitere Informationen zur Verwendung von NVMe/FC mit VMware vSphere 7.0 finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["ONTAP NVMe/FC-Host-Konfigurationsleitfaden"] und http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"].

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datastore erstellen*.
. Wählen Sie den VMFS-Datastore-Typ aus.
. Geben Sie im Bereich „Name und Protokoll“ den Namen, die Größe und die Protokollinformationen des Datenspeichers ein.  Um den neuen Datenspeicher zu einem vorhandenen VMFS-Cluster hinzuzufügen, wählen Sie den Datenspeicher-Cluster in den erweiterten Optionen aus.
. Wählen Sie Speicher-VM im Bereich *Speicher* aus. Geben Sie den *Custom Initiator Group Name* im Abschnitt *Advanced options* nach Bedarf an. Sie können eine vorhandene Initiatorgruppe für den Datastore auswählen oder eine neue Initiatorgruppe mit einem benutzerdefinierten Namen erstellen.
+
Wenn das NVMe/FC- oder NVMe/TCP-Protokoll ausgewählt wird, wird ein neues Namespace-Subsystem erstellt und für die Namespace-Zuordnung verwendet.  ONTAP -Tools erstellen das Namespace-Subsystem mithilfe des automatisch generierten Namens, der den Datenspeichernamen enthält.  Sie können das Namespace-Subsystem im Feld *Benutzerdefinierter Namespace-Subsystemname* in den erweiterten Optionen des Bereichs *Speicher* umbenennen.

. Im Bereich *Storage attributes*:
+
.. Wählen Sie aus den Dropdown-Optionen *Aggregate* aus.
+

NOTE: Bei ASA r2-Speichersystemen wird die Option *Aggregat* nicht angezeigt, da der Speicher disaggregiert ist. Wenn Sie einen ASA R2-Speichersystemtyp „SVM“ auswählen, werden auf der Seite mit den Speicherattributen die Optionen zum Aktivieren von QoS angezeigt.

.. ONTAP -Tools erstellen basierend auf dem ausgewählten Protokoll eine Speichereinheit (LUN/Namespace) mit einer Thin-Space-Reserve.
+

NOTE: Ab ONTAP 9.16.1 unterstützen ASA r2 Storage-Systeme bis zu 12 Nodes pro Cluster.

.. Wählen Sie das *Performance Service Level* für ASA r2 Speichersysteme mit 12 Knoten SVM, die ein heterogener Cluster ist. Diese Option ist nicht verfügbar, wenn die ausgewählte SVM ein homogenes Cluster ist oder einen SVM-Benutzer verwendet.
+
„Beliebig“ ist der Standard-PSL-Wert (Performance Service Level). Diese Einstellung erstellt die Speichereinheit mithilfe des ONTAP-Algorithmus für die ausgewogene Platzierung. Sie können jedoch nach Bedarf die Option „Performance“ oder „Extreme“ auswählen.

.. Wählen Sie *vorhandenes Volume verwenden*, *QoS*-Optionen nach Bedarf aktivieren und geben Sie die Details an.
+

NOTE: Beim Speichertyp ASA r2 gilt die Volume-Erstellung oder -Auswahl nicht für die Erstellung von Speichereinheiten (LUN/Namespace).  Daher werden diese Optionen nicht angezeigt.

+

NOTE: Sie können das vorhandene Volume nicht zum Erstellen eines VMFS-Datenspeichers mit NVMe/FC- oder NVMe/TCP-Protokoll verwenden.  Erstellen Sie ein neues Volume für den VMFS-Datenspeicher.



. Überprüfen Sie die Datastore-Details im Bereich *Summary* und wählen Sie *Finish*.



NOTE: Wenn Sie den Datastore auf einem geschützten Cluster erstellen, wird eine schreibgeschützte Meldung angezeigt: „Der Datastore wird auf einem geschützten Cluster gemountet.“

.Ergebnis
ONTAP -Tools erstellen den VMFS-Datenspeicher und mounten ihn auf allen Hosts.

--
====