---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords: discover storage systems and hosts, ONTAP tools first discovery, ESXi host and LUN discovery, NFS export discovery 
summary: ESXi Hosts, LUNs, NFS Exporte und NetApp Speichersysteme werden in ONTAP tools beim ersten Start erkannt. 
---
= Speichersysteme und Hosts in ONTAP tools entdecken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ONTAP tools for VMware vSphere zum ersten Mal im vSphere Client gestartet wird, werden automatisch ESXi-Hosts, die zugehörigen LUNs und NFS-Exporte sowie die NetApp -Speichersysteme, denen diese Ressourcen gehören, erkannt.

.Bevor Sie beginnen
* Stellen Sie sicher, dass alle ESXi-Hosts eingeschaltet und verbunden sind.
* Stellen Sie sicher, dass alle zu erkennenden Storage Virtual Machines (SVMs) ausgeführt werden und dass auf jedem Clusterknoten mindestens eine Daten-LIF für das verwendete Speicherprotokoll (NFS oder iSCSI) konfiguriert ist.


.Über diese Aufgabe
Sie können neue Speichersysteme entdecken oder bestehende aktualisieren, um die neuesten Kapazitäts- und Konfigurationsdetails zu erhalten.  Sie können die ONTAP tools for VMware vSphere Anmeldeinformationen für den Zugriff auf das Speichersystem ändern.

Bei der Erkennung der Speichersysteme erfasst ONTAP-Tools für VMware vSphere Informationen von den ESXi-Hosts, die von der vCenter Server-Instanz gemanagt werden.

.Schritte
. Auf der Startseite des vSphere Clients die Option *Hosts und Cluster* auswählen.
. Mit der rechten Maustaste auf das gewünschte Rechenzentrum klicken und *NetApp ONTAP tools* > *Host- und Speicherdaten aktualisieren* auswählen.
+
Bestätigen Sie im Dialogfeld *Bestätigen* Ihre Auswahl.

. Wählen Sie die ermittelten Speicher-Controller aus, die den Status haben `Authentication Failure`, und wählen Sie *actions* > *Modify* aus.
. Geben Sie die erforderlichen Informationen in das Dialogfeld * Speichersystem ändern* ein.
. Wiederholen Sie die Schritte 4 und 5 für alle Speicher-Controller mit `Authentication Failure` Status:


Führen Sie nach Abschluss des Erkennungsvorgangs die folgenden Schritte aus:

* Verwenden Sie ONTAP-Tools für VMware vSphere, um ESXi-Hosteinstellungen für Hosts zu konfigurieren, die das Warnsymbol in der Spalte für die Adaptereinstellungen, die Spalte für die MPIO-Einstellungen oder die Spalte für NFS-Einstellungen anzeigen.
* Geben Sie die Anmeldeinformationen des Speichersystems an.

