---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: Mithilfe der ONTAP-Tools für VMware vSphere können Timeouts und andere Werte auf den ESXi-Hosts festgelegt werden, um beste Leistung und erfolgreiches Failover zu gewährleisten. Die Werte, die ONTAP Tools für VMware vSphere Set bieten, basieren auf internen NetApp-Tests. 
---
= Legen Sie ESXi-Hostwerte fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den ONTAP-Tools für VMware vSphere können Sie Timeouts und andere Werte auf den ESXi-Hosts festlegen, um die beste Performance und ein erfolgreiches Failover zu gewährleisten. Die Werte, die ONTAP Tools für VMware vSphere Set bieten, basieren auf internen NetApp-Tests.

Auf einem ESXi-Host können Sie die folgenden Werte festlegen:



== HBA/CNA-Adaptereinstellungen

Legt die empfohlenen Einstellungen für das HBA-Zeitlimit für NetApp-Speichersysteme fest.

|===
| Parameter | Wert festlegen auf... 


| Disk.QFullSampleSize | 32 für alle Konfigurationen. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert. 


| Disk.QFullThreshold | 8 für alle Konfigurationen. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert. 


| Emulex FC-HBA-Zeitüberschreitungen | Standardwert. 


| QLogic FC-HBA-Zeitüberschreitungen | Standardwert. 
|===


== MPIO-Einstellungen

MPIO-Einstellungen definieren die bevorzugten Pfade für NetApp-Speichersysteme. Sie legen fest, welche der verfügbaren Pfade optimiert sind (im Gegensatz zu nicht optimierten Pfaden, die das Interconnect-Kabel durchlaufen), und legen den bevorzugten Pfad auf einen dieser Pfade fest.

In hochperformanten Umgebungen oder wenn Sie die Performance mit einem einzelnen LUN-Datastore testen, sollten Sie eventuell die Load-Balancing-Einstellung der Round-Robin (VMW_PSP_RR) Path Selection Policy (PSP) von der Standard-IOPS-Einstellung von 1000 auf den Wert 1 ändern.



== NFS-Einstellungen

|===


| Parameter | Wert festlegen auf... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024MB 


| MaxVolumes: NFS | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 oder höher 


| NFS.HeartbeatMaxFailures | 10 


| HeartbeatFrequency NFS.HeartbeatFrequency | 12 


| HeartbeatTimeout NFS.HeartbeatTimeout | 5 
|===