---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können das NetApp NFS-Plug-in für VMware vStorage APIs for Array Integration \(VAAI\) mit den ONTAP Tools für VMware vSphere installieren.' 
---
= Installieren Sie das NFS VAAI-Plug-in mit ONTAP -Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Plug-In NFS vStorage API for Array Integration (NFS VAAI) verbindet VMware vSphere mit NFS-Speicher-Arrays.  Verwenden Sie ONTAP tools for VMware vSphere , um das VAAI-Plug-In zu installieren. Dadurch kann das NFS-Speicherarray bestimmte Speichervorgänge anstelle von ESXi-Hosts verarbeiten.

.Bevor Sie beginnen
* Laden Sie das Installationspaket herunter https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["NetApp NFS Plug-in für VMware VAAI"].
* Stellen Sie sicher, dass Sie über den ESXi-Host und vSphere 7.0U3 neuesten Patch oder neuere Versionen und ONTAP 9.14.1 oder höhere Versionen verfügen.
* Mounten Sie einen NFS-Datastore.


.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie im Abschnitt Plug-ins *Shortcuts* > *NetApp ONTAP Tools* aus.
. Wählen Sie *Einstellungen* > *NFS VAAI Tools*.
. Wenn Sie das VAAI-Plug-In bereits auf vCenter Server hochgeladen haben, wählen Sie *Ändern* unter *Vorhandene Version*.  Wenn nicht, wählen Sie *Hochladen*.
. Durchsuchen Sie die Datei, wählen `.vib` Sie sie aus und wählen Sie *Hochladen*, um die Datei in ONTAP-Tools hochzuladen.
. Wählen Sie *auf ESXI-Host installieren*, wählen Sie den ESXi-Host aus, auf dem Sie das NFS VAAI-Plug-in installieren möchten, und wählen Sie dann *Installieren* aus.
+
Der vSphere Web Client zeigt nur die ESXi-Hosts an, die das Plug-in installieren können. Sie können den Installationsfortschritt im Abschnitt „Letzte Aufgaben“ verfolgen.

. Starten Sie den ESXi-Host nach der Installation manuell neu.
+
Nach dem Neustart des ESXi-Hosts erkennen und aktivieren die ONTAP tools for VMware vSphere das NFS-VAAI-Plug-In automatisch.



.Was kommt als Nächstes?
Nachdem Sie das NFS-VAAI-Plug-In installiert und Ihren ESXi-Host neu gestartet haben, konfigurieren Sie die NFS-Exportrichtlinien für die VAAI-Kopierauslagerung.  Stellen Sie sicher, dass die Exportrichtlinienregeln diese Anforderungen erfüllen:

* Das entsprechende ONTAP Volume ermöglicht NFSv4-Aufrufe.
* Der Root-Benutzer bleibt Root und NFSv4 ist in allen übergeordneten Junction-Volumes zulässig.
* Die Option für die VAAI-Unterstützung wird auf dem jeweiligen NFS-Server eingestellt.


Weitere Informationen finden Sie unter https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Konfigurieren Sie die richtigen NFS-Exportrichtlinien für den VAAI Copy-Offload"] KB-Artikel.

.Verwandte Informationen
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Support für VMware vStorage via NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Aktivieren oder deaktivieren Sie NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["ONTAP unterstützt NFSv4.2"]
