---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: ONTAP Tools für VMware vSphere managen den Schutz von Host-Clustern. 
---
= Schützen mit Host-Cluster-Schutz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere managen den Schutz von Host-Clustern. Alle Datastores, die zur ausgewählten SVM gehören und auf einem oder mehreren Hosts des Clusters gemountet werden, werden unter einem Host-Cluster geschützt.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie diese Anforderungen erfüllen, bevor Sie einen Hostcluster schützen:

* Der Hostcluster enthält nur Datenspeicher von einer einzigen SVM.
* Datenspeicher auf dem Hostcluster werden nicht auf Hosts außerhalb des Clusters gemountet.
* Auf dem Hostcluster gemountete Datenspeicher sind VMFS-Datenspeicher mit iSCSI- oder FC-Protokoll.  Sie können keine vVols, NFS- oder VMFS-Datenspeicher mit NVMe/FC- und NVMe/TCP-Protokollen verwenden.
* Datenspeicher, die auf auf einem Host gemounteten FlexVol/LUN-Volumes basieren, sind nicht Teil einer Konsistenzgruppe.
* Datenspeicher, die auf auf einem Host gemounteten FlexVol/LUN-Volumes basieren, sind nicht Teil einer SnapMirror -Beziehung.
* Der Hostcluster enthält mindestens einen Datenspeicher.


.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf einen Hostcluster und wählen Sie * NetApp ONTAP -Tools* > *Cluster schützen*.
. Im Fenster „Cluster schützen“ trägt das System automatisch den Datenspeichertyp und die Details der virtuellen Maschine (VM) des Quellspeichers ein.  Wählen Sie den Link „Datenspeicher“ aus, um die geschützten Datenspeicher anzuzeigen.
. Wählen Sie *Beziehung Hinzufügen*.
. Wählen Sie im Fenster *SnapMirror-Beziehung hinzufügen* den Typ *Zielspeicher-VM* und den Typ *Richtlinie* aus.
+
Der Richtlinientyp kann „asynchron“ oder „AutomaticatedFailOverDuplex“ sein.

+
Wenn Sie die SnapMirror Beziehung als Richtlinie vom Typ AutomatedFailOverDuplex hinzufügen, müssen Sie die Ziel-Storage VM als Storage-Backend zum gleichen vCenter hinzufügen, in dem ONTAP Tools für VMware vSphere implementiert werden.

+
Beim Richtlinientyp „AutomatedFailOverDuplex“ gibt es einheitliche und nicht einheitliche Hostkonfigurationen.  Wenn Sie die Umschalttaste *einheitliche Hostkonfiguration* auswählen, wird die Konfiguration der Hostinitiatorgruppe implizit auf der Zielsite repliziert. Weitere Informationen finden Sie unter link:../concepts/ontap-tools-concepts-terms.html["Schlüsselkonzepte und -Begriffe"] .

. Wenn Sie sich für eine nicht einheitliche Hostkonfiguration entscheiden, wählen Sie den Hostzugriff (Quelle/Ziel) für jeden Host innerhalb dieses Clusters aus.
. Wählen Sie *Hinzufügen*.
. Sie können den Hostclusterschutz mit dem Vorgang *Hostclusterschutz ändern* bearbeiten.  Sie können die Beziehungen mithilfe der Auslassungspunkte-Menüoptionen bearbeiten oder löschen.
. Wählen Sie die Schaltfläche *protect*.
+
Das System erstellt eine vCenter-Aufgabe mit Job-ID-Details und zeigt ihren Fortschritt im Bereich „Letzte Aufgaben“ an.  Dies ist eine asynchrone Aufgabe. Die Benutzeroberfläche zeigt nur den Status der Anforderungsübermittlung an und wartet nicht auf den Abschluss der Aufgabe.

. Um die geschützten Host-Cluster anzuzeigen, gehen Sie zu * NetApp ONTAP Tools* > *Schutz* > *Host-Cluster-Beziehungen*.  Wählen Sie eine Konsistenzgruppe aus, um ihre Kapazität, die zugehörigen Datenspeicher und die untergeordneten Konsistenzgruppen anzuzeigen.


[NOTE]
====
Wenn Sie den Schutz innerhalb einer Stunde nach der Erstellung entfernen müssen, führen Sie zuerst die Speichererkennung aus.

====
.Verwandte Informationen
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro Storage Cluster (vMSC)"^]
