---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: Sie können den VASA-Anbieter mithilfe der ONTAP tools for VMware vSphere bei einer vCenter Server-Instanz registrieren. 
---
= Registrieren Sie den VASA Provider bei einer vCenter Server-Instanz in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie ONTAP tools for VMware vSphere, um den VASA-Anbieter bei einer vCenter Server-Instanz zu registrieren.  Dies ermöglicht eine speicherrichtlinienbasierte Verwaltung, vVols Unterstützung und die Integration mit VMware Live Site Recovery-Geräten auf ONTAP -Systemen.

Die VASA-Provider-Einstellungen zeigen den Registrierungsstatus für den ausgewählten vCenter Server an.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie im Abschnitt Plug-ins *Shortcuts* > *NetApp ONTAP Tools* aus.
. Wählen Sie *Einstellungen* > *VASA-Anbietereinstellungen*.  Die ONTAP -Tools zeigen den Registrierungsstatus des VASA-Anbieters als „nicht registriert“ an.
. Klicken Sie auf die Schaltfläche *Registrieren*, um den VASA Provider zu registrieren.
. Geben Sie einen Namen und Anmeldeinformationen für den VASA-Anbieter ein.  Der Benutzername darf nur Buchstaben, Zahlen und Unterstriche enthalten.  Legen Sie die Passwortlänge zwischen 8 und 256 Zeichen fest.
. Wählen Sie *Registrieren*.
. Nach einer erfolgreichen Registrierung und Seitenaktualisierung zeigen die ONTAP -Tools den Status, den Namen und die Version des registrierten VASA-Anbieters an.


.Wie es weiter geht
Vergewissern Sie sich, dass der aufgelistete VASA Provider vom vCenter Client unter VASA Provider aufgeführt ist:

.Schritte
. Gehen Sie zur vCenter Server-Instanz.
. Melden Sie sich mit den Administratoranmeldeinformationen an.
. Wählen Sie *Speicheranbieter* > *Konfigurieren* Aus. Vergewissern Sie sich, dass der onboard VASA Provider korrekt aufgeführt ist.

