---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, ONTAP tools for VMware vSphere, 10.6 
summary: In den Versionshinweisen zu ONTAP tools for VMware vSphere 10.6 finden sich Informationen zu Funktionen, Kompatibilität und unterstützten Migrationspfaden. 
---
= Versionshinweise für ONTAP tools für VMware vSphere 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf dieser Seite finden sich wichtige Informationen zu ONTAP tools for VMware vSphere 10.6. Die verlinkten Themen bieten Details zu Funktionen, Kompatibilität und Migrationsinformationen.

Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new.adoc[Neuerungen in ONTAP tools für VMware vSphere 10.6] zu finden.

Die aktuellsten Informationen zur Kompatibilität finden Sie unter  https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].

Die Migration von ONTAP tools for VMware vSphere 9.12D1, 9.13D2 und 9.13P2 auf ONTAP tools for VMware vSphere 10.6 wird unterstützt.

Weitere Informationen finden sich im  https://library.netapp.com/ecm/ecm_download_file/ECMLP3383264["ONTAP tools für VMware vSphere 10.6 Versionshinweise"^]. Für den Zugriff auf dieses Dokument ist eine Anmeldung mit Ihrem NetApp Konto oder die Erstellung eines Kontos erforderlich.
