---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: Informieren Sie sich über die neuen Funktionen der ONTAP tools for VMware vSphere 10.5. 
---
= Was ist neu in den ONTAP tools for VMware vSphere 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informieren Sie sich über die neuen Funktionen der ONTAP tools for VMware vSphere 10.5.

* *Plattformqualifikation*


ONTAP tools for VMware vSphere 10.5 bieten Unterstützung für ASA r2-Systeme und sorgen so für Kompatibilität mit den neuesten Hardware- und Softwarekonfigurationen.  Diese Version umfasst auch die Integration mit ONTAP 9.16.1 und 9.17.1, wodurch die unterstützten Umgebungen erweitert werden.

* *VMware-Qualifikation und -Zertifizierungen*


ONTAP tools for VMware vSphere 10.5 entsprechen den aktuellen VMware-Zertifizierungsstandards für Interoperabilität und unterstützen sowohl ESXi-Host als auch vCenter Server.

* * MetroCluster Unterstützung*


Diese Version bietet Unterstützung für MetroCluster -Konfigurationen und verbessert so die Hochverfügbarkeit und Notfallwiederherstellungsfunktionen.

* *Sicherheits- und Zertifikatsverwaltung*


Diese Version führt eine optimierte Verwaltung selbstsignierter Zertifikate ein und verbessert so sowohl die Benutzererfahrung als auch die Einhaltung von Sicherheitsstandards.  Es bietet verbesserte Workflows zur Zertifikatsvalidierung, um ONTAP und ONTAP tools for VMware vSphere Kommunikation zu sichern.

* *Replikationsverbesserungen*


Diese Version unterstützt die VMFS-Replikation mit hierarchischer Konsistenzgruppe einschließlich SRA und SnapMirror Active Sync in ASA R2-Systemen.  Es unterstützt Zero-RPO-Backups zur Verbesserung des Datenschutzes und der Datenwiederherstellung.

* *Upgrade und Migration*


Der Upgrade- und Migrationsprozess von früheren Versionen der ONTAP tools for VMware vSphere auf die ONTAP tools for VMware vSphere 10.5 ist nahtlos und effizient konzipiert, minimiert Ausfallzeiten und gewährleistet einen reibungslosen Übergang.



== Unterstützte ONTAP -Plattformen und vCenter Server-Versionen

Aktuelle Informationen zur Versionskompatibilität finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] .
