---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords: add vSphere host, ONTAP tools host discovery, register ESXi host, VMware host management 
summary: VMware vSphere-Hosts zu ONTAP tools for VMware vSphere hinzufügen. 
---
= VMware vSphere-Hosts zu ONTAP tools hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Neue VMware vSphere Hosts zu ONTAP tools for VMware vSphere hinzufügen, sodass Host-Datenspeicher verwaltet und geschützt werden können.

.Schritte
. Einen Host zum VMware vSphere Cluster entsprechend der  https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] hinzufügen.
. Nachdem Sie den Host hinzugefügt haben, zum Hauptmenü der ONTAP tools gehen und im Übersichtsfenster *Discover* auswählen oder auf den Abschluss der geplanten Host-Erkennung warten.


.Ergebnis
Der neue Host wird nun von ONTAP tools for VMware vSphere erkannt und verwaltet. Datenspeicher auf dem Host können jetzt verwaltet werden.

.Verwandte Themen
* link:../manage/mount-a-vvols-datastore.html["Mounten Sie einen VVols Datastore"]auf neuen Hosts.
* link:../manage/mount-datastores-on-host.html["Mounten Sie NFS- und VMFS-Datastore"]auf neuen Hosts.

