---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords: attach data disk VM, detach VM disk, ONTAP tools virtual machine disk, VMware VM storage expansion 
summary: Virtuelle Maschinen-Datenträger können angehängt oder entfernt werden, um die Speicherkapazität zu verwalten. 
---
= Eine Datenfestplatte an eine VM in ONTAP tools anhängen oder trennen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Datenfestplatten an oder von virtuellen Maschinen in vSphere anhängen oder trennen, um die Speicherkapazität zu verwalten.



[[attach-a-data-disk-to-a-virtual-machine]]
== Verbinden Sie eine Datenfestplatte mit einer virtuellen Maschine

Schließen Sie eine Datenfestplatte an eine virtuelle Maschine an, um mehr Speicherplatz hinzuzufügen.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Mit der rechten Maustaste auf eine virtuelle Maschine im Inventar klicken und *Einstellungen bearbeiten* auswählen.
. Wählen Sie auf der Registerkarte *Virtual Hardware* *existing Hard Disk* aus.
. Wählen Sie die virtuelle Maschine aus, die die Festplatte enthält.
. Wählen Sie die Festplatte aus, die Sie anschließen möchten, und wählen Sie *OK* aus.


.Ergebnis
Die Festplatte wird in der Liste Virtuelle Hardwaregeräte angezeigt.



[[detach-a-data-disk-from-the-virtual-machine]]
== Trennen Sie ein Datenlaufwerk von der virtuellen Maschine

Eine Datenfestplatte kann von einer virtuellen Maschine getrennt werden, wenn sie nicht mehr benötigt wird. Die Festplatte wird nicht gelöscht und verbleibt im ONTAP Speichersystem.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf eine virtuelle Maschine im Inventar und wählen Sie *Einstellungen bearbeiten*.
. Bewegen Sie den Mauszeiger über die Scheibe und wählen Sie *Entfernen*.
+

NOTE: Der Datenträger wird aus der virtuellen Maschine entfernt. Wenn andere virtuelle Maschinen den Datenträger gemeinsam nutzen, werden die Datenträgerdateien nicht gelöscht.



.Verwandte Informationen
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Fügen Sie einer virtuellen Maschine eine neue Festplatte hinzu"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Fügen Sie einer virtuellen Maschine eine vorhandene Festplatte hinzu"]
