---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords:  
summary: Verbinden Sie eine Datenfestplatte mit einer virtuellen Maschine, um die Speicherkapazität zu erweitern. 
---
= Eine Datenfestplatte an eine VM in ONTAP tools anhängen oder trennen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um Datenträger an virtuelle Maschinen in vSphere anzuhängen oder zu trennen und deren Speicherressourcen zu verwalten.



== Verbinden Sie eine Datenfestplatte mit einer virtuellen Maschine

Schließen Sie eine Datenfestplatte an eine virtuelle Maschine an, um mehr Speicherplatz hinzuzufügen.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf eine virtuelle Maschine im Inventar und wählen Sie *Einstellungen bearbeiten*.
. Wählen Sie auf der Registerkarte *Virtual Hardware* *existing Hard Disk* aus.
. Wählen Sie die virtuelle Maschine aus, auf der das Laufwerk vorhanden ist.
. Wählen Sie die Festplatte aus, die Sie anschließen möchten, und klicken Sie auf die Schaltfläche *OK*.


.Ergebnis
Die Festplatte wird in der Liste Virtuelle Hardwaregeräte angezeigt.



== Trennen Sie ein Datenlaufwerk von der virtuellen Maschine

Trennen Sie eine Datenfestplatte von einer virtuellen Maschine, wenn Sie sie nicht mehr benötigen.  Die Festplatte wird nicht gelöscht; sie verbleibt im ONTAP -Speichersystem.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf eine virtuelle Maschine im Inventar und wählen Sie *Einstellungen bearbeiten*.
. Bewegen Sie den Mauszeiger über die Scheibe und wählen Sie *Entfernen*.
+

NOTE: Der Datenträger wird aus der virtuellen Maschine entfernt. Wenn andere virtuelle Maschinen den Datenträger gemeinsam nutzen, werden die Datenträgerdateien nicht gelöscht.



.Verwandte Informationen
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Fügen Sie einer virtuellen Maschine eine neue Festplatte hinzu"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Fügen Sie einer virtuellen Maschine eine vorhandene Festplatte hinzu"]
