---
permalink: manage/backup-settings.html 
sidebar: sidebar 
keywords: ONTAP tools backup settings, configure backup schedule, appliance backup configuration, ONTAP tools data protection 
summary: ONTAP tools Backup kann aktiviert oder deaktiviert und die Sicherungshäufigkeit zwischen 10 und 60 Minuten konfiguriert werden. 
---
= ONTAP tools-Sicherungseinstellungen bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP tools for VMware vSphere 10.5 sind Backups standardmäßig aktiviert und werden alle 10 Minuten ausgeführt. Backups können deaktiviert oder die Backup-Frequenz geändert werden.

Deaktivieren Sie die Datensicherung nicht, da dies ONTAP tools daran hindert, ein niedriges Wiederherstellungspunktziel (RPO) einzuhalten. Das Deaktivieren der Datensicherung löscht die vorhandenen Sicherungsdateien nicht. Die Häufigkeit der Datensicherung kann auf einen Wert zwischen 10 und 60 Minuten geändert werden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie die Option *Einstellungen* > *Sicherung* > *Bearbeiten*.
. Im Bearbeitungsfenster lässt sich die Datensicherung deaktivieren oder die Sicherungshäufigkeit ändern.

