---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords: ONTAP tools certificates, VASA provider certificate, vCenter certificate trust, manage appliance certificates 
summary: ONTAP tools und VASA Provider-Zertifikate verwalten, Standardzertifikate erneuern oder durch benutzerdefinierte CA-Zertifikate ersetzen. 
---
= ONTAP tools-Zertifikate verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools und VASA Provider verwenden standardmäßig ein selbstsigniertes Zertifikat. Im ONTAP tools Manager besteht die Möglichkeit, dieses Zertifikat zu erneuern oder durch ein benutzerdefiniertes CA-Zertifikat zu ersetzen. Multi-vCenter Deployments erfordern benutzerdefinierte CA-Zertifikate.


WARNING: Wenn Zertifikate ohne rechtzeitige Verlängerung ablaufen, funktionieren die ONTAP tools nicht mehr. Zertifikate sollten vor Ablauf erneuert werden, damit der kontinuierliche Betrieb aufrechterhalten bleibt und Unterbrechungen des Dienstes vermieden werden.

.Bevor Sie beginnen
Folgendes sollten Sie vor Beginn bereithalten:

* Der Domänenname, der der ONTAP tools IP-Adresse zugeordnet ist.
* Erfolgreicher nslookup des Domainnamens, was bestätigt, dass er zur korrekten IP-Adresse aufgelöst wird.
* Zertifikate, die mit dem Domänennamen und der IP-Adresse der ONTAP -Tools erstellt wurden.



NOTE: Eine ONTAP tools IP-Adresse sollte einer vollqualifizierten Domain (FQDN) zugeordnet sein. Zertifikate sollten denselben FQDN im Feld Subject Alternative Name (SAN) enthalten.


NOTE: Sie können nicht von einem mit einer Zertifizierungsstelle signierten zu einem selbstsignierten Zertifikat wechseln.

[role="tabbed-block"]
====
.Upgrade ONTAP Tools Zertifikat
--
Die Registerkarte ONTAP tools zeigt Details wie den Zertifikatstyp (selbstsigniert oder CA-signiert) und den Domainnamen. Während der Bereitstellung generiert ONTAP tools standardmäßig ein selbstsigniertes Zertifikat. Das Zertifikat kann erneuert oder auf ein CA-signiertes Zertifikat aktualisiert werden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *Zertifikate* > *ONTAP Tools* > *erneuern*, um die Zertifikate zu erneuern.
+
Sie können das Zertifikat erneuern, wenn es abgelaufen ist oder sich dem Ablaufdatum nähert. Die Erneuerungsoption ist verfügbar, wenn der Zertifikatstyp selbstsigniert oder von einer Zertifizierungsstelle signiert ist. Im Pop-up-Fenster sind die Details des Serverzertifikats, des privaten Schlüssels, der Stammzertifizierungsstelle und des Zwischenzertifikats anzugeben.

+

NOTE: Das System ist offline, bis die Zertifikatserneuerung abgeschlossen ist und ONTAP tools Manager Sie abmeldet.

. Um das selbstsignierte Zertifikat auf ein benutzerdefiniertes CA-Zertifikat zu aktualisieren, wählen Sie *Zertifikate* > *ONTAP-Tools* > *Upgrade auf CA*.
+
.. Laden Sie im Popup-Fenster das Serverzertifikat, den privaten Schlüssel des Serverzertifikats, das Stammzertifizierungsstellenzertifikat und die Zwischenzertifikatdateien hoch.
.. Geben Sie den FQDN ein, der der ONTAP tools IP-Adresse (ehemals Load Balancer IP) zugeordnet ist, für die Sie dieses Zertifikat generiert haben, und aktualisieren Sie das Zertifikat.
+

NOTE: Das System ist bis zum Abschluss des Upgrades offline und Sie werden von der Oberfläche des ONTAP Tools Managers abgemeldet.





--
.Upgrade des VASA Provider-Zertifikats
--
ONTAP tools für VMware vSphere verwendet standardmäßig ein selbstsigniertes Zertifikat für VASA Provider. Mit diesem Zertifikat kann nur eine vCenter Server-Instanz für vVols Datenspeicher verwaltet werden. Wenn mehrere vCenter Server-Instanzen verwaltet werden und die vVols Funktionalität aktiviert werden soll, ist das selbstsignierte Zertifikat durch ein benutzerdefiniertes CA-Zertifikat zu ersetzen.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *Certificates* > *VASA Provider* oder *ONTAP Tools* > *Renew*, um die Zertifikate zu erneuern.
. Wählen Sie *Certificates* > *VASA Provider* oder *ONTAP Tools* > *Upgrade auf CA*, um das selbstsignierte Zertifikat auf ein benutzerdefiniertes CA-Zertifikat zu aktualisieren.
+
.. Laden Sie im Popup-Fenster das Serverzertifikat, den privaten Schlüssel des Serverzertifikats, das Stammzertifizierungsstellenzertifikat und die Zwischenzertifikatdateien hoch.
.. Geben Sie den FQDN ein, der der ONTAP tools IP-Adresse (ehemals Load Balancer IP) zugeordnet ist, für die Sie dieses Zertifikat generiert haben, und aktualisieren Sie das Zertifikat.
+

NOTE: Das System ist bis zum Abschluss des Upgrades offline und Sie werden von der Oberfläche des ONTAP Tools Managers abgemeldet.





--
.ONTAP tools Servicezertifikat aktualisieren
--
Ab ONTAP tools 10.5 wurde die Gültigkeitsdauer von Zertifikaten von 10 Jahren auf 1 Jahr geändert. Ab ONTAP tools 10.5P2 werden während eines Upgrades der ONTAP tools die internen Servicekommunikationszertifikate automatisch erneuert und das selbstsignierte Gateway-Zertifikat ebenfalls aktualisiert.

Diese Option in der Wartungskonsole dient dazu, interne Servicekommunikationszertifikate manuell zu aktualisieren, wenn eine Warnung über das bevorstehende Ablaufdatum eines internen Zertifikats angezeigt wird oder wenn ONTAP tools seit über einem Jahr nicht aktualisiert wurde. Ab ONTAP tools 10.5P2 werden diese Zertifikate bei Upgrades automatisch erneuert. Die aktualisierten Zertifikate behalten weiterhin eine Gültigkeitsdauer von einem Jahr (365 Tagen), was die Erfüllung von Audit-Anforderungen unterstützt.

.Schritte
. Melden Sie sich beim vCenter Server an.
. Die ONTAP tools VM suchen und die Webkonsole öffnen.
. Melden Sie sich mit den  `maint` Zugangsdaten an.
. Eingeben `2` Um die *Systemkonfiguration* auszuwählen, wählen Sie diese bitte aus.
. Geben Sie  `9` ein, um *Refresh ONTAP tools services certificates* auszuwählen.



WARNING: Diese Aktion startet alle Dienste neu und kann zu Ausfallzeiten oder Störungen führen. Zum Fortfahren muss die Warnung durch Eingabe von  `y` bestätigt werden, danach beginnt der Aktualisierungsprozess.

--
====