---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Mit einer einzigen Instanz der ONTAP Tools für VMware vSphere können mehrere vCenter Server-Instanzen gemanagt werden. ONTAP Tools für VMware vSphere werden mit einem selbstsignierten Zertifikat für VASA Provider implementiert. Dadurch kann nur eine vCenter Server-Instanz für VVols-Datastores gemanagt werden. 
---
= Verwalten von Zertifikaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit einer einzigen Instanz der ONTAP Tools für VMware vSphere können mehrere vCenter Server-Instanzen gemanagt werden.

Stellen Sie sicher, dass der Domänenname, auf dem das Zertifikat ausgestellt wird, der virtuellen IP-Adresse in einer Multi-vCenter-Bereitstellung zugeordnet ist, in der benutzerdefinierte CA-Zertifikate erforderlich sind. _Nslookup_ Überprüfen Sie den Domänennamen, um zu prüfen, ob die Domäne auf die beabsichtigte IP-Adresse aufgelöst wird. Die Zertifikate sollten mit dem Domänennamen und der IP-Adresse der Load Balancer-IP-Adresse erstellt werden.


NOTE: Eine andere Load Balancer-IP-Adresse, die verschiedenen Domänen zugeordnet ist, wird nicht unterstützt, wenn Sie ein selbstsigniertes Upgrade auf eine benutzerdefinierte CA durchführen.

[role="tabbed-block"]
====
.Zertifikat für ONTAP Tools
--
Auf der Registerkarte „ONTAP Tools“ werden Details wie der Zertifikatstyp (selbstsigniert/CA-signiert) und der Domänenname angezeigt. Während der Bereitstellung wird standardmäßig ein selbstsigniertes Zertifikat generiert. Sie können das Zertifikat erneuern oder das Zertifikat auf CA aktualisieren.

*Schritte*

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://loadBalancerIP:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *Zertifikate* > *ONTAP Tools* > *erneuern*, um die Zertifikate zu erneuern.
+

NOTE: Sie können das Zertifikat erneuern, wenn es abgelaufen ist oder sich dem Ablaufdatum nähert. Das System ist offline, bis das Zertifikat erneuert wird und Sie von der Benutzeroberfläche abgemeldet werden.

+
*Renew* ist die einzige Option, die verfügbar ist, wenn der Zertifikatstyp CA-signiert ist. Bei CA-signierten Zertifikaten wird ein Dialogfeld angezeigt, in dem Sie das Serverzertifikat, den privaten Schlüssel, die Stammzertifizierungsstelle und die Details zum Zwischenzertifikat angeben können.

. Um das selbstsignierte Zertifikat auf ein benutzerdefiniertes CA-Zertifikat zu aktualisieren, wählen Sie *Zertifikate* > *ONTAP-Tools* > *Upgrade auf CA*.
+
.. Laden Sie im Popup-Fenster *Upgrade Certificate to Custom CA* das Serverzertifikat, den privaten Schlüssel des Serverzertifikats, das Stammzertifizierungszertifikat und die Zwischenzertifikatdateien hoch. Der QuickInfo enthält eine Beschreibung der Zertifikate.
.. Geben Sie den Domänennamen ein, für den Sie dieses Zertifikat erstellt haben.
.. Klicken Sie Auf *Upgrade*.
+

NOTE: Das System ist offline, bis das Upgrade abgeschlossen ist und Sie von der Benutzeroberfläche abgemeldet werden. Das Umschalten von einem signierten CA-Zertifikat auf ein selbstsigniertes Zertifikat ist nicht zulässig.





--
.VASA-Provider-Zertifikat
--
ONTAP Tools für VMware vSphere werden mit einem selbstsignierten Zertifikat für VASA Provider implementiert. Dadurch kann nur eine vCenter Server-Instanz für VVols-Datastores gemanagt werden. Wenn Sie mehrere vCenter Server-Instanzen managen und die VVols-Funktion auf mehreren vCenter Server-Instanzen aktivieren möchten, müssen Sie das selbstsignierte Zertifikat über die Benutzeroberfläche von ONTAP Tools Manager in ein benutzerdefiniertes CA-Zertifikat ändern.

*Schritte*

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://loadBalancerIP:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie *Certificates* > *VASA Provider* oder *ONTAP Tools* > *Renew*, um die Zertifikate zu erneuern.
. Um das selbstsignierte Zertifikat auf ein benutzerdefiniertes CA-Zertifikat zu aktualisieren, wählen Sie *Zertifikate* > *VASA-Anbieter* oder *ONTAP-Tools* > *Upgrade auf CA*.
+
.. Laden Sie im Popup-Fenster *Upgrade Certificate to Custom CA* das Serverzertifikat, den privaten Schlüssel des Serverzertifikats, das Stammzertifizierungszertifikat und die Zwischenzertifikatdateien hoch. Der QuickInfo enthält eine Beschreibung der Zertifikate.
.. Geben Sie den Domänennamen ein, für den Sie dieses Zertifikat erstellt haben.
.. Klicken Sie Auf *Upgrade*.
+

NOTE: Das System ist offline, bis das Upgrade abgeschlossen ist und Sie von der Benutzeroberfläche abgemeldet werden. Das Umschalten von einem signierten CA-Zertifikat auf ein selbstsigniertes Zertifikat ist nicht zulässig.





--
====