---
permalink: manage/change-valid-flag.html 
sidebar: sidebar 
keywords:  
summary: Sie können das Zertifikatvalidierungsflag mithilfe der Wartungskonsole ändern. 
---
= Zertifikatvalidierungsflag ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig ist das Flag zur Zertifikatsvalidierung aktiviert (auf „true“ gesetzt).  Sie können das Zertifikatvalidierungsflag des ONTAP -Speicher-Backends auf „false“ setzen, wenn Sie SAN-Zertifikatsprüfungen umgehen müssen.  Diese Einstellung ist nicht auf vCenter Server-Zertifikate anwendbar.

.Bevor Sie beginnen
Sie müssen über Anmeldedaten für Wartungsbenutzer verfügen.

.Schritte
. Öffnen Sie im vCenter Server eine Konsole für ONTAP Tools.
. Melden Sie sich als Wartungbenutzer an.
. Eingeben `1` um das Menü *Anwendungskonfiguration* auszuwählen.
. Eingeben `3` um das Zertifikatvalidierungsflag zu ändern.
+
Die Wartungskonsole zeigt den Status des Zertifikatvalidierungsflags an und fordert Sie auf, ihn zu ändern.

. Geben Sie „y“ ein, um die Flagge umzuschalten, oder „n“, um abzubrechen.


Wenn Sie das Flag für die Zertifikatsvalidierung aktivieren (auf „true“ setzen), überprüft ONTAP Tools, ob alle Speicher-Backends Zertifikate mit einem Subject Alternative Name (SAN) verwenden.  Wenn ein Backend ein Zertifikat ohne SAN verwendet, kann die Zertifikatsvalidierung nicht aktiviert werden.  Bevor Sie dieses Flag aktivieren, vergewissern Sie sich, dass alle Speichersysteme SAN-basierte Zertifikate verwenden.  Wenn Sie das Flag für die Zertifikatsvalidierung deaktivieren (auf „false“ setzen), umgeht ONTAP tools die Zertifikatsvalidierung für alle konfigurierten Speicher-Backends.
