---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords: remote diagnostic access, ONTAP tools SSH diag user, enable SSH diagnostics, appliance troubleshooting access 
summary: SSH-Zugriff für den Benutzer „diag“ in ONTAP tools for VMware vSphere aktivieren. 
---
= Konfigurieren Sie den Ferndiagnosezugriff für ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den SSH-Zugriff für den Benutzer diag in ONTAP tools for VMware vSphere aktivieren.

.Bevor Sie beginnen
Aktivieren Sie die VASA Provider-Erweiterung für Ihre vCenter Server-Instanz.

.Über diese Aufgabe
Die Verwendung von SSH für den Zugriff auf das Diagnose-Benutzerkonto weist folgende Einschränkungen auf:

* Es kann jeweils nur ein Login-Konto verwendet werden, wenn SSH aktiviert wird.
* Der SSH-Zugriff auf das diag-Benutzerkonto ist in beiden folgenden Fällen deaktiviert:
+
** Die Zeit läuft ab.
+
Die Anmeldesitzung läuft am nächsten Tag um Mitternacht ab.

** Sie melden sich erneut als Diagnose-Benutzer mit SSH an.




.Schritte
. Melden Sie sich beim vCenter Server an.
. Die ONTAP tools VM suchen und die Webkonsole öffnen.
. Melden Sie sich mit den  `maint` Zugangsdaten an.
. Geben Sie ein `4`, um *Support und Diagnose* auszuwählen.
. Eingeben `2` , um *Zugriff auf Remotediagnose aktivieren* auszuwählen.
. Geben Sie  `y` im Bestätigungsdialogfeld ein, um den Remote-Diagnosezugriff zu aktivieren.
. Geben Sie ein Kennwort für den Remote-Diagnosezugriff ein.

