---
permalink: manage/delete-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Wenn Sie den Host-Cluster-Schutz entfernen, werden die Datastores ungeschützt. 
---
= Entfernen Sie den Host-Cluster-Schutz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie den Host-Cluster-Schutz entfernen, werden die Datastores ungeschützt.

.Schritte
. Um die Liste der geschützten Host-Cluster anzuzeigen, gehen Sie zu * NetApp ONTAP Tools* > *Schutz* > *Host-Cluster-Beziehungen*.
+
Überwachen Sie auf dieser Seite geschützte Hostcluster, den Schutzstatus, die SnapMirror -Beziehung und den Status.  Wählen Sie Konsistenzgruppen aus, um Kapazität, zugehörige Datenspeicher und untergeordnete Gruppen anzuzeigen.

. Wählen Sie im Fenster *Hostclusterschutz* das Auslassungsmenü neben dem Cluster und wählen Sie *Schutz entfernen*.
+
** Wenn Sie den Schutz von einem Hostcluster mit nur einer asynchronen SnapMirror -Beziehung entfernen, müssen Sie die Speicherelemente manuell löschen.  Zu den Speicherelementen gehören Konsistenzgruppen, Volumes (für ONTAP -Systeme), Speichereinheiten (LUNs) und Snapshots.
** Wenn Sie den Schutz von einem Hostcluster mit nur einer automatisierten, auf Failover-Duplex basierenden SnapMirror -Richtlinienbeziehung und einer nicht hierarchischen Konsistenzgruppe entfernen, können Sie die zugehörigen Speicherelemente auf dem sekundären Speicher direkt vom selben Bildschirm aus löschen.
** Wenn Sie den Schutz eines Hostclusters sowohl mit SnapMirror -Richtlinien als auch mit einer hierarchischen Konsistenzgruppe für Sicherungen entfernen, wird eine Warnung zu den Auswirkungen auf die Sicherung angezeigt.  Bestätigen Sie, um fortzufahren.  Nach der Bestätigung löschen Sie die zugehörigen Speicherelemente auf dem Sekundärspeicher.  Wenn Sie keine Bereinigung durchführen, verbleiben die Speicherelemente auf dem sekundären Standort.



