---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Wenn Sie einen dedizierten ONTAP Cluster für ONTAP Tools zur VMware Implementierung verwenden, werden viele nicht genutzte FlexVol Volumes erstellt. Nach dem Entfernen von ONTAP-Tools für VMware vSphere sollten Sie die FlexVol-Volumes entfernen, um mögliche Performance-Auswirkungen zu vermeiden. 
---
= Entfernen Sie FlexVol-Volumes nach der Deinstallation von ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen dedizierten ONTAP Cluster für ONTAP Tools zur VMware Implementierung verwenden, werden viele nicht genutzte FlexVol Volumes erstellt. Nach dem Entfernen von ONTAP-Tools für VMware vSphere sollten Sie die FlexVol-Volumes entfernen, um mögliche Performance-Auswirkungen zu vermeiden.

.Schritte
. Ermitteln Sie den ONTAP tools for VMware vSphere -Bereitstellungstyp über die VM des ONTAP Tools-Verwaltungsknotens.  Führen Sie folgenden Befehl aus, um den Bereitstellungstyp zu überprüfen: _cat /opt/netapp/meta/ansible_vars.yaml | grep -i protocol_
+
Wenn es sich um eine iSCSI-Bereitstellung handelt, löschen Sie auch die igroups.

. Rufen Sie die Liste der FlexVol -Volumes ab. _kubectl beschreibe persistente Volumes | grep internalName | awk -F'=' '{print $2}'_
. Entfernen Sie die VMs vom vCenter Server. Siehe https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Entfernen Sie VMs und VM-Vorlagen und registrieren Sie sie erneut"].
. Löschen Sie FlexVol -Volumes. Siehe https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Löschen Sie ein FlexVol Volume"] . Geben Sie den genauen FlexVol volume Namen im CLI-Befehl ein, um ein Volume zu löschen.
. Löschen Sie im Falle einer iSCSI-Bereitstellung SAN-Initiatorgruppen aus dem ONTAP-Speichersystem. Siehe https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Zeigen Sie SAN-Initiatoren und -Initiatorgruppen an und verwalten Sie sie"].

