---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Mit der Aktion „Datastore löschen“ wird der Datastore gelöscht. Im Falle eines NFS- oder VMFS-Datenspeichers wird ein Dialogfeld mit der Liste der VMs angezeigt, die den Datenspeicher verwenden. 
---
= Löschen Sie Datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Seite beschreibt, wie man NFS-, VMFS- oder vVols -Datenspeicher mithilfe von ONTAP Tools im vCenter Server löscht.

Wenn Sie einen Datenspeicher löschen, werden je nach Datenspeichertyp die folgenden Aktionen ausgeführt:

* Der vVol-Container ist ausgehängt.
* Wenn die Igroup nicht verwendet wird, wird iqn aus der Igroup entfernt.
* Der vVol-Container wird gelöscht.
* Flex-Volumes verbleiben auf dem Speicherarray.


Sie können den Datenspeicher nur löschen, wenn auf dem ausgewählten Datenspeicher keine vVols vorhanden sind.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum und wählen Sie * NetApp ONTAP Tools* > *Datenspeicher löschen*.
+

NOTE: Sie können einen von virtuellen Maschinen verwendeten Datenspeicher nicht löschen.  Verschieben Sie virtuelle Maschinen vor dem Löschen in einen anderen Datenspeicher.  Sie können das Volume nicht löschen, wenn es Teil eines geschützten Hostclusters ist.

+
.. Bei einem NFS- oder VMFS-Datenspeicher wird ein Dialogfeld mit der Liste der VMs angezeigt, die den Datenspeicher verwenden.
.. Wenn einem VMFS-Datenspeicher keine virtuellen Maschinen zugeordnet sind, wird ein Bestätigungsdialogfeld angezeigt.  Wenn der Hostclusterschutz aktiviert ist und eine AFD-Beziehung besteht, können Sie sekundäre Speicherelemente bereinigen.
.. Bei geschützten VMFS-Datenspeichern auf ASA r2-Systemen muss der Schutz vor dem Löschen entfernt werden. Ab ONTAP 9.17.1 und ONTAP tools for VMware vSphere 10.5 können Sie einen geschützten Datenspeicher löschen.  Wenn es sich um den einzigen Datenspeicher in der Schutzgruppe handelt, wird dieser vom Hostclusterschutz automatisch entfernt.
.. Bei vVols -Datenspeichern können Sie den Datenspeicher nur löschen, wenn keine vVols vorhanden sind.  Das Dialogfeld *Datenspeicher löschen* enthält eine Option zum Entfernen von Volumes aus dem ONTAP Cluster.
.. Bei vVols Datenspeichern auf ASA r2-Systemen können Sie die Sicherungsvolumes nicht mit der Option *Datenspeicher löschen* aus ONTAP löschen.


. Um die Backing Volumes auf dem ONTAP-Speicher zu löschen, wählen Sie *Delete Volumes on ONTAP Cluster* aus.
+

NOTE: Bei VMFS-Datenspeichern auf Unified ONTAP -Speicher, die Teil eines geschützten Hostclusters sind, können Sie das Volume nicht aus dem ONTAP Cluster löschen.



Wenn Sie einen NFS-, VMFS- oder vVols -Datenspeicher löschen, verbleiben die übergeordneten igroups auf dem ONTAP System. Untergeordnete igroups, die keinen LUNs zugeordnet sind, werden automatisch gelöscht. ONTAP -Tools führen eine tägliche Bereinigung durch, um nicht zugeordnete übergeordnete Standard-igroups zu entfernen. Löschen Sie die benutzerdefinierten übergeordneten iGroups manuell in ONTAP.  ONTAP Tools können veraltete übergeordnete iGroups nicht wiederverwenden.
