---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Nachdem Sie ONTAP Tools für die VMware vSphere Implementierung gelöscht haben, sollten Sie die während der Implementierung erstellten FlexVol Volumes bereinigen. Wenn Sie einen dedizierten ONTAP Cluster für Implementierungen verwendet haben, sollten Sie die FlexVols bereinigen, da die Implementierung viele FlexVols erstellt, die ungenutzt bleiben, was die Performance senkt. 
---
= Volumes bereinigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie ONTAP Tools für die VMware vSphere Implementierung gelöscht haben, sollten Sie die während der Implementierung erstellten FlexVol Volumes bereinigen. Wenn Sie einen dedizierten ONTAP Cluster für Implementierungen verwendet haben, sollten Sie die FlexVols bereinigen, da die Implementierung viele FlexVols erstellt, die ungenutzt bleiben, was die Performance senkt.

Verwenden Sie die folgenden Richtlinien, um die FlexVols nach der Entfernung von ONTAP Tools zur Implementierung von VMware vSphere zu bereinigen.

.Schritte
. Führen Sie in der VM des primären Node in ONTAP Tools für VMware vSphere den folgenden Befehl aus, um den Bereitstellungstyp zu ermitteln.
+
_CAT /opt/netapp/meta/ansible_vars.yaml grep -i Protocol_

+
Handelt es sich um eine iSCSI-Bereitstellung, müssen auch Initiatorgruppen gelöscht werden.

. Rufen Sie die Liste der in ONTAP während der Implementierung erstellten FlexVols mit dem folgenden Befehl ab.
+
_Kubectl Beschreiben Sie dauerhafte Volumina.Name AWK -F'=' '{Print 2}'_

. Löschen Sie die VMs vom vCenter Server, siehe https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Entfernen Sie VMs und VM-Vorlagen und registrieren Sie sie erneut"] .
. Löschen Sie Volumes aus dem ONTAP System Manager, siehe https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Löschen Sie ein FlexVol Volume"] . Geben Sie den genauen Namen des FlexVolume im cli-Befehl ein, um das Volume zu löschen.
. Löschen Sie im Fall der iSCSI-Bereitstellung SAN-Initiatorgruppen aus ONTAP, siehe https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Zeigen Sie SAN-Initiatoren und -Initiatorgruppen an und verwalten Sie sie"].

