---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: remove FlexVol after uninstall, ONTAP tools cleanup, delete unused FlexVol volumes, post-uninstall storage cleanup 
summary: Nicht verwendete FlexVol Volumes nach der Entfernung der ONTAP tools-Bereitstellung entfernen, um Leistungseinbußen zu vermeiden. 
---
= Entfernen Sie FlexVol-Volumes nach der Deinstallation von ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ONTAP tools for VMware vSphere auf einem dedizierten ONTAP Cluster bereitgestellt werden, erstellt die Bereitstellung viele ungenutzte FlexVol Volumes. Nach der Entfernung von ONTAP tools sollten die ungenutzten FlexVol Volumes gelöscht werden, um mögliche Auswirkungen auf die Performance zu vermeiden.

.Schritte
. Den Bereitstellungstyp der ONTAP tools for VMware vSphere aus der ONTAP tools Management-Node-VM ermitteln. Dazu den folgenden Befehl ausführen, um den Bereitstellungstyp zu überprüfen: _cat /opt/netapp/meta/ansible_vars.yaml | grep -i protocol_
+
Wenn die Bereitstellung iSCSI verwendet, sollten die igroups ebenfalls gelöscht werden.

. Rufen Sie die Liste der FlexVol -Volumes ab. _kubectl beschreibe persistente Volumes | grep internalName | awk -F'=' '{print $2}'_
. Entfernen Sie die VMs vom vCenter Server. Siehe https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Entfernen Sie VMs und VM-Vorlagen und registrieren Sie sie erneut"].
. Löschen Sie FlexVol -Volumes. Siehe https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Löschen Sie ein FlexVol Volume"] . Geben Sie den genauen FlexVol volume Namen im CLI-Befehl ein, um ein Volume zu löschen.
. Bei iSCSI-Bereitstellungen die SAN igroups aus dem ONTAP Storage Backend löschen. Siehe  https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Zeigen Sie SAN-Initiatoren und -Initiatorgruppen an und verwalten Sie sie"].

