---
permalink: manage/disable-autosupport.html 
sidebar: sidebar 
keywords:  
summary: Bei der ersten Konfiguration des Speichersystems ist AutoSupport standardmäßig aktiviert. Es sendet 24 Stunden nach der Aktivierung Meldungen an den technischen Support. 
---
= Deaktivieren Sie AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der ersten Konfiguration des Speichersystems ist AutoSupport standardmäßig aktiviert. Es sendet 24 Stunden nach der Aktivierung Meldungen an den technischen Support. Wenn Sie AutoSupport deaktivieren, erhalten Sie keinen proaktiven Support und keine Überwachung mehr.


NOTE: Es wird empfohlen, die AutoSupport weiterhin zu aktivieren. Das hilft, Probleme schneller zu erkennen und zu lösen. Das System erfasst AutoSupport-Informationen und speichert diese lokal, auch wenn sie deaktiviert sind. Der Bericht wird jedoch nicht an ein Netzwerk gesendet.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie die Option *Einstellungen* > *Telemetrie* > *Bearbeiten*.
. Deaktivieren Sie die Option *AutoSupport* und speichern Sie die Änderungen.

