---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords: modify ESXi host settings, ONTAP tools host configuration, VMware host tuning, ESXi settings dashboard 
summary: ESXi-Hosteinstellungen können über das ONTAP tools Dashboard bearbeitet werden. 
---
= Ändern Sie ESXi Hosteinstellungen mithilfe von ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das ONTAP tools Dashboard in VMware vSphere bietet die Möglichkeit, Konfigurationsprobleme zu identifizieren, von NetApp empfohlene Einstellungen für ausgewählte ESXi Hosts zu überprüfen und diese anzuwenden.

.Bevor Sie beginnen
Das ESXi-Hostsystem-Portlet zeigt Probleme mit den ESXi-Hosteinstellungen an.  Wählen Sie ein Problem aus, um den Hostnamen oder die IP-Adresse anzuzeigen.

.Schritte
. Melden Sie sich beim vSphere Client an.
. Auf der Seite „Shortcuts“ im Abschnitt „Plug-ins“ ist *NetApp ONTAP tools* auszuwählen.
. Zum Portlet *ESXi Host compliance* im Übersichts-Dashboard des ONTAP tools for VMware vSphere Plug-in wechseln.
. Den Link *Empfohlene Einstellungen anwenden* auswählen.
. Im Fenster *Empfohlene Host-Einstellungen anwenden* die Hosts auswählen, für die die von NetApp empfohlenen Host-Einstellungen angewendet werden sollen, und anschließend *Weiter* auswählen.
+

NOTE: Sie können den ESXi-Host erweitern, um die aktuellen Werte anzuzeigen.

. Auf der Einstellungsseite können die empfohlenen Werte nach Bedarf ausgewählt werden.
. Im Zusammenfassungsbereich die Werte überprüfen und *Fertigstellen* auswählen. Der Fortschritt kann im Bereich „Letzte Aufgaben“ verfolgt werden.


.Verwandte Informationen
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Konfigurieren Sie ESXi-Hosteinstellungen"]
