---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords: scale ONTAP tools appliance, enable high availability, ONTAP tools HA configuration, appliance scaling settings 
summary: 'Die ONTAP tools Appliance kann skaliert und Hochverfügbarkeit (HA) mithilfe von ONTAP tools Manager konfiguriert werden.' 
---
= ONTAP tools skalieren und Hochverfügbarkeit aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP tools Manager lässt sich die Appliance skalieren oder Hochverfügbarkeit (HA) konfigurieren. Standardmäßig wird ONTAP tools for VMware vSphere als Einzelknoten-Konfiguration ohne Hochverfügbarkeit bereitgestellt.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Ihre OVA-Vorlage mit der Version von Node 1 (dem initialen Bereitstellungsknoten) übereinstimmt.
* CPU-Hot-Add und Memory-Hot-Plug werden auf dem Hypervisor aktiviert. Diese Funktionen sind erforderlich, um die Appliance zu skalieren und HA zu ermöglichen. Für ONTAP tools 10.6 und höher sind diese Funktionen standardmäßig aktiviert. Bei früheren Versionen werden diese Funktionen vor dem Skalieren oder dem Aktivieren von HA aktiviert.
* Im vCenter Server den Automatisierungsgrad des Disaster Recovery Service (DRS) auf teilweise automatisiert setzen. Nach Abschluss der HA-Bereitstellung wieder auf vollständig automatisiert zurücksetzen.
+

NOTE: Die Knotengröße kann nur erhöht, nicht aber verringert werden. Besonders kleine (XS) Bereitstellungen schränken bestimmte Dienste ein.



.Schritte
. ONTAP tools Manager öffnen: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit Ihren ONTAP tools Administratoranmeldeinformationen an.
. Im Übersichtsabschnitt ist *Geräteeinstellungen bearbeiten* auszuwählen.
. Im Abschnitt *Konfiguration* die neue Knotengröße auswählen und den HA-Schalter umlegen, um Hochverfügbarkeit zu aktivieren.
. Auf der Seite *HA-Einstellungen* ist Folgendes zu überprüfen:
+
** Die Bibliothek befindet sich auf demselben vCenter Server, auf dem die ONTAP tools virtuellen Maschinen (VMs) laufen.
** Die ONTAP tools VMs werden auf einem Cluster oder Ressourcenpool bereitgestellt, nicht direkt auf einem ESXi Host.
+

IMPORTANT: Nach der Aktivierung von HA ist eine Rückkehr zu einer Einzelknoten-Konfiguration ohne HA nicht mehr möglich.



. Im Abschnitt *HA-Einstellungen* die Netzwerkdetails für die Nodes 2 und 3 eingeben. ONTAP tools unterstützt drei Nodes im HA-Modus.
+
ONTAP tools füllt die meisten Felder automatisch mit den Netzwerkeinstellungen von Node 1 aus. Diese Werte können vor Abschluss des Assistenten bearbeitet werden. IPv6-Adresseneinträge sind nur verfügbar, wenn IPv6 auf dem Management-Node aktiviert ist. Jeder ESXi Host sollte nur eine ONTAP tools VM ausführen.

. Die Zusammenfassung wird angezeigt, danach auf *Speichern* klicken.


.Ergebnis
Die Appliance beginnt mit der Skalierung und der Aktivierung von Hochverfügbarkeit. Der Fortschritt kann auf der *Übersicht*-Seite überwacht oder der Vorgang in der *Aufträge*-Ansicht anhand der Auftrags-ID verfolgt werden.

Wenn die HA-Bereitstellung mit dem Status 'Neu' fehlschlägt, die fehlgeschlagene VM in vCenter löschen und den Vorgang erneut versuchen.

Die Registerkarte *Warnungen* sollte während des Vorgangs auf etwaige Warnungen oder Probleme überprüft werden.
