---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords:  
summary: Über das Dashboard der ONTAP Tools für VMware vSphere können Sie Ihre ESXi Host-Einstellungen bearbeiten. 
---
= Ändern Sie ESXi Hosteinstellungen mithilfe von ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nutzen Sie das ONTAP -Tools-Dashboard in VMware vSphere, um Konfigurationsprobleme zu identifizieren, ESXi-Hosts auszuwählen, die von NetApp empfohlenen Einstellungen zu überprüfen und diese anzuwenden.

.Bevor Sie beginnen
Das ESXi-Hostsystem-Portlet zeigt Probleme mit den ESXi-Hosteinstellungen an.  Wählen Sie ein Problem aus, um den Hostnamen oder die IP-Adresse anzuzeigen.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie in der Übersicht (Dashboard) des ONTAP Tools for VMware vSphere Plug-ins zum Portlet *ESXi Host Compliance*.
. Wählen Sie den Link *Empfohlene Einstellungen anwenden*.
. Im Fenster *Empfohlene Hosteinstellungen anwenden* wählen Sie die Hosts aus, für die Sie die von NetApp empfohlenen Hosteinstellungen verwenden möchten, und klicken Sie auf *Weiter*.
+

NOTE: Sie können den ESXi-Host erweitern, um die aktuellen Werte anzuzeigen.

. Wählen Sie auf der Einstellungsseite die empfohlenen Werte nach Bedarf aus.
. Überprüfen Sie im Übersichtsfenster die Werte und wählen Sie *Fertig stellen*. Sie können den Fortschritt im Fenster „Letzte Aufgabe“ verfolgen.


.Verwandte Informationen
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Konfigurieren Sie ESXi-Hosteinstellungen"]
