---
permalink: manage/edit-autosupport.html 
sidebar: sidebar 
keywords: ONTAP tools AutoSupport, configure AutoSupport settings, technical support messages, appliance telemetry settings 
summary: Einstellungen für AutoSupport bei ONTAP tools konfigurieren und das Standardverhalten von Supportmeldungen überprüfen. 
---
= ONTAP tools AutoSupport-Einstellungen bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport ist standardmäßig aktiviert, wenn ONTAP tools for VMware vSphere erstmals konfiguriert werden. 24 Stunden nach der Aktivierung werden Nachrichten an den technischen Support gesendet.



[[disable-autosupport]]
== Deaktivieren Sie AutoSupport

Wenn Sie AutoSupport deaktivieren, erhalten Sie keinen proaktiven Support und keine Überwachung mehr.


NOTE: AutoSupport sollte aktiviert bleiben, da dies die Erkennung und Behebung von Problemen beschleunigt. Auch wenn AutoSupport deaktiviert ist, sammelt und speichert das System weiterhin Informationen lokal, sendet jedoch keine Berichte über das Netzwerk.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie die Option *Einstellungen* > *Telemetrie* > *Bearbeiten*.
. Deaktivieren Sie die Option *AutoSupport* und speichern Sie die Änderungen.




[[update-autosupport-proxy-url]]
== Aktualisieren Sie die AutoSupport-Proxy-URL

Aktualisieren Sie die AutoSupport -Proxy-URL, damit die AutoSupport Funktion Daten zur sicheren Übertragung über den Proxy-Server leitet.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Einstellungen* aus.
. Wählen Sie die Option *Einstellungen* > *Telemetrie* > *Bearbeiten*.
. Geben Sie eine gültige *Proxy-URL* ein und speichern Sie die Änderungen.
+
Wenn Sie AutoSupport deaktivieren, ist auch die Proxy-URL deaktiviert.


