---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: Sie können das Administratorkennwort mit dem ONTAP Tools Manager ändern. 
---
= ONTAP-Tools-Appliance-Einstellungen ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie den ONTAP Tools Manager, um die ONTAP tools for VMware vSphere Konfiguration zu skalieren, indem Sie entweder die Anzahl der Knoten erhöhen oder die Hochverfügbarkeit (HA) aktivieren.  Standardmäßig werden die ONTAP tools for VMware vSphere Appliance als Einzelknotenkonfiguration ohne Hochverfügbarkeit bereitgestellt.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Ihre OVA-Vorlage die gleiche OVA-Version wie Knoten 1 hat. Knoten 1 ist der Standardknoten, auf dem die ONTAP-Tools für VMware vSphere OVA ursprünglich bereitgestellt werden.
* Stellen Sie sicher, dass der CPU-Hot-Plug-Speicher und der Hot-Plug-Speicher aktiviert sind.
* Stellen Sie im vCenter Server die Automatisierungsstufe des Disaster Recovery Service (DRS) auf „Teilautomatisiert“ ein. Setzen Sie sie nach der HA-Bereitstellung wieder auf „Vollautomatisiert“ zurück.
* Knoten-Hostnamen im HA-Setup sollten in Kleinbuchstaben geschrieben sein.


.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie im Übersichtsbereich die Option *Geräteeinstellungen bearbeiten* aus.
. Im Abschnitt *Konfiguration* können Sie die Knotengröße erhöhen und die HA-Konfiguration aktivieren.  Verwenden Sie die Anmeldeinformationen des vCenter Servers, um Änderungen vorzunehmen.
+
In der HA-Konfiguration können Sie Details zur Inhaltsbibliothek ändern.  Geben Sie für jede Bearbeitung das Passwort an.

+

NOTE: In ONTAP tools for VMware vSphere können Sie die Knotengröße nur erhöhen, nicht jedoch verringern.  In einem Nicht-HA-Setup wird nur eine mittelgroße Konfiguration unterstützt.  In einem HA-Setup werden mittlere und große Konfigurationen unterstützt.

. Aktivieren Sie die HA-Konfiguration mit der HA-Toggle-Taste. Stellen Sie auf der Seite *HA settings* Folgendes sicher:
+
** Die Inhaltsbibliothek gehört zum gleichen vCenter Server, auf dem die ONTAP Tools-Knoten-VMs ausgeführt werden. VCenter Server-Anmeldeinformationen werden verwendet, um die OVA-Vorlage für Appliance-Änderungen zu validieren und herunterzuladen.
** Die virtuelle Maschine, die die ONTAP-Tools hostet, wird nicht direkt auf einem ESXi-Host bereitgestellt. Die VM sollte auf einem Cluster oder einem Ressourcen-Pool bereitgestellt werden.
+

NOTE: Nachdem die HA-Konfiguration aktiviert wurde, können Sie nicht mehr zu einer Einzelknotenkonfiguration ohne HA zurückkehren.



. Im Abschnitt *HA-Einstellungen* des Fensters *Appliance-Einstellungen bearbeiten* können Sie die Details der Knoten 2 und 3 eingeben. Die ONTAP Tools für VMware vSphere unterstützen drei Nodes im HA-Setup.
+

NOTE: Die ONTAP -Tools füllen die meisten Eingabefelder automatisch mit Netzwerkdetails von Knoten 1 aus, um den Arbeitsablauf zu vereinfachen.  Sie können die Eingabedaten bearbeiten, bevor Sie zur letzten Seite des Assistenten gelangen. Sie können IPv6-Adressdetails für die anderen beiden Knoten nur eingeben, wenn die IPv6-Adresse auf dem Verwaltungsknoten der ONTAP -Tools aktiviert ist.

+
Stellen Sie sicher, dass ein ESXi-Host nur eine VM mit ONTAP Tools enthält. Die Eingaben werden jedes Mal validiert, wenn Sie zum nächsten Fenster wechseln.

. Überprüfen Sie die Details im Abschnitt *Zusammenfassung* und speichern Sie die Änderungen.


.Was kommt als Nächstes?
Auf der Seite *Übersicht* wird der Status der Bereitstellung angezeigt. Sie können den Status des Auftrags „Geräteeinstellungen bearbeiten“ auch in der Auftragsansicht mithilfe der Auftrags-ID verfolgen.

Falls die HA-Bereitstellung fehlschlägt und der Status des neuen Knotens „Neu“ lautet, löschen Sie die neue VM in vCenter, bevor Sie versuchen, HA erneut zu aktivieren.

Auf der Registerkarte *Alerts* im linken Bereich werden Warnungen für ONTAP-Tools für VMware vSphere aufgelistet.
