---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords: enable ONTAP tools services, enable VASA provider, enable SRA service, vVols service configuration 
summary: 'Optionale ONTAP tools Dienste, einschließlich VASA Provider, vVols Konfigurationsimport und Disaster Recovery (SRA), können aktiviert werden.' 
---
= ONTAP tools-Dienste aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP tools Manager können optionale Dienste wie VASA Provider, vVols Konfigurationsimport und Disaster Recovery (SRA) aktiviert werden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Im Abschnitt *Übersicht* *Geräteeinstellungen bearbeiten* auswählen.
. Im Abschnitt *Dienste* können die optionalen Dienste aktiviert werden, die benötigt werden, wie VASA Provider, vVols Konfigurationsimport und Disaster Recovery (SRA).
+
Wenn diese Dienste zum ersten Mal aktiviert werden, sind VASA Provider und SRA Anmeldeinformationen zu erstellen.

+
** Verwenden Sie diese Anmeldeinformationen, um VASA Provider und SRA Services auf dem vCenter Server zu registrieren und zu aktivieren.
** Der Benutzername darf nur Buchstaben, Zahlen und Unterstriche enthalten.
** Die Passwortlänge muss zwischen 8 und 256 Zeichen liegen.





NOTE: Bevor Sie einen optionalen Dienst deaktivieren, stellen Sie sicher, dass vCenter Server-Instanzen, die von ONTAP tools verwaltet werden, diesen Dienst nicht verwenden.

Die Option *Import von vVols-Konfiguration erlauben* wird nur angezeigt, wenn der VASA Provider-Dienst aktiviert ist. Diese Option ermöglicht die vVols Datenmigration von ONTAP tools 9.x zu ONTAP tools 10.6.
