---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: expand vVols datastore, increase vVol datastore capacity, ONTAP tools vVol storage expansion, VMware virtual volumes scaling 
summary: Der vVols Datenspeicher kann aus der vCenter Objektansicht mithilfe von ONTAP tools Aktionen erweitert werden. 
---
= Einen vVols Datenspeicher in ONTAP tools erweitern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn in der vCenter-Objektansicht mit der rechten Maustaste auf das Datenspeicherobjekt geklickt wird, zeigt der Plug-in-Abschnitt die unterstützten Aktionen für ONTAP tools for VMware vSphere an. Die verfügbaren Aktionen hängen vom Datenspeichertyp und den aktuellen Privileges des Benutzers ab.


NOTE: Dieses Verfahren gilt nicht für ASA r2 System-basierte vVols Datenspeicher.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den Datastore und wählen Sie *NetApp ONTAP Tools* > *Speicher zum Datastore hinzufügen*.
. Im Fenster „Volumes erstellen oder auswählen“ können Sie entweder neue Volumes erstellen oder aus den vorhandenen Volumes auswählen. Folgen Sie den Anweisungen auf dem Bildschirm, um Ihre Auswahl zu treffen.
. Überprüfen Sie im Fenster *Summary* die Auswahl und wählen Sie *Expand*. Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.

