---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage 
summary: Migration virtueller Maschinen von NFS- und VMFS-Datenspeichern zu vVols Datenspeichern für richtlinienbasierte Verwaltung. 
---
= Migrieren Sie virtuelle Maschinen zu vVols-Datenspeichern in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können virtuelle Maschinen von NFS- oder VMFS-Datenspeichern zu Virtual Volumes (vVols) Datenspeichern migrieren, um die richtlinienbasierte VM-Verwaltung und andere vVols Funktionen zu nutzen.

.Bevor Sie beginnen
Stellen Sie sicher, dass der VASA Provider auf keiner der virtuellen Maschinen ausgeführt wird, die Sie migrieren möchten. Wenn eine virtuelle Maschine, auf der der VASA Provider ausgeführt wird, auf einen vVols Datenspeicher migriert wird, sind keine Verwaltungsoperationen möglich, einschließlich des Einschaltens der virtuellen Maschinen, die sich auf vVols Datenspeichern befinden.

.Über diese Aufgabe
Bei der Migration von einem NFS- oder VMFS-Datenspeicher zu einem vVols-Datenspeicher verwendet der vCenter Server vStorage APIs for Array Integration (VAAI)-Offloads für Daten, die von VMFS-Datenspeichern verschoben werden, jedoch nicht für Daten, die von NFS-VMDK-Dateien verschoben werden. VAAI-Offloads reduzieren üblicherweise die Hostlast.

.Schritte
. Klicken Sie mit der rechten Maustaste auf die virtuelle Maschine, die Sie migrieren möchten, und wählen Sie *Migrate*.
. Wählen Sie *nur Speicher ändern* und dann *Weiter*.
. Wählen Sie ein virtuelles Datenträgerformat, eine VM-Speicherrichtlinie und einen vVol-Datenspeicher aus, der den Funktionen des Datenspeichers entspricht, den Sie migrieren.
. Überprüfen Sie die Einstellungen und wählen Sie *Fertig stellen*.

