---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten einige der Überlegungen bei der Migration von vorhandenen virtuellen Maschinen in Ihrem Rechenzentrum kennen. 
---
= Überlegungen zur Migration und zum Klonen virtueller Maschinen für ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Migration bestehender virtueller Maschinen in Ihrem Rechenzentrum sollten Sie einige Überlegungen beachten.



== Migrieren Sie geschützte Virtual Machines

Sie können die geschützten virtuellen Maschinen migrieren in:

* Derselbe VVols-Datastore auf einem anderen ESXi-Host
* Unterschiedliche kompatible VVols-Datastores auf demselben ESXi-Host
* Unterschiedliche kompatible VVols-Datastores auf einem anderen ESXi-Host


Wenn Sie die virtuelle Maschine auf ein anderes FlexVol volume migrieren, aktualisiert das System die Metadatendatei für dieses Volume mit den Informationen zur virtuellen Maschine. Wenn eine virtuelle Maschine auf einen anderen ESXi-Host, aber denselben Speicher migriert wird, wird die zugrunde liegende Metadatendatei des FlexVol volume nicht geändert.



== Klonen geschützter Virtual Machines

Sie können geschützte Virtual Machines folgendermaßen klonen:

* Derselbe Container desselben FlexVol Volumes mithilfe der Replizierungsgruppe
+
Die Metadatendatei dieses FlexVol Volume wird mit den geklonten Virtual Machines aktualisiert.

* Derselbe Container eines anderen FlexVol Volumes unter Verwendung der Replizierungsgruppe
+
Das FlexVol Volume, auf dem die geklonte Virtual Machine gespeichert wird, wird die Metadatendatei mit den Details der geklonten Virtual Machine aktualisiert.

* Unterschiedlicher Container oder VVols Datastore
+
Dem FlexVol Volume, auf dem die geklonte Virtual Machine gespeichert wird, werden die Metadatendatei die Details der Virtual Machine aktualisiert.



VMware unterstützt derzeit keine virtuellen Maschinen, die in eine VM-Vorlage geklont wurden.

Der Klon einer geschützten Virtual Machine wird unterstützt.

Weitere Informationen finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Erstellen einer virtuellen Maschine zum Klonen"].



== Snapshots Von Virtual Machines

Derzeit werden nur Snapshots virtueller Maschinen ohne Speicher unterstützt. Wenn auf einer virtuellen Maschine Snapshot mit Arbeitsspeicher vorhanden ist, wird die virtuelle Maschine nicht als Schutz betrachtet.

Sie können auch keine ungeschützten virtuellen Maschinen schützen, die über einen Speicher-Snapshot verfügen.  Bei dieser Version müssen Sie den Speicher-Snapshot löschen, bevor Sie den Schutz für die virtuelle Maschine aktivieren.

Bei einer Windows-VM mit dem Speichertyp ASA r2 ist ein Snapshot der virtuellen Maschine schreibgeschützt.  Beim Einschalten der VM erstellt der VASA Provider eine LUN aus dem schreibgeschützten Snapshot und aktiviert IOPS.  Wenn Sie die VM ausschalten, löscht der VASA Provider die LUN und deaktiviert IOPS.
