---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords: virtual machine migration considerations, ONTAP tools VM cloning guidance, VMware storage vMotion considerations, VM migration best practices 
summary: Wichtige Aspekte sollten vor der Migration bestehender virtueller Maschinen in Ihrem Rechenzentrum berücksichtigt werden. 
---
= Migration und Klonen virtueller Maschinen in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überlegungen zur Migration und zum Klonen virtueller Maschinen für ONTAP tools for VMware vSphere, einschließlich Compute-only (vMotion), Storage-only (Storage vMotion) und kombinierter Compute- und Storage-Migration über unterstützte Datenspeichertypen hinweg.



[[migrate-protected-virtual-machines]]
== Migrieren Sie geschützte Virtual Machines

Sie können geschützte virtuelle Maschinen migrieren zu:

* Derselbe Datenspeicher auf einem anderen ESXi-Host
* Ein anderer kompatibler Datenspeicher auf demselben ESXi-Host
* Ein anderer kompatibler Datenspeicher auf einem anderen ESXi-Host


Wenn die virtuelle Maschine auf ein anderes FlexVol volume migriert wird, aktualisiert das System die Metadatendatei dieses Volumes mit den Informationen der virtuellen Maschine. Wenn eine virtuelle Maschine auf einen anderen ESXi-Host, aber auf denselben Speicher migriert wird, wird die zugrunde liegende FlexVol volume Metadatendatei nicht geändert.

Informationen zur Migration virtueller Maschinen sind unter https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] zu finden



[[clone-protected-virtual-machines]]
== Klonen geschützter Virtual Machines

Sie können geschützte Virtual Machines folgendermaßen klonen:

* Derselbe Container desselben FlexVol volume unter Verwendung einer Replikationsgruppe
+
ONTAP tools aktualisiert die Metadatendatei desselben FlexVol volume mit den Details der geklonten virtuellen Maschine.

* Derselbe Container eines anderen FlexVol volume unter Verwendung einer Replikationsgruppe
+
Im FlexVol volume, in dem die geklonte virtuelle Maschine platziert ist, aktualisieren die ONTAP tools die Metadatendatei mit den Details der geklonten virtuellen Maschine.

* Ein anderer Container oder vVols Datenspeicher
+
Im FlexVol volume, in dem die geklonte virtuelle Maschine platziert ist, aktualisieren die ONTAP tools die Metadatendatei mit den Details der virtuellen Maschine.



VMware unterstützt derzeit keine virtuellen Maschinen, die auf eine VM-Template geklont wurden.

Das Klonen eines Klons einer geschützten virtuellen Maschine wird unterstützt.

Weitere Einzelheiten finden Sie in der Broadcom-Dokumentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Erstellen einer virtuellen Maschine zum Klonen"].



[[virtual-machine-snapshots]]
== Snapshots virtueller Maschinen

ONTAP tools unterstützt Snapshots virtueller Maschinen über standardmäßige VMware-Workflows. Snapshots sind kurzfristige Wiederherstellungspunkte, die für Anwendungsfälle wie Tests und Patch-Vorbereitung vorgesehen sind. Sie sind kein Ersatz für Backup oder replikationsbasierte Datensicherung. Der Betrieb einer virtuellen Maschine auf einem Snapshot über längere Zeiträume kann zu Instabilität und Datenverlust führen.

Sie können absturzkonsistente Snapshots (Snapshots ohne Speicherzustand, mit denen die virtuelle Maschine in einen konsistenten Zustand neu gestartet werden kann) auf allen unterstützten Datenspeichertypen erstellen. Auch quiesced Snapshots, die VMware Tools verwenden, um die Daten im Arbeitsspeicher vor der Erfassung auf die Festplatte zu schreiben, werden unterstützt. Eine Übersicht über Snapshot-Typen und deren Verhalten finden Sie unter https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"].


NOTE: Speicher-Snapshots erfassen den aktuellen Speicherzustand und führen zu einer temporären Unterbrechung der virtuellen Maschine. Sie werden in ONTAP tools Workflows nicht unterstützt. Wenn eine virtuelle Maschine über einen Speicher-Snapshot verfügt, muss dieser gelöscht werden, bevor die virtuelle Maschine in eine Konsistenzgruppe oder eine Host-Cluster-Beziehung aufgenommen werden kann, die von ONTAP tools verwaltet wird.

Auf ASA r2-Speichersystemen unterscheidet sich das Verhalten von VM-Snapshots von anderen Speichertypen. Snapshots sind schreibgeschützt. Beim Einschalten der virtuellen Maschine erstellt der VASA Provider eine LUN aus dem schreibgeschützten Snapshot und aktiviert IOPS. Beim Ausschalten der virtuellen Maschine löscht der VASA Provider die LUN und deaktiviert IOPS.

Informationen zur Verwaltung von Snapshots virtueller Maschinen sind unter  https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] zu finden.
