---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage 
summary: Migration virtueller Maschinen von NFS- und VMFS-Datenspeichern zu vVols Datenspeichern für richtlinienbasierte Verwaltung. 
---
= Migrieren Sie virtuelle Maschinen zu vVols-Datenspeichern in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Virtual Machines von NFS- und VMFS-Datastores auf Virtual Volumes (VVols) Datastores migrieren, um die Vorteile des richtlinienbasierten VM-Managements und anderer VVols Funktionen zu nutzen. VVols Datastores ermöglichen es, steigende Workload-Anforderungen zu erfüllen.

.Bevor Sie beginnen
Stellen Sie sicher, dass der VASA Provider auf keiner der virtuellen Maschinen ausgeführt wird, die Sie migrieren möchten. Wenn eine virtuelle Maschine, auf der der VASA Provider ausgeführt wird, auf einen vVols Datenspeicher migriert wird, sind keine Verwaltungsoperationen möglich, einschließlich des Einschaltens der virtuellen Maschinen, die sich auf vVols Datenspeichern befinden.

.Über diese Aufgabe
Bei der Migration von einem NFS- und VMFS-Datastore zu einem VVols-Datastore verwendet vCenter Server vStorage APIs for Array Integration (VAAI), wenn Daten aus VMFS-Datastores, nicht jedoch aus einer NFS VMDK-Datei verschoben werden. VAAI-Entlastung verringert normalerweise die Last des Hosts.

.Schritte
. Klicken Sie mit der rechten Maustaste auf die virtuelle Maschine, die Sie migrieren möchten, und wählen Sie *Migrate*.
. Wählen Sie *nur Speicher ändern* und dann *Weiter*.
. Wählen Sie ein virtuelles Datenträgerformat, eine VM-Speicherrichtlinie und einen vVol-Datenspeicher aus, der den Funktionen des Datenspeichers entspricht, den Sie migrieren.
. Überprüfen Sie die Einstellungen und wählen Sie *Fertig stellen*.

