---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Bei der Migration bestehender virtueller Maschinen in Ihrem Rechenzentrum sollten Sie einige Punkte beachten. 
---
= Überlegungen zur Migration und zum Klonen virtueller Maschinen für ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools für VMware vSphere unterstützen alle gängigen Arten der virtuellen Maschinenmigration, einschließlich reiner Compute- (vMotion), reiner Storage- (Storage vMotion) und kombinierter Compute- und Storage-Migration über alle Datenspeicher hinweg. In diesem Abschnitt werden wichtige Aspekte und Best Practices für eine erfolgreiche Migration und das Klonen von virtuellen Maschinen unabhängig vom zugrunde liegenden Datenspeichertyp erläutert.



== Migrieren Sie geschützte Virtual Machines

Sie können geschützte virtuelle Maschinen migrieren zu:

* Derselbe Datenspeicher auf einem anderen ESXi-Host
* Ein anderer kompatibler Datenspeicher auf demselben ESXi-Host
* Ein anderer kompatibler Datenspeicher auf einem anderen ESXi-Host


Wenn Sie die virtuelle Maschine auf ein anderes FlexVol volume migrieren, aktualisiert das System die Metadatendatei dieses Volumes mit den Informationen der virtuellen Maschine. Wird eine virtuelle Maschine auf einen anderen ESXi-Host, aber auf denselben Speicher migriert, wird die zugrunde liegende FlexVol volume-Metadatendatei nicht geändert.

Informationen zur Migration virtueller Maschinen finden Sie in der Broadcom-Dokumentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html["vSphere Migration virtueller Maschinen"]



== Klonen geschützter Virtual Machines

Sie können geschützte Virtual Machines folgendermaßen klonen:

* Derselbe Container desselben FlexVol volume unter Verwendung einer Replikationsgruppe
+
Die Metadatendatei desselben FlexVol volumes wird mit den Details der geklonten virtuellen Maschine aktualisiert.

* Derselbe Container eines anderen FlexVol volume unter Verwendung einer Replikationsgruppe
+
Im FlexVol volume, in dem die geklonte virtuelle Maschine abgelegt ist, wird die Metadatendatei mit den Details der geklonten virtuellen Maschine aktualisiert.

* Ein anderer Container oder vVols Datenspeicher
+
Im FlexVol volume, in dem die geklonte virtuelle Maschine platziert ist, wird die Metadatendatei mit den Details der virtuellen Maschine aktualisiert.



VMware unterstützt derzeit keine virtuellen Maschinen, die auf eine VM-Vorlage geklont wurden.

Das Klonen eines Klons einer geschützten virtuellen Maschine wird unterstützt.

Weitere Einzelheiten finden Sie in der Broadcom-Dokumentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Erstellen einer virtuellen Maschine zum Klonen"].



== Snapshots virtueller Maschinen

ONTAP tools unterstützt Snapshots virtueller Maschinen über standardmäßige VMware-Workflows. Snapshots sind kurzfristige Wiederherstellungspunkte, die für Anwendungsfälle wie Tests und Patch-Vorbereitung vorgesehen sind. Sie sind kein Ersatz für Backup oder replikationsbasierte Datensicherung. Der Betrieb einer virtuellen Maschine auf einem Snapshot über längere Zeiträume kann zu Instabilität und Datenverlust führen.

Sie können absturzkonsistente Snapshots (Snapshots ohne Speicherzustand, mit denen die virtuelle Maschine in einen konsistenten Zustand neu gestartet werden kann) auf allen unterstützten Datenspeichertypen erstellen. Auch quiesced Snapshots, die VMware Tools verwenden, um die Daten im Arbeitsspeicher vor der Erfassung auf die Festplatte zu schreiben, werden unterstützt. Eine Übersicht über Snapshot-Typen und deren Verhalten finden Sie unter https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html["Übersicht über Snapshots virtueller Maschinen in vSphere"].


NOTE: Speicher-Snapshots erfassen den aktuellen Speicherzustand und führen zu einer temporären Unterbrechung der virtuellen Maschine. Sie werden in ONTAP tools Workflows nicht unterstützt. Wenn eine virtuelle Maschine über einen Speicher-Snapshot verfügt, muss dieser gelöscht werden, bevor die virtuelle Maschine in eine Konsistenzgruppe oder eine Host-Cluster-Beziehung aufgenommen werden kann, die von ONTAP tools verwaltet wird.

Auf ASA r2-Speichersystemen unterscheidet sich das Verhalten von VM-Snapshots von anderen Speichertypen. Snapshots sind schreibgeschützt. Beim Einschalten der virtuellen Maschine erstellt der VASA Provider eine LUN aus dem schreibgeschützten Snapshot und aktiviert IOPS. Beim Ausschalten der virtuellen Maschine löscht der VASA Provider die LUN und deaktiviert IOPS.

Informationen zur Verwaltung von Snapshots virtueller Maschinen finden Sie in der Broadcom-Dokumentation https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html["Virtuelle Maschinen mit Snapshots verwalten"].
