---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: Datenspeicher auf zusätzlichen Hosts einbinden, nachdem Hosts zur VMware-Umgebung hinzugefügt wurden. 
---
= NFS- und VMFS-Datenspeicher in ONTAP tools einbinden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Mounten eines Datenspeichers können zusätzliche Hosts auf den Speicher zugreifen. Nachdem Sie die Hosts der VMware Umgebung hinzugefügt haben, können Sie den Datastore auf den zusätzlichen Hosts einbinden.


NOTE: Nach dem Hinzufügen des Hosts sollte abgewartet werden, bis die geplante Host-Erkennung abgeschlossen ist, bevor er in ONTAP tools angezeigt wird. Alternativ kann die Erkennung manuell über die Übersicht der NetApp ONTAP tools ausgeführt werden. Informationen zum Hinzufügen eines ESXi Hosts zu Ihrem vSphere Cluster sind unter  https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] zu finden.

.Über diese Aufgabe
* Einige Rechtsklick-Aktionen sind abhängig von der vSphere-Client-Version und dem ausgewählten Datastore-Typ deaktiviert oder nicht verfügbar.
+
** Wenn Sie vSphere Client 8.0 oder höher verwenden, sind einige der Optionen mit der rechten Maustaste ausgeblendet.
** Von vSphere 7.0U3 bis vSphere 8.0, obwohl die Optionen angezeigt werden, wird die Aktion deaktiviert.


* vSphere deaktiviert die Option "Mount Datastore", wenn der Host-Cluster mit einheitlichen Konfigurationen geschützt ist.
* Wenn ein Datenspeicher mit nconnect auf einem neuen Host eingebunden wird, wenden die ONTAP tools den nconnect-Wert des Datenspeichers an, falls dieser den Wert des Hosts überschreitet.


.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im linken Navigationsbereich die Rechenzentren aus, die die Hosts enthalten.
. Um NFS/VMFS-Datenspeicher auf einem Host oder einem Hostcluster einzubinden, klicken Sie mit der rechten Maustaste und wählen Sie * NetApp ONTAP Tools* > *Datenspeicher einbinden*.
. Wählen Sie die Datenspeicher aus, die Sie mounten möchten, und wählen Sie *Mount*.


.Was kommt als Nächstes?
Sie können den Fortschritt im Fenster „Letzte Aufgabe“ verfolgen.

.Verwandtes Thema
link:../manage/add-vsphere-host.html["Neue VMware vSphere-Hosts hinzufügen"]
