---
permalink: manage/mount-a-vvols-datastore.html 
sidebar: sidebar 
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount 
summary: Einen vVols Datenspeicher auf zusätzliche Hosts einbinden, um Speicherzugriff in der gesamten virtuellen Umgebung bereitzustellen. 
---
= Einen vVols-Datenspeicher in ONTAP tools einbinden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein VMware Virtual Volumes (vVols) Datenspeicher kann auf einem oder mehreren zusätzlichen Hosts eingebunden werden, um diesen zusätzlichen Hosts Speicherzugriff bereitzustellen. Ein vVols Datenspeicher kann nur über Host-APIs ausgehängt werden. Das Aushängen eines Datenspeichers auf Cluster-Ebene wird nicht unterstützt.


NOTE: Nach dem Hinzufügen des Hosts sollte abgewartet werden, bis die geplante Host-Erkennung abgeschlossen ist, bevor er in ONTAP tools angezeigt wird. Alternativ kann die Erkennung manuell über die Übersicht der NetApp ONTAP tools ausgeführt werden. Informationen zum Hinzufügen eines ESXi Hosts zu Ihrem vSphere Cluster sind unter  https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] zu finden.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den Datastore und wählen Sie *NetApp ONTAP Tools* > *Datastore mounten*.
. Wählen Sie im Dialogfeld *Datastores auf Hosts mounten* die Hosts aus, auf denen Sie den Datastore mounten möchten, und wählen Sie dann *Mount* aus.


Im Bereich „Letzte Aufgaben“ wird der Fortschritt angezeigt.

.Verwandtes Thema
link:../manage/add-vsphere-host.html["Neue VMware vSphere-Hosts hinzufügen"]
