---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down 
summary: Einen vVols Datenspeicher nur löschen, wenn keine vVols mehr auf dem ausgewählten Datenspeicher vorhanden sind. 
---
= Einen vVols Datenspeicher in ONTAP tools verkleinern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Aktion „Speicher aus Datenspeicher entfernen“ entfernt Volumes aus einem vVols Datenspeicher in ONTAP tools und verringert dessen Kapazität, wenn der zusätzliche Speicher nicht mehr benötigt wird.

Verwenden Sie die Aktion "Speicher aus Datenspeicher entfernen" für jeden vVols -Datenspeicher, der von ONTAP Tools in vCenter Server verwaltet wird.

Sie können keinen Speicher aus einem Volume entfernen, wenn es vVols enthält; die Option zum Entfernen ist für solche Volumes deaktiviert. Beim Entfernen von Volumes aus dem Datenspeicher besteht außerdem die Möglichkeit, die ausgewählten Volumes aus dem ONTAP Speicher zu löschen.


NOTE: Der Vorgang zum Verkleinern von vVols Datenspeichern wird für vVols Datenspeicher, die auf ASA R2-Systemen basieren, nicht unterstützt.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den vVol Datastore und wählen Sie *NetApp ONTAP Tools* > *Speicher aus Datastore entfernen*.
. Wählen Sie die Volumes aus, die keine vVols haben, und wählen Sie *Entfernen*.
+

NOTE: Die Option zur Auswahl des Volumes, auf dem vVols liegen, ist deaktiviert.

. Im Popup *Speicher entfernen* die Checkbox *Volumes aus ONTAP Cluster löschen* aktivieren, um die Volumes aus dem Datenspeicher und aus dem ONTAP Storage zu löschen, und *Löschen* auswählen.

