---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: Remove vVol datastore 
summary: Mit der Aktion „Datastore löschen“ wird der Datastore gelöscht, wenn sich keine VVols auf dem ausgewählten Datastore befinden. 
---
= VVols Datastore verkleinern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Seite erklärt, wie man Volumes aus einem vVols -Datenspeicher entfernt.

Verwenden Sie die Aktion "Speicher aus Datenspeicher entfernen" für jeden vVols -Datenspeicher, der von ONTAP Tools in vCenter Server verwaltet wird.

Sie können keinen Speicher von einem Volume entfernen, wenn es vVols enthält. Die Option zum Entfernen wird für solche Volumes deaktiviert.  Beim Entfernen von Volumes aus dem Datenspeicher haben Sie auch die Möglichkeit, die ausgewählten Volumes aus dem ONTAP Speicher zu löschen.


NOTE: Der Vorgang zum Verkleinern von vVols Datenspeichern wird für vVols Datenspeicher, die auf ASA R2-Systemen basieren, nicht unterstützt.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den vVol Datastore und wählen Sie *NetApp ONTAP Tools* > *Speicher aus Datastore entfernen*.
. Wählen Sie die Volumes aus, die keine vVols haben, und wählen Sie *Entfernen*.
+

NOTE: Die Option zum Auswählen des Volumes, auf dem sich vVols befindet, ist deaktiviert.

. Aktivieren Sie im Popup-Fenster *Speicher entfernen* das Kontrollkästchen *Volumes aus ONTAP-Cluster löschen*, um die Volumes aus dem Datastore und aus dem ONTAP-Speicher zu löschen, und wählen Sie *Löschen* aus.

