---
permalink: manage/reports.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für das VMware vSphere Plug-in bieten Berichte für Virtual Machines und Datastores. 
---
= Berichte zu ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für das VMware vSphere Plug-in bieten Berichte für Virtual Machines und Datastores. Wenn Sie im Abschnitt „Verknüpfungen“ des vCenter-Clients das Symbol „NetApp ONTAP-Tools für VMware vSphere“ auswählen, wechselt die Benutzeroberfläche zur Seite „Übersicht“. Wählen Sie die Registerkarte Berichte aus, um die virtuelle Maschine und den Bericht Datastores anzuzeigen.

Der Bericht „Virtuelle Maschinen“ zeigt die Liste der erkannten virtuellen Maschinen (sollte mindestens eine Festplatte aus ONTAP Speicher-basierten Datenspeichern haben) mit Leistungsmetriken. Wenn Sie den VM-Datensatz erweitern, zeigt die Benutzeroberfläche alle datenspeicherbezogenen Informationen zum Datenträger an.

Der Datenspeicherbericht listet die von ONTAP tools for VMware vSphere erkannten oder identifizierten Datenspeicher auf, die ONTAP -Speicher verwenden, und gibt Leistungskennzahlen an.

Mit der Option Spalten verwalten können Sie verschiedene Spalten ein- oder ausblenden.
