---
permalink: manage/reports.html 
sidebar: sidebar 
keywords: ONTAP tools reports, virtual machine reports, datastore reports, VMware storage reporting 
summary: Berichte zu virtuellen Maschinen und Datenspeichern sind im ONTAP tools Plug-in verfügbar. 
---
= ONTAP tools für VMware vSphere Berichte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das ONTAP tools for VMware vSphere Plug-in stellt Berichte bereit, die bei der Überwachung von virtuellen Maschinen und Datenspeichern unterstützen, die durch ONTAP Storage bereitgestellt werden. Diese Berichte sind über das ONTAP tools for VMware vSphere Plug-in-Symbol im Bereich „Verknüpfungen“ des vCenter Clients und anschließend über die Registerkarte „Berichte“ zugänglich.

Der Bericht „Virtuelle Maschinen“ listet entdeckte virtuelle Maschinen auf, die mindestens eine Festplatte auf einem ONTAP Storage-basierten Datenspeicher haben, zusammen mit Leistungskennzahlen. Beim Erweitern des VM-Eintrags zeigt die Oberfläche alle festplattenbezogenen Datenspeicherinformationen an.

Der Datenspeicherbericht listet die Datenspeicher auf, die ONTAP tools for VMware vSphere erkennt und die ONTAP Storage verwenden, zusammen mit Leistungskennzahlen.

Mit der Option Spalten verwalten können Sie verschiedene Spalten ein- oder ausblenden.
