---
permalink: manage/reset-vasa-sra-credentials.html 
sidebar: sidebar 
keywords:  
summary: Geben Sie die NTP-Serverdetails ein, um die Zeituhren der ONTAP Tools-Appliance zu synchronisieren. 
---
= Setzen Sie die VASA-Provider- und SRA-Anmeldeinformationen zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihre VASA-Provider- oder SRA-Anmeldeinformationen vergessen, können Sie sie mithilfe der ONTAP Tools Manager-Schnittstelle auf ein neues Kennwort zurücksetzen.  Das neue Passwort muss zwischen 8 und 256 Zeichen lang sein.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie die Option *Einstellungen* > *VASA-Anbieter-/SRA-Anmeldeinformationen* > *Passwort zurücksetzen*.
. Geben Sie das neue Passwort ein und bestätigen Sie es.
. Wählen Sie *Speichern*, um die Änderungen zu übernehmen.

