---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords: reset ONTAP tools Manager password, manager admin credential recovery, token-based password reset, appliance administrator reset 
summary: ONTAP tools Manager Administratoranmeldeinformationen mithilfe eines Wartungskonsolentokens zurücksetzen. 
---
= Das Passwort des ONTAP tools Manager zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie das Passwort des ONTAP Tools Managers vergessen haben, können Sie den Administratorzugriff wiederherstellen, indem Sie ein Reset-Token verwenden, das von der ONTAP tools for VMware vSphere Wartungskonsole generiert wurde.

.Schritte
. Einen Webbrowser öffnen und zu  `https://<ONTAPtoolsIP>:8443/virtualization/ui/` wechseln, um ONTAP tools Manager zu öffnen.
. Wählen Sie auf der Anmeldeseite die Option *Passwort zurücksetzen*.
. Generieren Sie ein Token zum Zurücksetzen des Kennworts mithilfe der ONTAP tools for VMware vSphere Wartungskonsole:
+
.. Melden Sie sich beim vCenter Server an.
.. Die ONTAP tools VM suchen und die Webkonsole öffnen.
.. Melden Sie sich mit den  `maint` Zugangsdaten an.
.. Eingeben `2` Um die *Systemkonfiguration* auszuwählen, wählen Sie diese bitte aus.
.. Geben Sie  `3` ein, um *Token zum Zurücksetzen des Manager-UI-Passworts generieren* auszuwählen, und notieren Sie das Token.


. Geben Sie im Dialogfeld zum Zurücksetzen des Passworts das Reset-Token, den Benutzernamen und das neue Passwort ein.
. Wählen Sie *Zurücksetzen*, um die Anmeldeinformationen zu aktualisieren.
. Melden Sie sich mit dem neuen Passwort beim ONTAP Tools Manager an.

