---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie das Passwort für den ONTAP Tools Manager vergessen haben, können Sie die Administratoranmeldedaten mithilfe des Tokens zurücksetzen, das von den ONTAP Tools für die VMware vSphere-Wartungskonsole generiert wurde. 
---
= Kennwort des ONTAP Tools Managers zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie das Passwort des ONTAP Tools Managers vergessen haben, können Sie den Administratorzugriff wiederherstellen, indem Sie ein Reset-Token verwenden, das von der ONTAP tools for VMware vSphere Wartungskonsole generiert wurde.

.Schritte
. Öffnen Sie einen Webbrowser und navigieren Sie zu `https://<ONTAPtoolsIP>:8443/virtualization/ui/` um auf den ONTAP Tools Manager zuzugreifen.
. Wählen Sie auf der Anmeldeseite die Option *Passwort zurücksetzen*.
. Generieren Sie ein Token zum Zurücksetzen des Kennworts mithilfe der ONTAP tools for VMware vSphere Wartungskonsole:
+
.. Melden Sie sich beim vCenter Server an und öffnen Sie die Wartungskonsole.
.. Eingeben `2` Um die *Systemkonfiguration* auszuwählen, wählen Sie diese bitte aus.
.. Eingeben `3` *Passwort des Wartungsbenutzers ändern*.


. Geben Sie im Dialogfeld zum Zurücksetzen des Passworts das Reset-Token, den Benutzernamen und das neue Passwort ein.
. Wählen Sie *Zurücksetzen*, um die Anmeldeinformationen zu aktualisieren.
. Melden Sie sich mit dem neuen Passwort beim ONTAP Tools Manager an.

