---
permalink: manage/resize-datastores.html 
sidebar: sidebar 
keywords:  
summary: Durch die Größenänderung eines Datenspeichers können Sie den Speicher für die Dateien Ihrer virtuellen Maschine erhöhen. Sie können die Größe eines Datastores ändern, wenn sich Ihre Infrastrukturanforderungen ändern. 
---
= NFS- und VMFS-Datenspeicher in ONTAP tools vergrößern/verkleinern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Größenänderung eines Datenspeichers können Sie den Speicher für die Dateien Ihrer virtuellen Maschine erhöhen. Sie können die Größe eines Datastores ändern, wenn sich Ihre Infrastrukturanforderungen ändern.

.Über diese Aufgabe
Sie können die Größe von NFS- und VMFS-Datenspeichern erhöhen.  Ein FlexVol volume in diesen Datenspeichern kann nicht unter seine aktuelle Größe verkleinert werden, aber auf bis zu 120 % anwachsen.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den NFS- oder VMFS-Datastore und wählen Sie *NetApp ONTAP Tools* > *Datastore skalieren* aus.
. Geben Sie im Dialogfeld „Größe ändern“ eine neue Größe für den Datenspeicher ein und wählen Sie *OK*.

