---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Storage-Back-Ends sind Systeme, die die ESXi Hosts zum Speichern von Daten verwenden. 
---
= Managen von Storage-Back-Ends
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Back-Ends sind Systeme, die die ESXi Hosts zum Speichern von Daten verwenden.



== Storage erkennen

Sie können die Erkennung eines Speicher-Backends bei Bedarf ausführen, ohne auf eine geplante Erkennung warten zu müssen, um die Speicherdetails sofort zu aktualisieren.  Führen Sie bei MetroCluster -Konfigurationen die Erkennung der ONTAP Tools nach einem Switchover manuell aus.

Führen Sie die folgenden Schritte aus, um die Speicher-Back-Ends zu ermitteln.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Wählen Sie das Menü Vertikale Ellipsen und dann *Speicher entdecken*


Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.



== Speicherbackends ändern

Sie können die Anmeldeinformationen des Speicher-Backends oder den Portnamen ändern.  Sie können das Speicher-Backend für globale ONTAP Cluster auch mit dem ONTAP Tools Manager ändern.  Wenn das Zertifikat in 30 Tagen oder weniger abläuft, zeigen die ONTAP Tools eine Warnung an.  Ändern Sie das Speicher-Backend und laden Sie das neue Zertifikat vom ONTAP Administrator hoch.

Wenn Sie das Speicher-Backend ändern, führen ONTAP tools for VMware vSphere eine Erkennung des Speicher-Backends durch, um die Speicherdetails zu aktualisieren.

Befolgen Sie die Schritte in diesem Abschnitt, um ein Speicher-Back-End zu ändern.

. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Wählen Sie das vertikale Ellipsenmenü aus und wählen Sie *Ändern*, um die Anmeldeinformationen oder den Anschlussnamen zu ändern. Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.


Ändern Sie globale ONTAP Cluster mit dem ONTAP -Tools-Manager wie folgt.

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste Speicher-Back-Ends aus.
. Wählen Sie das zu ändernde Speicher-Back-End aus.
. Wählen Sie das Menü Vertikale Ellipsen und dann *Ändern*.
. Sie können die Anmeldeinformationen oder den Port ändern. Geben Sie den *Username* und das *Passwort* ein, um das Speicher-Backend zu ändern.




== Entfernen Sie die Speicher-Back-Ends

Sie müssen alle an das Speicher-Backend angeschlossenen Datenspeicher entfernen, bevor Sie es entfernen.  Führen Sie die folgenden Schritte aus, um ein Speicher-Backend zu entfernen.

. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Wählen Sie das vertikale Auslassungsmenü und wählen Sie *Entfernen*.  Stellen Sie sicher, dass das Speicher-Backend keine Datenspeicher enthält.  Sie können den Fortschritt im Bereich „Letzte Aufgaben“ verfolgen.


Sie können den Vorgang zum Entfernen globaler ONTAP-Cluster mit dem ONTAP-Tools-Manager ausführen.

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Wählen Sie das Storage-Backend aus, das Sie entfernen möchten
. Wählen Sie das Menü Vertikale Ellipsen und dann *Entfernen*.




== Drilldown-Ansicht des Storage-Back-End

Auf der Speicher-Backend-Seite sind alle Speicher-Backends aufgelistet.  Sie können Vorgänge zum Erkennen, Ändern und Entfernen von Speicher auf den von Ihnen hinzugefügten Speicher-Backends ausführen, jedoch nicht auf den einzelnen untergeordneten SVMs unter dem Cluster.

Wählen Sie den übergeordneten oder untergeordneten Cluster aus, um die Komponentenübersicht anzuzeigen.  Verwenden Sie für den übergeordneten Cluster das Dropdown-Menü „Aktionen“, um Speicher zu ermitteln und das Speicher-Backend zu ändern oder zu entfernen.

Die Übersichtsseite enthält folgende Details:

* Status des Storage-Backends
* Kapazitätsinformationen
* Grundlegende Informationen zur VM
* Zertifikatsdetails wie Zertifikatsstatus und Ablaufdatum.
* Netzwerkinformationen wie IP-Adresse und Port des Netzwerks.  Für die untergeordnete SVM sind die Informationen dieselben wie für das übergeordnete Speicher-Backend.
* Erlaubte und eingeschränkte Privileges für das Speicher-Backend.  Für die untergeordnete SVM sind die Informationen dieselben wie für das übergeordnete Speicher-Backend.  ONTAP -Tools zeigen Berechtigungen nur für die clusterbasierten Speicher-Backends an.  Wenn Sie SVM als Speicher-Backend hinzufügen, werden keine Berechtigungsinformationen angezeigt.
* Die Drilldown-Ansicht des ASA R2-Systemclusters enthält keine Registerkarte „Lokale Ebenen“, wenn die disaggregierte Eigenschaft für die SVM oder den Cluster auf „true“ gesetzt ist.
* Bei ASA r2 SVM-Systemen wird das Portlet „Capacity“ nicht angezeigt. Das Kapazitätsportal ist nur erforderlich, wenn die disaggregierte Eigenschaft für die SVM oder den Cluster als „true“ festgelegt ist.
* Für ASA r2 SVM-Systeme wird im Abschnitt grundlegende Informationen der Plattformtyp angezeigt.


Die Registerkarte Schnittstelle enthält detaillierte Informationen zur Schnittstelle.

Auf der Registerkarte „Lokale Ebenen“ finden Sie detaillierte Informationen zur Aggregatliste.
