---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords: manage storage backends, ONTAP backend systems, storage backend operations, VMware datastore backend configuration 
summary: Speicher-Backends verwalten, die ESXi-Hosts für die Datenspeicherung verwenden. 
---
= Speicher-Backends in ONTAP tools verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Backends sind Systeme, die ESXi-Hosts zur Datenspeicherung verwenden. Storage-Backends lassen sich mit ONTAP tools for VMware vSphere ermitteln, ändern und entfernen.



[[discover-storage]]
== Storage erkennen

Sie können die Speicher-Backend-Erkennung bedarfsgesteuert ausführen, anstatt auf die nächste geplante Erkennung zur Aktualisierung der Speicherdetails zu warten. Für MetroCluster Konfigurationen sollte die ONTAP tools-Erkennung nach einem Switchover manuell ausgeführt werden.

Führen Sie die folgenden Schritte aus, um die Speicher-Back-Ends zu ermitteln.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Das vertikale Auslassungszeichen-Menü auswählen und *Speicher entdecken* auswählen


Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.



[[modify-storage-backends]]
== Speicherbackends ändern

Sie können die Zugangsdaten für das Storage-Backend oder den Portnamen ändern. Das Storage-Backend für globale ONTAP Cluster kann auch mit ONTAP tools Manager angepasst werden. Wenn das Zertifikat in 30 Tagen oder weniger abläuft, zeigt ONTAP tools eine Warnung an. Das Storage-Backend sollte angepasst und das neue Zertifikat vom ONTAP Administrator hochgeladen werden.

Wenn Sie das Speicher-Backend ändern, führen ONTAP tools for VMware vSphere eine Erkennung des Speicher-Backends durch, um die Speicherdetails zu aktualisieren.

Befolgen Sie die Schritte in diesem Abschnitt, um ein Speicher-Back-End zu ändern.

. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Wählen Sie das vertikale Auslassungszeichen-Menü und dann *Ändern*, um die Anmeldeinformationen oder den Portnamen zu ändern. Der Fortschritt kann im Bereich „Letzte Aufgaben“ verfolgt werden.


Ändern Sie globale ONTAP Cluster mit dem ONTAP -Tools-Manager wie folgt.

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste Speicher-Back-Ends aus.
. Wählen Sie das zu ändernde Speicher-Back-End aus.
. Das Menü mit den vertikalen Auslassungspunkten auswählen und *Ändern* wählen.
. Sie können die Anmeldeinformationen oder den Port ändern. Geben Sie den *Username* und das *Passwort* ein, um das Speicher-Backend zu ändern.




[[remove-storage-backends]]
== Entfernen Sie die Speicher-Back-Ends

Sie müssen alle an das Speicher-Backend angeschlossenen Datenspeicher entfernen, bevor Sie es entfernen.  Führen Sie die folgenden Schritte aus, um ein Speicher-Backend zu entfernen.

. Melden Sie sich beim vSphere-Client an.
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie im linken Bereich der ONTAP -Tools zu *Storage Backends* und wählen Sie ein Storage Backend aus.
. Wählen Sie das Menü mit den drei vertikalen Punkten und dann *Entfernen*. Es sollte sichergestellt sein, dass das Storage-Backend keine Datenspeicher enthält. Der Fortschritt lässt sich im Bereich „Letzte Aufgaben“ nachverfolgen.


Sie können globale ONTAP-Cluster mit ONTAP tools Manager entfernen.

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Wählen Sie das Storage-Backend aus, das Sie entfernen möchten
. Das Menü mit den vertikalen Auslassungspunkten auswählen und *Entfernen* wählen.




[[drill-down-view-of-storage-backend]]
== Drilldown-Ansicht des Storage-Back-End

Die Seite „Speicher-Backend“ listet alle Speicher-Backends auf. Sie können die hinzugefügten Speicher-Backends ermitteln, ändern und entfernen, aber diese Vorgänge können nicht für die einzelnen untergeordneten SVMs im Cluster durchgeführt werden.

Wählen Sie den übergeordneten oder untergeordneten Cluster aus, um die Komponentenübersicht anzuzeigen.  Verwenden Sie für den übergeordneten Cluster das Dropdown-Menü „Aktionen“, um Speicher zu ermitteln und das Speicher-Backend zu ändern oder zu entfernen.

Die Übersichtsseite enthält folgende Details:

* Status des Storage-Backends
* Kapazitätsinformationen
* Grundlegende Informationen zur VM
* Zertifikatsdetails wie Zertifikatsstatus und Ablaufdatum.
* Netzwerkinformationen wie IP-Adresse und Port des Netzwerks.  Für die untergeordnete SVM sind die Informationen dieselben wie für das übergeordnete Speicher-Backend.
* Privileges erlaubt und eingeschränkt für das Storage-Backend. Für das untergeordnete SVM sind die Informationen dieselben wie für das übergeordnete Storage-Backend. ONTAP tools zeigt Privileges nur bei clusterbasierten Storage-Backends an. Wenn Sie SVM als Storage-Backend hinzufügen, werden keine Privileges-Informationen angezeigt.
* Die Drilldown-Ansicht des ASA r2 Systemclusters enthält nicht die Registerkarte „Lokale Ebenen“, wenn die Eigenschaft „disaggregated“ für die SVM oder den Cluster auf „true“ gesetzt ist.
* Bei ASA r2 SVM-Systemen wird das Kapazitäts-Portlet nicht angezeigt. Das Kapazitäts-Portlet ist nur erforderlich, wenn die Eigenschaft „disaggregiert“ für die SVM oder den Cluster auf „true“ gesetzt ist.
* Für ASA r2 SVM-Systeme wird im Abschnitt grundlegende Informationen der Plattformtyp angezeigt.


Die Registerkarte Schnittstelle enthält detaillierte Informationen zur Schnittstelle.

Auf der Registerkarte „Lokale Ebenen“ finden Sie detaillierte Informationen zur Aggregatliste.
