---
permalink: manage/storage-view-datastore.html 
sidebar: sidebar 
keywords: ONTAP storage view datastores, datastore volume details, NFS VMFS vVol datastore insights, ONTAP tools storage visibility 
summary: Details zu Datenspeicher und Volumes sind auf der ONTAP Storage-Seite in ONTAP tools for VMware vSphere verfügbar. 
---
= ONTAP-Speicheransichten für Datenspeicher in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere zeigt auf der Registerkarte *Konfigurieren* ONTAP-seitige Details für Datenspeicher und deren Volumes an, einschließlich Storage-Backend-, Aggregat- und Volume-Details für jeden Datenspeichertyp.

.Schritte
. Im vSphere Client-Inventar den Datenspeicher auswählen.
. Wählen Sie im rechten Fensterbereich die Registerkarte *Configure* aus.
. Wählen Sie * NetApp ONTAP -Tools* > * ONTAP Speicher*. Die Ansicht ändert sich je nach Datenspeichertyp.  Siehe die folgende Tabelle:


|===


| *Datenspeichertyp* | *Informationen verfügbar* 


| NFS Datenspeicher | Die Seite *Speicherdetails* enthält Informationen zum Storage-Backend, zum Aggregat und zum Volume. Die Seite *NFS details* enthält Daten zum NFS-Datenspeicher. Hinweis: Wenn der nconnect-Wert außerhalb von ONTAP tools geändert wird, spiegelt der in ONTAP tools angezeigte Wert diese externe Änderung möglicherweise nicht wider. 


| VMFS-Datastores | Die Seite *Speicherdetails* enthält Informationen zum Storage-Backend, Aggregat, Volume und zur Storage Availability Zone (SAZ). Die Seite *Speichereinheitendetails* enthält Details zur Speichereinheit. 


| VVols Datastores | Auf dieser Seite werden alle Volumes aufgelistet. Im ONTAP Speicherbereich kann Speicher erweitert oder entfernt werden. ONTAP tools for VMware vSphere unterstützt diese Ansicht nicht für ASA r2 systembasierte vVols Datenspeicher. 
|===
.Ergebnis
Die Details des ONTAP-seitigen Datenspeichers lassen sich abhängig vom ausgewählten Datenspeichertyp anzeigen.
