---
permalink: manage/uninstall-deployment.html 
sidebar: sidebar 
keywords: uninstall ONTAP tools, remove ONTAP tools deployment, appliance decommission workflow, graceful deployment termination 
summary: Die ONTAP tools for VMware vSphere Bereitstellung wird ordnungsgemäß beendet. 
---
= Deinstallation Ihrer ONTAP tools für VMware vSphere Bereitstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Deinstallation von ONTAP tools for VMware vSphere werden alle Daten in den Tools gelöscht, daher sollten diese Schritte abgeschlossen werden, um die Bereitstellung ordnungsgemäß zu beenden und unerwarteten Datenverlust zu vermeiden.

.Schritte
. Entfernen oder verschieben Sie alle virtuellen Maschinen aus den ONTAP-Tools für von VMware vSphere gemanagte Datastores.
+
** Informationen zum Entfernen der virtuellen Maschinen finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Entfernen Sie VMs und VM-Vorlagen und registrieren Sie sie erneut"]
** Um sie in einen nicht verwalteten Datenspeicher zu verschieben, siehe  https://techdocs.broadcom.com/["Broadcom Technische Dokumentation"] zum Migrieren von virtuellen Maschinen mit Storage vMotion


. link:../manage/delete-ds.html["Löschen Sie Datastores"] Auf ONTAP Tools für VMware vSphere erstellt.
. Wenn Sie den VASA-Provider aktiviert haben, wählen Sie in den ONTAP-Tools *Einstellungen* > *VASA-Provider-Einstellungen* > *Registrierung aufheben* aus, um die Registrierung der VASA-Anbieter von allen vCenter-Servern aufzuheben.
. Aufheben der Zuordnung aller Speicher-Back-Ends zur vCenter Server-Instanz. Siehe link:../manage/manage-vcenter.html["Trennen Sie Storage Back-Ends von der vCenter Server-Instanz"].
. Löschen Sie alle Speicher-Back-Ends. Siehe link:../manage/storage-backend.html["Managen von Storage-Back-Ends"].
. Entfernen Sie den SRA-Adapter aus VMware Live Site Recovery:
+
.. Melden Sie sich als Administrator an der VMware Live Site Recovery-Appliance-Managementschnittstelle über Port 5480 an.
.. Wählen Sie *Storage Replication Adapter* Aus.
.. Wählen Sie die entsprechende SRA-Karte aus, und wählen Sie im Dropdown-Menü *Löschen* aus.
.. Bestätigen Sie, dass Sie die Ergebnisse des Löschens des Adapters kennen, und wählen Sie *Löschen*.


. Löschen Sie die in den ONTAP Tools für VMware vSphere gespeicherten vCenter Server-Instanzen. Siehe link:../manage/manage-vcenter.html["Verwalten von vCenter Server-Instanzen"].
. Schalten Sie die ONTAP-Tools für VMware vSphere-VMs vom vCenter-Server aus und löschen Sie die VMs.


.Was kommt als Nächstes?
link:../manage/delete-deployment.html["Entfernen Sie FlexVol Volumes"]
