---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords: unmount NFS VMFS datastore, remove datastore from host, ONTAP tools datastore unmount, ESXi host storage detach 
summary: NFS- oder VMFS-Datenspeicher werden mithilfe von ONTAP tools von ESXi Hosts ausgehängt. 
---
= NFS- und VMFS-Datenspeicher in ONTAP tools aushängen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Aufgabe dient dazu, einen NFS- oder VMFS-Datenspeicher von ESXi-Hosts zu trennen. Das Trennen von Datenspeichern auf Cluster-Ebene wird weder über die Benutzeroberfläche noch über APIs unterstützt.

Ab ONTAP tools 10.6 ist das Aushängen für geschützte VMFS-Datenspeicher blockiert.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein NFS- oder VMFS-Datenspeicherobjekt und wählen Sie *Datenspeicher aushängen*.
+
Der vSphere Client öffnet ein Dialogfeld und listet die ESXi-Hosts auf, die den Datenspeicher eingebunden haben. Wenn der Datenspeicher geschützt ist, blockieren die ONTAP tools die Anfrage und zeigen eine Meldung an, dass der Datenspeicher unter Schutz steht und nicht ausgehängt werden kann.

. Wählen Sie einen oder mehrere ESXi-Hosts aus, um die Bereitstellung des Datastore aufzuheben.
+
Sie können den Datastore nicht von allen Hosts abladen. Die Benutzeroberfläche schlägt vor, dass Sie stattdessen den Vorgang zum Löschen von Datenspeichern verwenden.

. Wählen Sie die Schaltfläche *Unmount*.
+
Die Option *Datenspeicher aushängen* ist nur verfügbar, wenn der Host außerhalb des geschützten Host-Clusters verschoben wird.




NOTE: Wenn ein Datenspeicher geschützt ist, muss der Schutz aufgehoben werden, bevor er ausgehängt werden kann.

.Was kommt als Nächstes?
Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.
