---
permalink: manage/update-proxyurl.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können Protokolldateien für ONTAP-Tools für VMware vSphere über die in den ONTAP-Tools für die grafische Benutzeroberfläche von VMware vSphere \(GUI\) verfügbaren Optionen sammeln. Der technische Support fordert Sie möglicherweise auf, die Protokolldateien zu sammeln, damit Sie Probleme beheben können.' 
---
= Aktualisieren Sie die AutoSupport-Proxy-URL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aktualisieren Sie die AutoSupport-Proxy-URL, um sicherzustellen, dass die AutoSupport-Funktion in Szenarien funktioniert, in denen ein Proxyserver für die Netzwerkzugriffskontrolle oder Sicherheitsmaßnahmen verwendet wird. Damit können die AutoSupport-Daten über den entsprechenden Proxy geleitet werden, um eine sichere Übertragung und Compliance zu ermöglichen.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Einstellungen* aus.
. Wählen Sie die Option *Einstellungen* > *Telemetrie* > *Bearbeiten*.
. Geben Sie eine gültige *Proxy-URL* ein und speichern Sie die Änderungen.
+
Wenn Sie AutoSupport deaktivieren, ist auch die Proxy-URL deaktiviert.


