---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: Sie können die vCenter Server- und ONTAP-Anmeldeinformationen über die Wartungskonsole aktualisieren. 
---
= Aktualisieren Sie die vCenter Server- und ONTAP-Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die vCenter Server-Instanz und die ONTAP-Anmeldeinformationen über die Wartungskonsole aktualisieren.

.Bevor Sie beginnen
Sie müssen über Anmeldedaten für Wartungsbenutzer verfügen.

.Über diese Aufgabe
Wenn Sie die Anmeldeinformationen für vCenter Server, ONTAP oder Data LIF nach der Bereitstellung geändert haben, aktualisieren Sie diese mit diesem Verfahren.

.Schritte
. Öffnen Sie über den vCenter Server eine Konsole für VASA Provider.
. Melden Sie sich als Wartungbenutzer an.
. Geben Sie ein `2` , um das Menü Systemkonfiguration auszuwählen.
. Geben Sie ein, `9` um die ONTAP-Anmeldedaten zu ändern.
. Geben Sie ein, `10` um die vCenter-Anmeldedaten zu ändern.

